#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.2 effective-5.10 (swiftlang-6.3.2.1.108 clang-2100.1.1.101)
#ifndef SPREEDLYPAYPAL_SWIFT_H
#define SPREEDLYPAYPAL_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SpreedlyPayPal",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SpreedlyPayPal",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_ENUM_FWD_DECL(NSInteger, PayPalButtonColor)
SWIFT_ENUM_FWD_DECL(NSInteger, PayPalButtonEdges)
SWIFT_ENUM_FWD_DECL(NSInteger, PayPalButtonSize)
SWIFT_ENUM_FWD_DECL(NSInteger, PayPalButtonLabel)
SWIFT_ENUM_FWD_DECL(NSInteger, PayPalButtonKind)
@class NSNumber;
/// Merchant styling for PPCP buttons. One instance can drive the whole button container;
/// Spreedly maps these fields onto PayPal <code>PaymentButtons</code> (Venmo is drawn by Spreedly).
/// Typical merchant path: build once → pass to <code>SpreedlyPayPalButtonContainer</code> / <code>…View</code>.
SWIFT_CLASS("_TtC14SpreedlyPayPal22PayPalButtonAppearance")
@interface PayPalButtonAppearance : NSObject
/// Face color. Unsupported colors for Credit/Venmo fall back via <code>resolvedColor(_:for:)</code>.
@property (nonatomic, readonly) enum PayPalButtonColor color;
/// Corner shape (rectangle / soft / pill / custom radius).
@property (nonatomic, readonly) enum PayPalButtonEdges edges;
/// Layout size forwarded to PayPal PaymentButtons (including <code>.mini</code>).
@property (nonatomic, readonly) enum PayPalButtonSize size;
/// Used only when <code>edges == .custom</code>; capped at half the button height when rendered.
@property (nonatomic, readonly) CGFloat customCornerRadius;
/// PayPal-button copy only (<code>.checkout</code> / <code>.buyNow</code> / <code>.payWith</code>). Ignored on Pay Later / Credit / Venmo.
@property (nonatomic, readonly) enum PayPalButtonLabel label;
/// Objective-C cannot express <code>NSDirectionalEdgeInsets?</code>. Use this initializer to set custom
/// padding; use the initializer without <code>insets:</code> to inherit PayPal’s per-size default.
- (nonnull instancetype)initWithColor:(enum PayPalButtonColor)color edges:(enum PayPalButtonEdges)edges size:(enum PayPalButtonSize)size customCornerRadius:(CGFloat)customCornerRadius label:(enum PayPalButtonLabel)label insets:(NSDirectionalEdgeInsets)insets;
/// Objective-C bridge — the designated Swift init isn’t <code>@objc</code>-visible because
/// <code>NSDirectionalEdgeInsets?</code> isn’t representable in Objective-C. Use this initializer to
/// inherit PayPal’s per-size default padding.
- (nonnull instancetype)initWithColor:(enum PayPalButtonColor)color edges:(enum PayPalButtonEdges)edges size:(enum PayPalButtonSize)size customCornerRadius:(CGFloat)customCornerRadius label:(enum PayPalButtonLabel)label;
/// <code>true</code> when custom padding was supplied. Readback for Objective-C.
@property (nonatomic, readonly) BOOL hasCustomInsets;
/// Custom padding, or <code>.zero</code> when unset. Check <code>hasCustomInsets</code> first.
@property (nonatomic, readonly) NSDirectionalEdgeInsets objcInsets;
/// Default gold PayPal button with soft edges, collapsed size.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) PayPalButtonAppearance * _Nonnull default_;)
+ (PayPalButtonAppearance * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
/// Step merchants use (or the container uses for them): pick a safe color per funding source.
/// Returns <code>color</code> when valid for <code>kind</code>, otherwise that button’s brand default.
+ (enum PayPalButtonColor)resolvedColor:(enum PayPalButtonColor)color for:(enum PayPalButtonKind)kind SWIFT_WARN_UNUSED_RESULT;
/// Objective-C bridge — Swift <code>[PayPalButtonColor]</code> is not visible to ObjC.
+ (NSArray<NSNumber *> * _Nonnull)allowedColorsRawFor:(enum PayPalButtonKind)kind SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_ENUM_FWD_DECL(NSInteger, PayPalFundingSource)
@class NSCoder;
/// Shared UIKit host for PayPal / Pay Later / Credit buttons.
/// Merchant mental model: this is <em>not</em> a network call — it wraps PayPal’s local <code>PaymentButton</code>,
/// applies Spreedly appearance, and fires <code>onTap</code> so the app can start checkout.
/// Subclasses implement <code>makeButton(appearance:)</code> to pick the concrete PayPal product button.
SWIFT_CLASS("_TtC14SpreedlyPayPal20PayPalButtonBaseView")
@interface PayPalButtonBaseView : UIView
/// Side length for the PayPal-wallet <code>.mini</code> monogram circle (matches PayPal demo visual).
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat miniMonogramSide;)
+ (CGFloat)miniMonogramSide SWIFT_WARN_UNUSED_RESULT;
/// Merchant / app handler — typically calls <code>SpreedlyPayPalCheckout.startCheckout</code>.
@property (nonatomic, copy) void (^ _Nullable onTap)(void);
/// Funding source represented by this button; used for telemetry when tapped.
/// Subclasses set this after <code>super.init</code>. That assignment must rebuild — <code>super.init</code>
/// runs <code>rebuild()</code> while this is still the default <code>.paypal</code>, which would otherwise
/// lock Pay Later / Credit mini into the 36×36 circle path.
@property (nonatomic) enum PayPalFundingSource fundingSource;
/// Merchant styling. Changing this rebuilds the underlying PayPal <code>PaymentButton</code>.
@property (nonatomic, strong) PayPalButtonAppearance * _Nonnull appearance;
/// Enables or disables the wrapped button.
@property (nonatomic) BOOL isEnabled;
- (nonnull instancetype)initWithAppearance:(PayPalButtonAppearance * _Nonnull)appearance OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
/// Height/width the layout system should reserve.
/// <ul>
///   <li>
///     PayPal-wallet <code>.mini</code> → fixed 36×36 circle (PayPal demo monogram).
///   </li>
///   <li>
///     Pay Later / Credit <code>.mini</code> → content width (rounded rectangle with label — not a circle).
///     PayPal’s PaymentButtons reports 36×24 for every mini, which truncates those labels.
///   </li>
/// </ul>
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

/// Button color. Not every color is valid for every button (Credit supports white/black/darkBlue);
/// unsupported values fall back to the button’s default.
typedef SWIFT_ENUM(NSInteger, PayPalButtonColor, open) {
  PayPalButtonColorGold = 0,
  PayPalButtonColorWhite = 1,
  PayPalButtonColorBlack = 2,
  PayPalButtonColorSilver = 3,
  PayPalButtonColorBlue = 4,
  PayPalButtonColorDarkBlue = 5,
};

/// Corner treatment for a PayPal button.
typedef SWIFT_ENUM(NSInteger, PayPalButtonEdges, open) {
/// Rectangle — 0pt corner radius (<code>PaymentButtonEdges.hardEdges</code>).
  PayPalButtonEdgesHard = 0,
/// Rounded — 4pt corner radius (<code>PaymentButtonEdges.softEdges</code>).
  PayPalButtonEdgesSoft = 1,
/// Pill — half the button height (<code>PaymentButtonEdges.rounded</code>).
  PayPalButtonEdgesRounded = 2,
/// Custom corner radius — use <code>PayPalButtonAppearance.customCornerRadius</code>. The rendered
/// radius is capped at half the button’s height by the wrapper view.
  PayPalButtonEdgesCustom = 3,
};

/// Identifies which PPCP button type is being styled (for color validation).
typedef SWIFT_ENUM_NAMED(NSInteger, PayPalButtonKind, "PayPalButtonKind", open) {
  PayPalButtonKindPayPal = 0,
  PayPalButtonKindPayLater = 1,
  PayPalButtonKindCredit = 2,
  PayPalButtonKindVenmo = 3,
};

/// Optional label on the generic PayPal button (not Pay Later or Credit).
typedef SWIFT_ENUM(NSInteger, PayPalButtonLabel, open) {
  PayPalButtonLabelNone = 0,
  PayPalButtonLabelCheckout = 1,
  PayPalButtonLabelBuyNow = 2,
  PayPalButtonLabelPayWith = 3,
};

/// Size category for a PayPal button. Maps 1:1 onto PayPal <code>PaymentButtonSize</code>.
/// Merchant guide: <code>.mini</code> = compact monogram; <code>.collapsed</code> = wordmark; <code>.expanded</code> / <code>.full</code> = wordmark + optional label text.
typedef SWIFT_ENUM(NSInteger, PayPalButtonSize, open) {
/// Compact size (~36pt tall). Shape depends on funding:
/// PayPal wallet / Venmo → circle monogram; Pay Later / Credit → rounded rect with logo + label.
  PayPalButtonSizeMini = 0,
/// Wordmark only — default / most common checkout size.
  PayPalButtonSizeCollapsed = 1,
/// Wordmark + suffix; PayPal <code>label</code> can show here.
  PayPalButtonSizeExpanded = 2,
/// Prefix + wordmark + suffix; tallest layout.
  PayPalButtonSizeFull = 3,
};

@class NSString;
/// Payload delivered when the buyer cancels the PPCP web checkout.
SWIFT_CLASS("_TtC14SpreedlyPayPal16PayPalCancelData")
@interface PayPalCancelData : NSObject
/// Order id that was in flight when the buyer canceled, if known.
@property (nonatomic, readonly, copy) NSString * _Nullable orderId;
/// Boxed <code>PayPalFundingSource</code> raw value for Objective-C. <code>nil</code> when unknown.
@property (nonatomic, readonly, strong) NSNumber * _Nullable fundingSourceRaw;
/// Short cancel reason, if known.
@property (nonatomic, readonly, copy) NSString * _Nullable message;
/// Convenience matching the original <code>orderId</code>-only initializer.
- (nonnull instancetype)initWithOrderId:(NSString * _Nullable)orderId;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PayPalCheckoutResult;
/// Delegate for PPCP checkout outcomes. Provides an Objective-C-friendly callback surface
/// equivalent to the Swift closure API on <code>SpreedlyPayPalCheckout</code>.
SWIFT_PROTOCOL("_TtP14SpreedlyPayPal22PayPalCheckoutDelegate_")
@protocol PayPalCheckoutDelegate
/// Called when the buyer approves the order and the merchant backend finishes capture.
- (void)payPalCheckoutDidApprove:(PayPalCheckoutResult * _Nonnull)result;
/// Called when the buyer cancels the checkout.
- (void)payPalCheckoutDidCancel:(PayPalCancelData * _Nonnull)data;
/// Called when the checkout fails. <code>error</code> is a <code>SpreedlyCore.PayPalError</code>.
- (void)payPalCheckoutDidFailWithError:(NSError * _Nonnull)error;
@end

/// Errors thrown while initializing PPCP checkout.
typedef SWIFT_ENUM(NSInteger, PayPalCheckoutInitializationErrorCode, open) {
  PayPalCheckoutInitializationErrorCodeMissingClientId = 0,
  PayPalCheckoutInitializationErrorCodeInvalidReturnURL = 1,
  PayPalCheckoutInitializationErrorCodeAlreadyInitialized = 2,
  PayPalCheckoutInitializationErrorCodeDeviceBlocked = 3,
};

/// PayPal Orders <code>intent</code> the merchant backend should send on create-order.
/// Derived from <code>PayPalCheckoutSessionOptions.commit</code> (<code>true</code> → capture, <code>false</code> → authorize).
typedef SWIFT_ENUM(NSInteger, PayPalCheckoutIntent, open) {
  PayPalCheckoutIntentCapture = 0,
  PayPalCheckoutIntentAuthorize = 1,
};

/// Terminal result of a completed PPCP checkout (order approved and captured by the merchant backend).
SWIFT_CLASS("_TtC14SpreedlyPayPal20PayPalCheckoutResult")
@interface PayPalCheckoutResult : NSObject
/// Approved PayPal order id.
@property (nonatomic, readonly, copy) NSString * _Nonnull orderId;
/// PayPal payer id from the approval.
@property (nonatomic, readonly, copy) NSString * _Nonnull payerId;
/// Funding source used for the order.
@property (nonatomic, readonly) enum PayPalFundingSource fundingSource;
/// Transaction state after capture (typically “pending” until the backend settles).
@property (nonatomic, readonly, copy) NSString * _Nonnull state;
- (nonnull instancetype)initWithOrderId:(NSString * _Nonnull)orderId payerId:(NSString * _Nonnull)payerId fundingSource:(enum PayPalFundingSource)fundingSource state:(NSString * _Nonnull)state OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Per-checkout options that override module defaults for a single PPCP session.
/// Merchant: pass into <code>startCheckout</code> / <code>start</code>.
/// <ul>
///   <li>
///     <code>commit: true</code> → SDK calls your <code>captureOrder</code> after approval.
///   </li>
///   <li>
///     <code>commit: false</code> → SDK skips capture; your <code>createOrder(..., intent: .authorize)</code> must support AUTHORIZE.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC14SpreedlyPayPal28PayPalCheckoutSessionOptions")
@interface PayPalCheckoutSessionOptions : NSObject
/// When <code>true</code> (default), the SDK calls <code>captureOrder</code> after approval.
/// When <code>false</code>, the SDK skips capture and passes <code>.authorize</code> to <code>createOrder(fundingSource:intent:)</code>
/// so the merchant backend can create the order with <code>intent=AUTHORIZE</code>.
@property (nonatomic, readonly) BOOL commit;
/// Optional Spreedly transaction token to correlate this checkout with a pending purchase.
@property (nonatomic, readonly, copy) NSString * _Nullable transactionToken;
- (nonnull instancetype)initWithCommit:(BOOL)commit transactionToken:(NSString * _Nullable)transactionToken OBJC_DESIGNATED_INITIALIZER;
/// Default options: commit enabled, no transaction token.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) PayPalCheckoutSessionOptions * _Nonnull default_;)
+ (PayPalCheckoutSessionOptions * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Merchant-controlled visibility inputs for <code>findEligibleMethods(visibility:)</code>.
/// Step (merchant): build from cart currency / amount / country → pass to eligibility
/// and/or <code>SpreedlyPayPalButtonContainer(visibilityConfig:)</code>.
/// <em>Decides which buttons to draw, nothing more</em> — it does not ask PayPal what the buyer
/// is entitled to, so a shown button can still fail at approval time.
SWIFT_CLASS("_TtC14SpreedlyPayPal29PayPalFundingVisibilityConfig")
@interface PayPalFundingVisibilityConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull currencyCode;
@property (nonatomic, readonly, strong) NSNumber * _Nullable amountCents;
@property (nonatomic, readonly, copy) NSString * _Nullable countryCode;
@property (nonatomic, readonly, copy) NSString * _Nullable locale;
- (nonnull instancetype)init;
/// Objective-C initializer without <code>disabledFundingSources</code> (Swift array of enum is not ObjC-visible).
- (nonnull instancetype)initWithCurrencyCode:(NSString * _Nonnull)currencyCode amountCents:(NSNumber * _Nullable)amountCents countryCode:(NSString * _Nullable)countryCode;
@end

/// Objective-C-friendly, block-based counterpart to <code>PayPalOrderProvider</code>.
/// Implementations must invoke exactly one branch of each completion block: either an id/success
/// or an error. <code>SpreedlyPayPalCheckout</code> wraps a conforming object in an internal adapter.
SWIFT_PROTOCOL("_TtP14SpreedlyPayPal23PayPalOrderProviderObjC_")
@protocol PayPalOrderProviderObjC
/// Creates an order and returns its id via <code>completion(orderId, error)</code>.
- (void)createOrderWithFundingSource:(enum PayPalFundingSource)fundingSource completion:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
/// Captures the approved order and reports completion via <code>completion(error)</code>.
- (void)captureOrderWithOrderId:(NSString * _Nonnull)orderId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
@optional
/// Optional. When implemented, the SDK passes <code>intent</code> from <code>PayPalCheckoutSessionOptions.commit</code>.
- (void)createOrderWithFundingSource:(enum PayPalFundingSource)fundingSource intent:(enum PayPalCheckoutIntent)intent completion:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
@end

/// Result of exchanging an approved setup token on the merchant backend.
/// Return this type only after the backend succeeds. Throw on failure — the SDK does not
/// interpret a backend status string. Saved-method identity lives on the merchant backend;
/// <code>label</code> is an optional display hint.
SWIFT_CLASS("_TtC14SpreedlyPayPal24PayPalPaymentTokenResult")
@interface PayPalPaymentTokenResult : NSObject
/// Optional merchant-backend display hint. Not a chargeable vault id.
@property (nonatomic, readonly, copy) NSString * _Nullable label;
/// Always <code>nil</code>. Retained so existing call sites still compile — read <code>label</code> instead.
@property (nonatomic, readonly, copy) NSString * _Nullable customerId;
- (nonnull instancetype)initWithLabel:(NSString * _Nullable)label OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Whether the interrupted session was a checkout or a vault consent sheet.
typedef SWIFT_ENUM(NSInteger, PayPalProcessDeathMode, open) {
  PayPalProcessDeathModeCheckout = 0,
  PayPalProcessDeathModeVault = 1,
};

/// Durable process-death record for merchant reconciliation (source of truth vs event replay).
SWIFT_CLASS("_TtC14SpreedlyPayPal26PayPalProcessDeathRecovery")
@interface PayPalProcessDeathRecovery : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull sessionBindId;
@property (nonatomic, readonly) enum PayPalProcessDeathMode mode;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
- (nonnull instancetype)initWithSessionBindId:(NSString * _Nonnull)sessionBindId mode:(enum PayPalProcessDeathMode)mode message:(NSString * _Nonnull)message OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Merchant-reported MIT / one-click charge outcome for telemetry.
/// Does not carry a PayPal vault payment-token id — the merchant already knows which saved method was charged.
SWIFT_CLASS("_TtC14SpreedlyPayPal21PayPalRecurringResult")
@interface PayPalRecurringResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull orderId;
@property (nonatomic, readonly) BOOL success;
@property (nonatomic, readonly, copy) NSString * _Nullable message;
/// Always empty. Retained so existing call sites still compile.
@property (nonatomic, readonly, copy) NSString * _Nonnull vaultId;
/// Always <code>nil</code>. Retained so existing call sites still compile — read <code>label</code> instead.
@property (nonatomic, readonly, copy) NSString * _Nullable customerId;
- (nonnull instancetype)initWithOrderId:(NSString * _Nonnull)orderId success:(BOOL)success message:(NSString * _Nullable)message OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Result of merchant-backend setup-token creation.
SWIFT_CLASS("_TtC14SpreedlyPayPal22PayPalSetupTokenResult")
@interface PayPalSetupTokenResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull setupTokenId;
@property (nonatomic, readonly, copy) NSString * _Nullable customerId;
- (nonnull instancetype)initWithSetupTokenId:(NSString * _Nonnull)setupTokenId customerId:(NSString * _Nullable)customerId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Buyer-approval payload after setup-token consent and payment-token exchange.
/// <code>label</code> is an optional backend display hint. <code>setupTokenId</code> is session correlation only —
/// not a chargeable vault id.
SWIFT_CLASS("_TtC14SpreedlyPayPal22PayPalVaultApproveData")
@interface PayPalVaultApproveData : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable label;
@property (nonatomic, readonly, copy) NSString * _Nonnull setupTokenId;
/// Always <code>nil</code>. Retained so existing call sites still compile — read <code>label</code> instead.
@property (nonatomic, readonly, copy) NSString * _Nullable customerId;
- (nonnull instancetype)initWithLabel:(NSString * _Nullable)label setupTokenId:(NSString * _Nonnull)setupTokenId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Cancel payload for a vault session.
SWIFT_CLASS("_TtC14SpreedlyPayPal21PayPalVaultCancelData")
@interface PayPalVaultCancelData : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable setupTokenId;
@property (nonatomic, readonly, copy) NSString * _Nullable message;
- (nonnull instancetype)initWithSetupTokenId:(NSString * _Nullable)setupTokenId message:(NSString * _Nullable)message OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PaymentResult;
/// Spreedly merchant delegate for vault outcomes (Objective-C).
SWIFT_PROTOCOL("_TtP14SpreedlyPayPal19PayPalVaultDelegate_")
@protocol PayPalVaultDelegate
- (void)payPalVaultDidApprove:(PayPalVaultApproveData * _Nonnull)result;
@optional
/// Same outcome as <code>payPalVaultDidApprove:</code> plus the published <code>PaymentResult</code> (Swift closure parity).
- (void)payPalVaultDidApprove:(PayPalVaultApproveData * _Nonnull)result paymentResult:(PaymentResult * _Nonnull)paymentResult;
@required
- (void)payPalVaultDidCancel:(PayPalVaultCancelData * _Nonnull)data;
- (void)payPalVaultDidFailWithError:(NSError * _Nonnull)error;
@optional
/// Late payment-token exchange after cancel/supersede — do not treat as vault success.
/// \param setupTokenId Session correlation only.
///
/// \param label Optional backend display hint.
///
- (void)payPalVaultDidOrphanSetupTokenId:(NSString * _Nonnull)setupTokenId label:(NSString * _Nullable)label;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, PayPalVaultUsageType)
/// Per-session options for a purchase-later vault (billing-agreement consent) flow.
SWIFT_CLASS("_TtC14SpreedlyPayPal25PayPalVaultSessionOptions")
@interface PayPalVaultSessionOptions : NSObject
@property (nonatomic, readonly) enum PayPalVaultUsageType usageType;
/// Optional description for PayPal consent UI when the backend supports it.
/// Cross-platform field name is <code>description</code>; Swift uses <code>consentDescription</code> to avoid clashing with <code>NSObject.description</code>.
@property (nonatomic, readonly, copy) NSString * _Nullable consentDescription;
/// Optional returning PayPal customer id.
@property (nonatomic, readonly, copy) NSString * _Nullable customerId;
/// Optional Spreedly transaction token to correlate this vault with a pending purchase.
@property (nonatomic, readonly, copy) NSString * _Nullable transactionToken;
/// Objective-C initializer — <code>usagePattern</code> is passed as an optional <code>NSNumber</code> of <code>PayPalVaultUsagePattern</code> raw values.
- (nonnull instancetype)initWithUsageType:(enum PayPalVaultUsageType)usageType usagePatternNumber:(NSNumber * _Nullable)usagePatternNumber consentDescription:(NSString * _Nullable)consentDescription customerId:(NSString * _Nullable)customerId transactionToken:(NSString * _Nullable)transactionToken OBJC_DESIGNATED_INITIALIZER;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) PayPalVaultSessionOptions * _Nonnull default_;)
+ (PayPalVaultSessionOptions * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Objective-C block-based counterpart to <code>PayPalVaultTokenProvider</code>.
SWIFT_PROTOCOL("_TtP14SpreedlyPayPal28PayPalVaultTokenProviderObjC_")
@protocol PayPalVaultTokenProviderObjC
- (void)createSetupTokenWithOptions:(PayPalVaultSessionOptions * _Nonnull)options completion:(void (^ _Nonnull)(PayPalSetupTokenResult * _Nullable, NSError * _Nullable))completion;
- (void)createPaymentTokenWithSetupTokenId:(NSString * _Nonnull)setupTokenId completion:(void (^ _Nonnull)(PayPalPaymentTokenResult * _Nullable, NSError * _Nullable))completion;
@end

/// Official PayPal <code>usage_pattern</code> values for vault setup and stored-credential charges.
/// Keep the same pattern from setup through CIT/MIT charges.
/// See PayPal “Save payment methods for recurring payments”.
typedef SWIFT_ENUM(NSInteger, PayPalVaultUsagePattern, open) {
  PayPalVaultUsagePatternImmediate = 0,
  PayPalVaultUsagePatternDeferred = 1,
  PayPalVaultUsagePatternRecurringPrepaid = 2,
  PayPalVaultUsagePatternRecurringPostpaid = 3,
  PayPalVaultUsagePatternSubscriptionPrepaid = 4,
  PayPalVaultUsagePatternSubscriptionPostpaid = 5,
  PayPalVaultUsagePatternUnscheduledPrepaid = 6,
  PayPalVaultUsagePatternUnscheduledPostpaid = 7,
  PayPalVaultUsagePatternThresholdPrepaid = 8,
  PayPalVaultUsagePatternThresholdPostpaid = 9,
  PayPalVaultUsagePatternInstallmentPrepaid = 10,
  PayPalVaultUsagePatternInstallmentPostpaid = 11,
};

/// How the vaulted PayPal payment method will be used after consent.
/// Maps to PayPal vault <code>usage_type</code> on the merchant’s setup-token request.
typedef SWIFT_ENUM(NSInteger, PayPalVaultUsageType, open) {
  PayPalVaultUsageTypeMerchant = 0,
  PayPalVaultUsageTypePlatform = 1,
};

@class PayPalEligibilityResult;
/// Vertical stack of eligible PPCP buttons (PayPal, Pay Later, Credit, Venmo).
/// Merchant path (KT): pass <code>visibilityConfig</code> + one <code>appearance</code> → buyer sees all eligible
/// funding sources at once; tap delivers <code>onFundingSourceSelected</code> for <code>startCheckout</code>.
/// Prefer this over standalone buttons so Venmo stays fail-closed.
/// When both <code>visibilityConfig</code> and <code>eligibility</code> are set, <code>visibilityConfig</code> wins.
SWIFT_CLASS("_TtC14SpreedlyPayPal33SpreedlyPayPalButtonContainerView")
@interface SpreedlyPayPalButtonContainerView : UIView
/// Eligibility from <code>findEligibleMethods</code>. Ignored when <code>visibilityConfig</code> is set.
/// <code>nil</code> fail-closes Venmo unless <code>visibilityConfig</code> is used.
@property (nonatomic, strong) PayPalEligibilityResult * _Nullable eligibility;
/// Preferred way to drive button visibility. When set, the stack calls
/// <code>findEligibleMethods(visibility:)</code> (no extra eligible event) and hides every
/// button if the SDK is not initialized.
@property (nonatomic, strong) PayPalFundingVisibilityConfig * _Nullable visibilityConfig;
@property (nonatomic, strong) PayPalButtonAppearance * _Nonnull appearance;
@property (nonatomic) BOOL showPayPal;
@property (nonatomic) BOOL showPayLater;
@property (nonatomic) BOOL showCredit;
@property (nonatomic) BOOL showVenmo;
@property (nonatomic) BOOL isEnabled;
/// Objective-C setter — Swift <code>[PayPalFundingSource]</code> is not visible to ObjC.
- (void)setDisabledFundingSourcesRaw:(NSArray<NSNumber *> * _Nonnull)rawValues;
/// Called when the buyer taps a visible funding button.
@property (nonatomic, copy) void (^ _Nullable onFundingSourceSelected)(enum PayPalFundingSource);
- (nonnull instancetype)initWithAppearance:(PayPalButtonAppearance * _Nonnull)appearance OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
/// Height of the visible button stack so SwiftUI layout reserves space below Pay with.
/// Measures each arranged button’s own <code>intrinsicContentSize</code> rather than assuming a
/// fixed row height — buttons report their real per-size height (see <code>PayPalButtonSize</code>).
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

/// UIKit PayPal button (PaymentButtons <code>PayPalButton</code> under the hood).
/// Merchant: set <code>appearance</code>, set <code>onTap</code> → <code>startCheckout(.paypal, …)</code>. Prefer the container
/// when showing multiple funding sources.
SWIFT_CLASS("_TtC14SpreedlyPayPal24SpreedlyPayPalButtonView")
@interface SpreedlyPayPalButtonView : PayPalButtonBaseView
- (nonnull instancetype)initWithAppearance:(PayPalButtonAppearance * _Nonnull)appearance OBJC_DESIGNATED_INITIALIZER;
@end

@class PayPalCheckoutConfig;
@class NSURL;
@class PayPalError;
/// PPCP checkout entry point (native PayPal buttons + web checkout).
/// Merchant integration steps (read aloud in KT):
/// <ul>
///   <li>
///     Step 1: <code>initialize(config:)</code> once (Client ID + return URL; secret stays on your server).
///   </li>
///   <li>
///     Step 2: Implement <code>PayPalOrderProvider</code> (<code>createOrder</code> / <code>captureOrder</code> → your backend).
///   </li>
///   <li>
///     Step 3: <code>findEligibleMethods(visibility:)</code> then show <code>SpreedlyPayPalButtonContainer</code>.
///   </li>
///   <li>
///     Step 4: On button tap → <code>startCheckout</code> (SDK: create → approve → capture when <code>commit</code>).
///   </li>
///   <li>
///     Alt: <code>start(orderId:)</code> if you already created the order; SDK only runs approval.
///   </li>
/// </ul>
/// Results: <code>Spreedly.shared().subscribeToPaymentResults</code> and/or per-call closures / ObjC delegate.
SWIFT_CLASS("_TtC14SpreedlyPayPal22SpreedlyPayPalCheckout")
@interface SpreedlyPayPalCheckout : NSObject
/// Whether <code>initialize(config:)</code> completed successfully.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isInitialized;)
+ (BOOL)isInitialized SWIFT_WARN_UNUSED_RESULT;
/// Whether a checkout or vault session is currently in flight.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isActive;)
+ (BOOL)isActive SWIFT_WARN_UNUSED_RESULT;
/// PayPal order id or vault setup token of the active session, if any.
+ (NSString * _Nullable)currentOrderId SWIFT_WARN_UNUSED_RESULT;
/// Cancels the active checkout or vault session and publishes a cancel result.
+ (void)cancel;
/// Optional hook to call when your app returns to the foreground.
/// Does nothing: PPCP completes buyer approval inside the web-authentication session, so there
/// is no return to hand back. Safe to call; provided so a shared call site can stay uniform.
+ (void)finalizeIfActive;
/// <code>true</code> when a prior PayPal sheet was interrupted and must be reconciled before a new session.
+ (BOOL)hasUnresolvedProcessDeathRecovery SWIFT_WARN_UNUSED_RESULT;
/// Reads the durable process-death record without clearing it. <code>nil</code> if none or unreadable.
+ (PayPalProcessDeathRecovery * _Nullable)getProcessDeathRecovery SWIFT_WARN_UNUSED_RESULT;
/// Returns and clears a readable process-death record. Prefer get + acknowledge after server confirm.
+ (PayPalProcessDeathRecovery * _Nullable)consumeProcessDeathRecovery SWIFT_WARN_UNUSED_RESULT;
/// Clears the stored record iff it still matches <code>recovery</code> (bind id + mode).
+ (BOOL)acknowledgeProcessDeathRecovery:(PayPalProcessDeathRecovery * _Nonnull)recovery;
/// Clears an undecodable record so checkout can resume after off-band reconciliation.
+ (BOOL)discardUnreadableProcessDeathRecovery;
/// Configures the PayPal SDK for PPCP. Call once before presenting buttons or sessions.
/// \param config Merchant-supplied Client ID, environment, and return URL.
///
+ (BOOL)initializeWithConfig:(PayPalCheckoutConfig * _Nonnull)config error:(NSError * _Nullable * _Nullable)error;
/// Step (merchant): call after <code>initialize</code> to decide which buttons to show.
/// Runs locally on-device. It does <em>not</em> ask PayPal what the buyer is entitled to, so treat
/// the result as a rendering hint only — approval can still fail at checkout time.
/// Venmo is fail-closed (explicit US + USD). Pay Later / Credit use amount bands above.
+ (void)findEligibleMethodsWithCurrency:(NSString * _Nonnull)currency locale:(NSString * _Nonnull)locale country:(NSString * _Nonnull)country amount:(NSString * _Nonnull)amount completionHandler:(void (^ _Nonnull)(PayPalEligibilityResult * _Nullable, NSError * _Nullable))completionHandler;
/// Objective-C wrapper for <code>findEligibleMethods(visibility:)</code>.
/// Swift callers use <code>findEligibleMethods(visibility:)</code> (<code>[PayPalFundingSource]</code>). This
/// companion exists so the ObjC selector is not overloaded on the same Swift name.
+ (NSArray<NSNumber *> * _Nonnull)findEligibleMethodsWithVisibility:(PayPalFundingVisibilityConfig * _Nonnull)visibility SWIFT_WARN_UNUSED_RESULT;
/// Return URL for Venmo Orders <code>payment_source.venmo.experience_context.return_url</code>.
/// Must match the ASWebAuthenticationSession <code>redirect_uri</code> (not <code>PayPalCheckoutConfig.returnURL</code>).
/// Returns <code>nil</code> only if the PayPal callback scheme URL cannot be formed.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nullable venmoWebCheckoutReturnURL;)
+ (NSURL * _Nullable)venmoWebCheckoutReturnURL SWIFT_WARN_UNUSED_RESULT;
/// Cancel URL for Venmo Orders <code>payment_source.venmo.experience_context.cancel_url</code>.
/// Returns <code>nil</code> only if the PayPal callback scheme URL cannot be formed.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nullable venmoWebCheckoutCancelURL;)
+ (NSURL * _Nullable)venmoWebCheckoutCancelURL SWIFT_WARN_UNUSED_RESULT;
/// Opens PayPal’s sign-out page so you can switch buyer accounts between sandbox runs.
/// No-op when <code>initialize(config:)</code> has not been called.
+ (void)signOutOfPayPal;
/// Objective-C wrapper for <code>findEligibleMethods</code>.
+ (void)findEligibleMethodsWithCurrency:(NSString * _Nonnull)currency locale:(NSString * _Nonnull)locale country:(NSString * _Nonnull)country amount:(NSString * _Nonnull)amount completion:(void (^ _Nonnull)(PayPalEligibilityResult * _Nullable, NSError * _Nullable))completion;
/// Runs PayPal approval for an order the merchant already created. The SDK does not capture;
/// the merchant authorizes/captures <code>orderId</code> on their backend after <code>onApprove</code>.
/// \param orderId A PayPal order id created by the merchant backend.
///
/// \param fundingSource Funding source the buyer selected.
///
/// \param options Per-session overrides (defaults to <code>.default</code>).
///
/// \param onApprove Called after the buyer approves.
///
/// \param onCancel Called when the buyer cancels.
///
/// \param onError Called with a <code>PayPalError</code> on failure.
///
+ (void)startWithOrderId:(NSString * _Nonnull)orderId fundingSource:(enum PayPalFundingSource)fundingSource options:(PayPalCheckoutSessionOptions * _Nonnull)options onApprove:(void (^ _Nonnull)(PayPalCheckoutResult * _Nonnull))onApprove onCancel:(void (^ _Nonnull)(PayPalCancelData * _Nonnull))onCancel onError:(void (^ _Nonnull)(PayPalError * _Nonnull))onError;
/// Objective-C entry point for a full PPCP checkout using a block-based order provider and delegate.
+ (void)startCheckoutWithFundingSource:(enum PayPalFundingSource)fundingSource options:(PayPalCheckoutSessionOptions * _Nonnull)options orderProvider:(id <PayPalOrderProviderObjC> _Nonnull)orderProvider delegate:(id <PayPalCheckoutDelegate> _Nonnull)delegate;
/// Objective-C entry point for approving a merchant-created order. Capture is merchant-side.
+ (void)startWithOrderId:(NSString * _Nonnull)orderId fundingSource:(enum PayPalFundingSource)fundingSource options:(PayPalCheckoutSessionOptions * _Nonnull)options delegate:(id <PayPalCheckoutDelegate> _Nonnull)delegate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface SpreedlyPayPalCheckout (SWIFT_EXTENSION(SpreedlyPayPal))
/// Objective-C entry point for purchase-later vault using a block-based provider and delegate.
+ (void)startVaultSessionWithProvider:(id <PayPalVaultTokenProviderObjC> _Nonnull)provider options:(PayPalVaultSessionOptions * _Nonnull)options delegate:(id <PayPalVaultDelegate> _Nonnull)delegate;
/// Reports a merchant-server recurring (MIT) charge outcome for telemetry.
/// Spreedly does not charge the vault — call this after your backend creates an order with <code>vault_id</code>.
+ (void)publishRecurringResult:(PayPalRecurringResult * _Nonnull)result;
@end

/// UIKit PayPal Credit button. Merchant: <code>onTap</code> → <code>startCheckout(.credit, …)</code>.
/// Supported colors: white / black / darkBlue — others fall back to darkBlue.
SWIFT_CLASS("_TtC14SpreedlyPayPal30SpreedlyPayPalCreditButtonView")
@interface SpreedlyPayPalCreditButtonView : PayPalButtonBaseView
- (nonnull instancetype)initWithAppearance:(PayPalButtonAppearance * _Nonnull)appearance OBJC_DESIGNATED_INITIALIZER;
@end

/// UIKit Pay Later button (PaymentButtons). Merchant: <code>onTap</code> → <code>startCheckout(.payLater, …)</code>.
/// Label on <code>PayPalButtonAppearance</code> is ignored here.
SWIFT_CLASS("_TtC14SpreedlyPayPal32SpreedlyPayPalPayLaterButtonView")
@interface SpreedlyPayPalPayLaterButtonView : PayPalButtonBaseView
- (nonnull instancetype)initWithAppearance:(PayPalButtonAppearance * _Nonnull)appearance OBJC_DESIGNATED_INITIALIZER;
@end

/// Custom Venmo PPCP button — PayPal PaymentButtons has no Venmo product, so Spreedly draws it.
/// Merchant note: color stays Venmo blue; size / edges / insets mirror the PayPal buttons beside it.
/// Prefer showing this via <code>SpreedlyPayPalButtonContainer</code> (eligibility gate) rather than alone.
SWIFT_CLASS("_TtC14SpreedlyPayPal19VenmoButtonBaseView")
@interface VenmoButtonBaseView : UIView
/// Same contract as PayPal hosts — typically starts Venmo checkout.
@property (nonatomic, copy) void (^ _Nullable onTap)(void);
/// Shared appearance with sibling PayPal buttons (color ignored for face fill).
@property (nonatomic, strong) PayPalButtonAppearance * _Nonnull appearance;
@property (nonatomic) BOOL isEnabled;
- (nonnull instancetype)initWithAppearance:(PayPalButtonAppearance * _Nonnull)appearance OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
/// Matches PayPal’s own <code>PaymentButton.intrinsicContentSize</code> per size — Venmo has no
/// underlying <code>PaymentButton</code> to forward, so this must be kept in sync manually.
/// <code>.mini</code> is a compact rounded rect sized to the wordmark, not a forced circle.
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

/// UIKit Venmo button for PPCP.
/// Merchant: prefer the container (eligibility). If standalone, call <code>findEligibleMethods</code> first,
/// then <code>onTap</code> → <code>startCheckout(.venmo, …)</code>.
SWIFT_CLASS("_TtC14SpreedlyPayPal23SpreedlyVenmoButtonView")
@interface SpreedlyVenmoButtonView : VenmoButtonBaseView
- (nonnull instancetype)initWithAppearance:(PayPalButtonAppearance * _Nonnull)appearance OBJC_DESIGNATED_INITIALIZER;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
