#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.2 effective-5.10 (swiftlang-6.3.2.1.108 clang-2100.1.1.101)
#ifndef SPREEDLYPAYPAL_SWIFT_H
#define SPREEDLYPAYPAL_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SpreedlyPayPal",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SpreedlyPayPal",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
SWIFT_ENUM_FWD_DECL(NSInteger, PayPalFundingSource)
/// Buyer-approval payload delivered when a PPCP order is approved in the web checkout.
SWIFT_CLASS("_TtC14SpreedlyPayPal17PayPalApproveData")
@interface PayPalApproveData : NSObject
/// PayPal order id approved by the buyer.
@property (nonatomic, readonly, copy) NSString * _Nonnull orderId;
/// PayPal payer id from the approval.
@property (nonatomic, readonly, copy) NSString * _Nonnull payerId;
/// Funding source used for this approval.
@property (nonatomic, readonly) enum PayPalFundingSource fundingSource;
- (nonnull instancetype)initWithOrderId:(NSString * _Nonnull)orderId payerId:(NSString * _Nonnull)payerId fundingSource:(enum PayPalFundingSource)fundingSource OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_ENUM_FWD_DECL(NSInteger, PayPalButtonColor)
SWIFT_ENUM_FWD_DECL(NSInteger, PayPalButtonEdges)
SWIFT_ENUM_FWD_DECL(NSInteger, PayPalButtonSize)
SWIFT_ENUM_FWD_DECL(NSInteger, PayPalButtonLabel)
SWIFT_ENUM_FWD_DECL(NSInteger, PayPalButtonKind)
@class NSNumber;
/// Appearance for Spreedly’s PPCP buttons, mapped onto the PayPal <code>PaymentButtons</code> design system.
SWIFT_CLASS("_TtC14SpreedlyPayPal22PayPalButtonAppearance")
@interface PayPalButtonAppearance : NSObject
/// PayPal requires at least 10pt for custom corner radius.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat minimumCustomCornerRadius;)
+ (CGFloat)minimumCustomCornerRadius SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) enum PayPalButtonColor color;
@property (nonatomic, readonly) enum PayPalButtonEdges edges;
@property (nonatomic, readonly) enum PayPalButtonSize size;
@property (nonatomic, readonly) CGFloat customCornerRadius;
@property (nonatomic, readonly) enum PayPalButtonLabel label;
- (nonnull instancetype)initWithColor:(enum PayPalButtonColor)color edges:(enum PayPalButtonEdges)edges size:(enum PayPalButtonSize)size customCornerRadius:(CGFloat)customCornerRadius label:(enum PayPalButtonLabel)label OBJC_DESIGNATED_INITIALIZER;
/// Default gold PayPal button with soft edges, collapsed size.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) PayPalButtonAppearance * _Nonnull default_;)
+ (PayPalButtonAppearance * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
/// Returns <code>color</code> when valid for <code>kind</code>, otherwise a sensible default for that button type.
+ (enum PayPalButtonColor)resolvedColor:(enum PayPalButtonColor)color for:(enum PayPalButtonKind)kind SWIFT_WARN_UNUSED_RESULT;
/// Colors supported by the given button type (as <code>NSNumber</code> wrapping <code>PayPalButtonColor</code> raw values).
+ (NSArray<NSNumber *> * _Nonnull)allowedColorsFor:(enum PayPalButtonKind)kind SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSCoder;
/// Shared UIKit host for the PPCP buttons. Owns the wrapped <code>PaymentButton</code>, pins it edge-to-edge,
/// forwards taps to <code>onTap</code>, and rebuilds when <code>appearance</code> changes. Subclasses supply the concrete
/// button via <code>makeButton(appearance:)</code>.
SWIFT_CLASS("_TtC14SpreedlyPayPal20PayPalButtonBaseView")
@interface PayPalButtonBaseView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

/// Button color. Not every color is valid for every button (Credit supports white/black/darkBlue);
/// unsupported values fall back to the button’s default.
typedef SWIFT_ENUM(NSInteger, PayPalButtonColor, open) {
  PayPalButtonColorGold = 0,
  PayPalButtonColorWhite = 1,
  PayPalButtonColorBlack = 2,
  PayPalButtonColorSilver = 3,
  PayPalButtonColorBlue = 4,
  PayPalButtonColorDarkBlue = 5,
};

/// Corner treatment for a PayPal button.
typedef SWIFT_ENUM(NSInteger, PayPalButtonEdges, open) {
/// Rectangle — 0pt corner radius (<code>PaymentButtonEdges.hardEdges</code>).
  PayPalButtonEdgesHard = 0,
/// Rounded — 4pt corner radius (<code>PaymentButtonEdges.softEdges</code>).
  PayPalButtonEdgesSoft = 1,
/// Pill — half the button height (<code>PaymentButtonEdges.rounded</code>).
  PayPalButtonEdgesRounded = 2,
/// Custom corner radius — use <code>PayPalButtonAppearance.customCornerRadius</code> (minimum 10pt).
  PayPalButtonEdgesCustom = 3,
};

/// Identifies which PPCP button type is being styled (for color validation).
typedef SWIFT_ENUM_NAMED(NSInteger, PayPalButtonKind, "PayPalButtonKind", open) {
  PayPalButtonKindPayPal = 0,
  PayPalButtonKindPayLater = 1,
  PayPalButtonKindCredit = 2,
  PayPalButtonKindVenmo = 3,
};

/// Optional label on the generic PayPal button (not Pay Later or Credit).
typedef SWIFT_ENUM(NSInteger, PayPalButtonLabel, open) {
  PayPalButtonLabelNone = 0,
  PayPalButtonLabelCheckout = 1,
  PayPalButtonLabelBuyNow = 2,
  PayPalButtonLabelPayWith = 3,
};

/// Size category for a PayPal button.
typedef SWIFT_ENUM(NSInteger, PayPalButtonSize, open) {
  PayPalButtonSizeMini = 0,
  PayPalButtonSizeCollapsed = 1,
  PayPalButtonSizeExpanded = 2,
  PayPalButtonSizeFull = 3,
};

/// Payload delivered when the buyer cancels the PPCP web checkout.
SWIFT_CLASS("_TtC14SpreedlyPayPal16PayPalCancelData")
@interface PayPalCancelData : NSObject
/// Order id that was in flight when the buyer canceled, if known.
@property (nonatomic, readonly, copy) NSString * _Nullable orderId;
- (nonnull instancetype)initWithOrderId:(NSString * _Nullable)orderId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PayPalCheckoutResult;
/// Delegate for PPCP checkout outcomes. Provides an Objective-C-friendly callback surface
/// equivalent to the Swift closure API on <code>SpreedlyPayPalCheckout</code>.
SWIFT_PROTOCOL("_TtP14SpreedlyPayPal22PayPalCheckoutDelegate_")
@protocol PayPalCheckoutDelegate
/// Called when the buyer approves the order and the merchant backend finishes capture.
- (void)payPalCheckoutDidApprove:(PayPalCheckoutResult * _Nonnull)result;
/// Called when the buyer cancels the checkout.
- (void)payPalCheckoutDidCancel:(PayPalCancelData * _Nonnull)data;
/// Called when the checkout fails. <code>error</code> is a <code>SpreedlyCore.PayPalError</code>.
- (void)payPalCheckoutDidFailWithError:(NSError * _Nonnull)error;
@end

/// Errors thrown while initializing PPCP checkout.
typedef SWIFT_ENUM(NSInteger, PayPalCheckoutInitializationErrorCode, open) {
  PayPalCheckoutInitializationErrorCodeMissingClientId = 0,
  PayPalCheckoutInitializationErrorCodeInvalidReturnURL = 1,
  PayPalCheckoutInitializationErrorCodeAlreadyInitialized = 2,
  PayPalCheckoutInitializationErrorCodeDeviceBlocked = 3,
};

/// Terminal result of a completed PPCP checkout (order approved and captured by the merchant backend).
SWIFT_CLASS("_TtC14SpreedlyPayPal20PayPalCheckoutResult")
@interface PayPalCheckoutResult : NSObject
/// Approved PayPal order id.
@property (nonatomic, readonly, copy) NSString * _Nonnull orderId;
/// PayPal payer id from the approval.
@property (nonatomic, readonly, copy) NSString * _Nonnull payerId;
/// Funding source used for the order.
@property (nonatomic, readonly) enum PayPalFundingSource fundingSource;
/// Transaction state after capture (typically “pending” until the backend settles).
@property (nonatomic, readonly, copy) NSString * _Nonnull state;
- (nonnull instancetype)initWithOrderId:(NSString * _Nonnull)orderId payerId:(NSString * _Nonnull)payerId fundingSource:(enum PayPalFundingSource)fundingSource state:(NSString * _Nonnull)state OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_ENUM_FWD_DECL(NSInteger, PayPalPresentationMode)
/// Per-checkout options that override module defaults for a single PPCP session.
SWIFT_CLASS("_TtC14SpreedlyPayPal28PayPalCheckoutSessionOptions")
@interface PayPalCheckoutSessionOptions : NSObject
/// When <code>true</code>, the order is expected to be captured/authorized by the merchant backend after approval.
/// Purely informational for the SDK; the actual capture happens in the merchant’s <code>captureOrder</code>.
@property (nonatomic, readonly) BOOL commit;
/// Preferred presentation for the web checkout (maps to the underlying web authentication experience).
@property (nonatomic, readonly) enum PayPalPresentationMode presentationMode;
/// Optional Spreedly transaction token to correlate this checkout with a pending purchase.
@property (nonatomic, readonly, copy) NSString * _Nullable transactionToken;
- (nonnull instancetype)initWithCommit:(BOOL)commit presentationMode:(enum PayPalPresentationMode)presentationMode transactionToken:(NSString * _Nullable)transactionToken OBJC_DESIGNATED_INITIALIZER;
/// Default options: commit enabled, automatic presentation, no transaction token.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) PayPalCheckoutSessionOptions * _Nonnull default_;)
+ (PayPalCheckoutSessionOptions * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Objective-C-friendly, block-based counterpart to <code>PayPalOrderProvider</code>.
/// Implementations must invoke exactly one branch of each completion block: either an id/success
/// or an error. <code>SpreedlyPayPalCheckout</code> wraps a conforming object in an internal adapter.
SWIFT_PROTOCOL("_TtP14SpreedlyPayPal23PayPalOrderProviderObjC_")
@protocol PayPalOrderProviderObjC
/// Creates an order and returns its id via <code>completion(orderId, error)</code>.
- (void)createOrderWithFundingSource:(enum PayPalFundingSource)fundingSource completion:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
/// Captures the approved order and reports completion via <code>completion(error)</code>.
- (void)captureOrderWithOrderId:(NSString * _Nonnull)orderId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
@end

/// UIKit PayPal button. Set <code>onTap</code> to start a checkout; style via <code>appearance</code>.
SWIFT_CLASS("_TtC14SpreedlyPayPal24SpreedlyPayPalButtonView")
@interface SpreedlyPayPalButtonView : PayPalButtonBaseView
- (nonnull instancetype)initWithAppearance:(PayPalButtonAppearance * _Nonnull)appearance OBJC_DESIGNATED_INITIALIZER;
@end

@class PayPalCheckoutConfig;
@class PayPalEligibilityResult;
/// PPCP checkout entry point (native PayPal buttons + web checkout).
/// Lifecycle: call <code>initialize(config:)</code> once, then drive a checkout with <code>startCheckout(...)</code>
/// (SDK orchestrates create → approve → capture) or <code>start(orderId:...)</code> (merchant pre-created the
/// order; the SDK only runs the PayPal approval). Results are delivered two ways: a cross-module
/// <code>PaymentResult</code> via <code>Spreedly.shared().subscribeToPaymentResults</code>, and the per-call closures
/// (Swift) or <code>PayPalCheckoutDelegate</code> (Objective-C).
SWIFT_CLASS("_TtC14SpreedlyPayPal22SpreedlyPayPalCheckout")
@interface SpreedlyPayPalCheckout : NSObject
/// Whether <code>initialize(config:)</code> completed successfully.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isInitialized;)
+ (BOOL)isInitialized SWIFT_WARN_UNUSED_RESULT;
/// Configures the PayPal SDK for PPCP. Call once before presenting buttons or sessions.
/// \param config Merchant-supplied Client ID, environment, and return URL.
///
+ (BOOL)initializeWithConfig:(PayPalCheckoutConfig * _Nonnull)config error:(NSError * _Nullable * _Nullable)error;
/// Returns client-side eligibility for PPCP funding sources using PayPal’s published country tables.
/// PayPal iOS SDK has no native eligibility API; this is a Spreedly wrapper for button gating.
+ (void)findEligibleMethodsWithCurrency:(NSString * _Nonnull)currency locale:(NSString * _Nonnull)locale country:(NSString * _Nonnull)country amount:(NSString * _Nonnull)amount completionHandler:(void (^ _Nonnull)(PayPalEligibilityResult * _Nullable, NSError * _Nullable))completionHandler;
/// Objective-C wrapper for <code>findEligibleMethods</code>.
+ (void)findEligibleMethodsWithCurrency:(NSString * _Nonnull)currency locale:(NSString * _Nonnull)locale country:(NSString * _Nonnull)country amount:(NSString * _Nonnull)amount completion:(void (^ _Nonnull)(PayPalEligibilityResult * _Nullable, NSError * _Nullable))completion;
/// Runs PayPal approval for an order the merchant already created. The SDK does not capture;
/// the merchant authorizes/captures <code>orderId</code> on their backend after <code>onApprove</code>.
/// \param orderId A PayPal order id created by the merchant backend.
///
/// \param fundingSource Funding source the buyer selected.
///
/// \param options Per-session overrides (defaults to <code>.default</code>).
///
/// \param onApprove Called after the buyer approves.
///
/// \param onCancel Called when the buyer cancels.
///
/// \param onError Called with a <code>PayPalError</code> on failure.
///
+ (void)startWithOrderId:(NSString * _Nonnull)orderId fundingSource:(enum PayPalFundingSource)fundingSource options:(PayPalCheckoutSessionOptions * _Nonnull)options onApprove:(void (^ _Nonnull)(PayPalCheckoutResult * _Nonnull))onApprove onCancel:(void (^ _Nonnull)(PayPalCancelData * _Nonnull))onCancel onError:(void (^ _Nonnull)(NSError * _Nonnull))onError;
/// Objective-C entry point for a full PPCP checkout using a block-based order provider and delegate.
+ (void)startCheckoutWithFundingSource:(enum PayPalFundingSource)fundingSource options:(PayPalCheckoutSessionOptions * _Nonnull)options orderProvider:(id <PayPalOrderProviderObjC> _Nonnull)orderProvider delegate:(id <PayPalCheckoutDelegate> _Nonnull)delegate;
/// Objective-C entry point for approving a merchant-created order. Capture is merchant-side.
+ (void)startWithOrderId:(NSString * _Nonnull)orderId fundingSource:(enum PayPalFundingSource)fundingSource options:(PayPalCheckoutSessionOptions * _Nonnull)options delegate:(id <PayPalCheckoutDelegate> _Nonnull)delegate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// UIKit PayPal Credit button. Set <code>onTap</code> to start a Credit checkout; style via <code>appearance</code>.
/// Credit supports white/black/darkBlue colors; other values fall back to darkBlue.
SWIFT_CLASS("_TtC14SpreedlyPayPal30SpreedlyPayPalCreditButtonView")
@interface SpreedlyPayPalCreditButtonView : PayPalButtonBaseView
- (nonnull instancetype)initWithAppearance:(PayPalButtonAppearance * _Nonnull)appearance OBJC_DESIGNATED_INITIALIZER;
@end

/// UIKit PayPal Pay Later button. Set <code>onTap</code> to start a Pay Later checkout; style via <code>appearance</code>.
SWIFT_CLASS("_TtC14SpreedlyPayPal32SpreedlyPayPalPayLaterButtonView")
@interface SpreedlyPayPalPayLaterButtonView : PayPalButtonBaseView
- (nonnull instancetype)initWithAppearance:(PayPalButtonAppearance * _Nonnull)appearance OBJC_DESIGNATED_INITIALIZER;
@end

/// Shared UIKit host for the Venmo PPCP button. Mirrors tap/telemetry behavior of <code>PayPalButtonBaseView</code>.
SWIFT_CLASS("_TtC14SpreedlyPayPal19VenmoButtonBaseView")
@interface VenmoButtonBaseView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

/// UIKit Venmo button for PPCP. Set <code>onTap</code> to start a Venmo checkout; style via <code>appearance</code>.
SWIFT_CLASS("_TtC14SpreedlyPayPal23SpreedlyVenmoButtonView")
@interface SpreedlyVenmoButtonView : VenmoButtonBaseView
- (nonnull instancetype)initWithAppearance:(PayPalButtonAppearance * _Nonnull)appearance OBJC_DESIGNATED_INITIALIZER;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.3.2 effective-5.10 (swiftlang-6.3.2.1.108 clang-2100.1.1.101)
#ifndef SPREEDLYPAYPAL_SWIFT_H
#define SPREEDLYPAYPAL_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SpreedlyPayPal",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SpreedlyPayPal",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
SWIFT_ENUM_FWD_DECL(NSInteger, PayPalFundingSource)
/// Buyer-approval payload delivered when a PPCP order is approved in the web checkout.
SWIFT_CLASS("_TtC14SpreedlyPayPal17PayPalApproveData")
@interface PayPalApproveData : NSObject
/// PayPal order id approved by the buyer.
@property (nonatomic, readonly, copy) NSString * _Nonnull orderId;
/// PayPal payer id from the approval.
@property (nonatomic, readonly, copy) NSString * _Nonnull payerId;
/// Funding source used for this approval.
@property (nonatomic, readonly) enum PayPalFundingSource fundingSource;
- (nonnull instancetype)initWithOrderId:(NSString * _Nonnull)orderId payerId:(NSString * _Nonnull)payerId fundingSource:(enum PayPalFundingSource)fundingSource OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_ENUM_FWD_DECL(NSInteger, PayPalButtonColor)
SWIFT_ENUM_FWD_DECL(NSInteger, PayPalButtonEdges)
SWIFT_ENUM_FWD_DECL(NSInteger, PayPalButtonSize)
SWIFT_ENUM_FWD_DECL(NSInteger, PayPalButtonLabel)
SWIFT_ENUM_FWD_DECL(NSInteger, PayPalButtonKind)
@class NSNumber;
/// Appearance for Spreedly’s PPCP buttons, mapped onto the PayPal <code>PaymentButtons</code> design system.
SWIFT_CLASS("_TtC14SpreedlyPayPal22PayPalButtonAppearance")
@interface PayPalButtonAppearance : NSObject
/// PayPal requires at least 10pt for custom corner radius.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat minimumCustomCornerRadius;)
+ (CGFloat)minimumCustomCornerRadius SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) enum PayPalButtonColor color;
@property (nonatomic, readonly) enum PayPalButtonEdges edges;
@property (nonatomic, readonly) enum PayPalButtonSize size;
@property (nonatomic, readonly) CGFloat customCornerRadius;
@property (nonatomic, readonly) enum PayPalButtonLabel label;
- (nonnull instancetype)initWithColor:(enum PayPalButtonColor)color edges:(enum PayPalButtonEdges)edges size:(enum PayPalButtonSize)size customCornerRadius:(CGFloat)customCornerRadius label:(enum PayPalButtonLabel)label OBJC_DESIGNATED_INITIALIZER;
/// Default gold PayPal button with soft edges, collapsed size.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) PayPalButtonAppearance * _Nonnull default_;)
+ (PayPalButtonAppearance * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
/// Returns <code>color</code> when valid for <code>kind</code>, otherwise a sensible default for that button type.
+ (enum PayPalButtonColor)resolvedColor:(enum PayPalButtonColor)color for:(enum PayPalButtonKind)kind SWIFT_WARN_UNUSED_RESULT;
/// Colors supported by the given button type (as <code>NSNumber</code> wrapping <code>PayPalButtonColor</code> raw values).
+ (NSArray<NSNumber *> * _Nonnull)allowedColorsFor:(enum PayPalButtonKind)kind SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSCoder;
/// Shared UIKit host for the PPCP buttons. Owns the wrapped <code>PaymentButton</code>, pins it edge-to-edge,
/// forwards taps to <code>onTap</code>, and rebuilds when <code>appearance</code> changes. Subclasses supply the concrete
/// button via <code>makeButton(appearance:)</code>.
SWIFT_CLASS("_TtC14SpreedlyPayPal20PayPalButtonBaseView")
@interface PayPalButtonBaseView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

/// Button color. Not every color is valid for every button (Credit supports white/black/darkBlue);
/// unsupported values fall back to the button’s default.
typedef SWIFT_ENUM(NSInteger, PayPalButtonColor, open) {
  PayPalButtonColorGold = 0,
  PayPalButtonColorWhite = 1,
  PayPalButtonColorBlack = 2,
  PayPalButtonColorSilver = 3,
  PayPalButtonColorBlue = 4,
  PayPalButtonColorDarkBlue = 5,
};

/// Corner treatment for a PayPal button.
typedef SWIFT_ENUM(NSInteger, PayPalButtonEdges, open) {
/// Rectangle — 0pt corner radius (<code>PaymentButtonEdges.hardEdges</code>).
  PayPalButtonEdgesHard = 0,
/// Rounded — 4pt corner radius (<code>PaymentButtonEdges.softEdges</code>).
  PayPalButtonEdgesSoft = 1,
/// Pill — half the button height (<code>PaymentButtonEdges.rounded</code>).
  PayPalButtonEdgesRounded = 2,
/// Custom corner radius — use <code>PayPalButtonAppearance.customCornerRadius</code> (minimum 10pt).
  PayPalButtonEdgesCustom = 3,
};

/// Identifies which PPCP button type is being styled (for color validation).
typedef SWIFT_ENUM_NAMED(NSInteger, PayPalButtonKind, "PayPalButtonKind", open) {
  PayPalButtonKindPayPal = 0,
  PayPalButtonKindPayLater = 1,
  PayPalButtonKindCredit = 2,
  PayPalButtonKindVenmo = 3,
};

/// Optional label on the generic PayPal button (not Pay Later or Credit).
typedef SWIFT_ENUM(NSInteger, PayPalButtonLabel, open) {
  PayPalButtonLabelNone = 0,
  PayPalButtonLabelCheckout = 1,
  PayPalButtonLabelBuyNow = 2,
  PayPalButtonLabelPayWith = 3,
};

/// Size category for a PayPal button.
typedef SWIFT_ENUM(NSInteger, PayPalButtonSize, open) {
  PayPalButtonSizeMini = 0,
  PayPalButtonSizeCollapsed = 1,
  PayPalButtonSizeExpanded = 2,
  PayPalButtonSizeFull = 3,
};

/// Payload delivered when the buyer cancels the PPCP web checkout.
SWIFT_CLASS("_TtC14SpreedlyPayPal16PayPalCancelData")
@interface PayPalCancelData : NSObject
/// Order id that was in flight when the buyer canceled, if known.
@property (nonatomic, readonly, copy) NSString * _Nullable orderId;
- (nonnull instancetype)initWithOrderId:(NSString * _Nullable)orderId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PayPalCheckoutResult;
/// Delegate for PPCP checkout outcomes. Provides an Objective-C-friendly callback surface
/// equivalent to the Swift closure API on <code>SpreedlyPayPalCheckout</code>.
SWIFT_PROTOCOL("_TtP14SpreedlyPayPal22PayPalCheckoutDelegate_")
@protocol PayPalCheckoutDelegate
/// Called when the buyer approves the order and the merchant backend finishes capture.
- (void)payPalCheckoutDidApprove:(PayPalCheckoutResult * _Nonnull)result;
/// Called when the buyer cancels the checkout.
- (void)payPalCheckoutDidCancel:(PayPalCancelData * _Nonnull)data;
/// Called when the checkout fails. <code>error</code> is a <code>SpreedlyCore.PayPalError</code>.
- (void)payPalCheckoutDidFailWithError:(NSError * _Nonnull)error;
@end

/// Errors thrown while initializing PPCP checkout.
typedef SWIFT_ENUM(NSInteger, PayPalCheckoutInitializationErrorCode, open) {
  PayPalCheckoutInitializationErrorCodeMissingClientId = 0,
  PayPalCheckoutInitializationErrorCodeInvalidReturnURL = 1,
  PayPalCheckoutInitializationErrorCodeAlreadyInitialized = 2,
  PayPalCheckoutInitializationErrorCodeDeviceBlocked = 3,
};

/// Terminal result of a completed PPCP checkout (order approved and captured by the merchant backend).
SWIFT_CLASS("_TtC14SpreedlyPayPal20PayPalCheckoutResult")
@interface PayPalCheckoutResult : NSObject
/// Approved PayPal order id.
@property (nonatomic, readonly, copy) NSString * _Nonnull orderId;
/// PayPal payer id from the approval.
@property (nonatomic, readonly, copy) NSString * _Nonnull payerId;
/// Funding source used for the order.
@property (nonatomic, readonly) enum PayPalFundingSource fundingSource;
/// Transaction state after capture (typically “pending” until the backend settles).
@property (nonatomic, readonly, copy) NSString * _Nonnull state;
- (nonnull instancetype)initWithOrderId:(NSString * _Nonnull)orderId payerId:(NSString * _Nonnull)payerId fundingSource:(enum PayPalFundingSource)fundingSource state:(NSString * _Nonnull)state OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_ENUM_FWD_DECL(NSInteger, PayPalPresentationMode)
/// Per-checkout options that override module defaults for a single PPCP session.
SWIFT_CLASS("_TtC14SpreedlyPayPal28PayPalCheckoutSessionOptions")
@interface PayPalCheckoutSessionOptions : NSObject
/// When <code>true</code>, the order is expected to be captured/authorized by the merchant backend after approval.
/// Purely informational for the SDK; the actual capture happens in the merchant’s <code>captureOrder</code>.
@property (nonatomic, readonly) BOOL commit;
/// Preferred presentation for the web checkout (maps to the underlying web authentication experience).
@property (nonatomic, readonly) enum PayPalPresentationMode presentationMode;
/// Optional Spreedly transaction token to correlate this checkout with a pending purchase.
@property (nonatomic, readonly, copy) NSString * _Nullable transactionToken;
- (nonnull instancetype)initWithCommit:(BOOL)commit presentationMode:(enum PayPalPresentationMode)presentationMode transactionToken:(NSString * _Nullable)transactionToken OBJC_DESIGNATED_INITIALIZER;
/// Default options: commit enabled, automatic presentation, no transaction token.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) PayPalCheckoutSessionOptions * _Nonnull default_;)
+ (PayPalCheckoutSessionOptions * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Objective-C-friendly, block-based counterpart to <code>PayPalOrderProvider</code>.
/// Implementations must invoke exactly one branch of each completion block: either an id/success
/// or an error. <code>SpreedlyPayPalCheckout</code> wraps a conforming object in an internal adapter.
SWIFT_PROTOCOL("_TtP14SpreedlyPayPal23PayPalOrderProviderObjC_")
@protocol PayPalOrderProviderObjC
/// Creates an order and returns its id via <code>completion(orderId, error)</code>.
- (void)createOrderWithFundingSource:(enum PayPalFundingSource)fundingSource completion:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
/// Captures the approved order and reports completion via <code>completion(error)</code>.
- (void)captureOrderWithOrderId:(NSString * _Nonnull)orderId completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
@end

/// UIKit PayPal button. Set <code>onTap</code> to start a checkout; style via <code>appearance</code>.
SWIFT_CLASS("_TtC14SpreedlyPayPal24SpreedlyPayPalButtonView")
@interface SpreedlyPayPalButtonView : PayPalButtonBaseView
- (nonnull instancetype)initWithAppearance:(PayPalButtonAppearance * _Nonnull)appearance OBJC_DESIGNATED_INITIALIZER;
@end

@class PayPalCheckoutConfig;
@class PayPalEligibilityResult;
/// PPCP checkout entry point (native PayPal buttons + web checkout).
/// Lifecycle: call <code>initialize(config:)</code> once, then drive a checkout with <code>startCheckout(...)</code>
/// (SDK orchestrates create → approve → capture) or <code>start(orderId:...)</code> (merchant pre-created the
/// order; the SDK only runs the PayPal approval). Results are delivered two ways: a cross-module
/// <code>PaymentResult</code> via <code>Spreedly.shared().subscribeToPaymentResults</code>, and the per-call closures
/// (Swift) or <code>PayPalCheckoutDelegate</code> (Objective-C).
SWIFT_CLASS("_TtC14SpreedlyPayPal22SpreedlyPayPalCheckout")
@interface SpreedlyPayPalCheckout : NSObject
/// Whether <code>initialize(config:)</code> completed successfully.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isInitialized;)
+ (BOOL)isInitialized SWIFT_WARN_UNUSED_RESULT;
/// Configures the PayPal SDK for PPCP. Call once before presenting buttons or sessions.
/// \param config Merchant-supplied Client ID, environment, and return URL.
///
+ (BOOL)initializeWithConfig:(PayPalCheckoutConfig * _Nonnull)config error:(NSError * _Nullable * _Nullable)error;
/// Returns client-side eligibility for PPCP funding sources using PayPal’s published country tables.
/// PayPal iOS SDK has no native eligibility API; this is a Spreedly wrapper for button gating.
+ (void)findEligibleMethodsWithCurrency:(NSString * _Nonnull)currency locale:(NSString * _Nonnull)locale country:(NSString * _Nonnull)country amount:(NSString * _Nonnull)amount completionHandler:(void (^ _Nonnull)(PayPalEligibilityResult * _Nullable, NSError * _Nullable))completionHandler;
/// Objective-C wrapper for <code>findEligibleMethods</code>.
+ (void)findEligibleMethodsWithCurrency:(NSString * _Nonnull)currency locale:(NSString * _Nonnull)locale country:(NSString * _Nonnull)country amount:(NSString * _Nonnull)amount completion:(void (^ _Nonnull)(PayPalEligibilityResult * _Nullable, NSError * _Nullable))completion;
/// Runs PayPal approval for an order the merchant already created. The SDK does not capture;
/// the merchant authorizes/captures <code>orderId</code> on their backend after <code>onApprove</code>.
/// \param orderId A PayPal order id created by the merchant backend.
///
/// \param fundingSource Funding source the buyer selected.
///
/// \param options Per-session overrides (defaults to <code>.default</code>).
///
/// \param onApprove Called after the buyer approves.
///
/// \param onCancel Called when the buyer cancels.
///
/// \param onError Called with a <code>PayPalError</code> on failure.
///
+ (void)startWithOrderId:(NSString * _Nonnull)orderId fundingSource:(enum PayPalFundingSource)fundingSource options:(PayPalCheckoutSessionOptions * _Nonnull)options onApprove:(void (^ _Nonnull)(PayPalCheckoutResult * _Nonnull))onApprove onCancel:(void (^ _Nonnull)(PayPalCancelData * _Nonnull))onCancel onError:(void (^ _Nonnull)(NSError * _Nonnull))onError;
/// Objective-C entry point for a full PPCP checkout using a block-based order provider and delegate.
+ (void)startCheckoutWithFundingSource:(enum PayPalFundingSource)fundingSource options:(PayPalCheckoutSessionOptions * _Nonnull)options orderProvider:(id <PayPalOrderProviderObjC> _Nonnull)orderProvider delegate:(id <PayPalCheckoutDelegate> _Nonnull)delegate;
/// Objective-C entry point for approving a merchant-created order. Capture is merchant-side.
+ (void)startWithOrderId:(NSString * _Nonnull)orderId fundingSource:(enum PayPalFundingSource)fundingSource options:(PayPalCheckoutSessionOptions * _Nonnull)options delegate:(id <PayPalCheckoutDelegate> _Nonnull)delegate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// UIKit PayPal Credit button. Set <code>onTap</code> to start a Credit checkout; style via <code>appearance</code>.
/// Credit supports white/black/darkBlue colors; other values fall back to darkBlue.
SWIFT_CLASS("_TtC14SpreedlyPayPal30SpreedlyPayPalCreditButtonView")
@interface SpreedlyPayPalCreditButtonView : PayPalButtonBaseView
- (nonnull instancetype)initWithAppearance:(PayPalButtonAppearance * _Nonnull)appearance OBJC_DESIGNATED_INITIALIZER;
@end

/// UIKit PayPal Pay Later button. Set <code>onTap</code> to start a Pay Later checkout; style via <code>appearance</code>.
SWIFT_CLASS("_TtC14SpreedlyPayPal32SpreedlyPayPalPayLaterButtonView")
@interface SpreedlyPayPalPayLaterButtonView : PayPalButtonBaseView
- (nonnull instancetype)initWithAppearance:(PayPalButtonAppearance * _Nonnull)appearance OBJC_DESIGNATED_INITIALIZER;
@end

/// Shared UIKit host for the Venmo PPCP button. Mirrors tap/telemetry behavior of <code>PayPalButtonBaseView</code>.
SWIFT_CLASS("_TtC14SpreedlyPayPal19VenmoButtonBaseView")
@interface VenmoButtonBaseView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

/// UIKit Venmo button for PPCP. Set <code>onTap</code> to start a Venmo checkout; style via <code>appearance</code>.
SWIFT_CLASS("_TtC14SpreedlyPayPal23SpreedlyVenmoButtonView")
@interface SpreedlyVenmoButtonView : VenmoButtonBaseView
- (nonnull instancetype)initWithAppearance:(PayPalButtonAppearance * _Nonnull)appearance OBJC_DESIGNATED_INITIALIZER;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
