#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef SPREEDLYSTRIPEAPM_SWIFT_H
#define SPREEDLYSTRIPEAPM_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SpreedlyStripeAPM",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSURL;
@class StripeAPMConfig;
@class UIViewController;
@class StripeAPMAppearanceConfig;
/// Presents Stripe’s PaymentSheet, then polls Spreedly for the transaction result.
/// The final <code>PaymentResult</code> is published through <code>Spreedly.shared().publishPaymentResult()</code>.
SWIFT_CLASS("_TtC17SpreedlyStripeAPM25SpreedlyStripeAPMCheckout")
@interface SpreedlyStripeAPMCheckout : NSObject
/// Handles the return URL after a Stripe redirect (e.g. iDEAL bank auth).
/// Call from your scene delegate or <code>onOpenURL</code> handler. Returns <code>true</code> if the URL was handled.
+ (BOOL)handleStripeReturnURL:(NSURL * _Nonnull)url SWIFT_WARN_UNUSED_RESULT;
/// Presents the Stripe APM payment sheet using the topmost view controller.
/// \param config Stripe APM configuration with credentials and transaction token.
///
+ (void)presentWithConfig:(StripeAPMConfig * _Nonnull)config;
/// Configures and presents the Stripe PaymentSheet from the given view controller.
+ (void)presentWithConfig:(StripeAPMConfig * _Nonnull)config from:(UIViewController * _Nonnull)viewController;
/// Presents the Stripe APM payment sheet using the topmost view controller with optional appearance theming.
/// \param config Stripe APM configuration with credentials and transaction token.
///
/// \param appearance Optional theming overrides for the PaymentSheet. Pass <code>nil</code> to use Stripe defaults.
///
+ (void)presentWithConfig:(StripeAPMConfig * _Nonnull)config appearance:(StripeAPMAppearanceConfig * _Nullable)appearance;
/// Configures and presents the Stripe PaymentSheet from the given view controller, with optional appearance theming.
/// \param config Stripe APM configuration with credentials and transaction token.
///
/// \param appearance Optional theming overrides for the PaymentSheet. Pass <code>nil</code> to use Stripe defaults.
///
/// \param viewController The view controller used to present the sheet.
///
+ (void)presentWithConfig:(StripeAPMConfig * _Nonnull)config appearance:(StripeAPMAppearanceConfig * _Nullable)appearance from:(UIViewController * _Nonnull)viewController;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIColor;
/// Color palette mirroring <code>PaymentSheet.Appearance.Colors</code>.
SWIFT_CLASS("_TtC17SpreedlyStripeAPM25StripeAPMAppearanceColors")
@interface StripeAPMAppearanceColors : NSObject
/// Primary brand color. Stripe default: <code>.systemBlue</code>.
@property (nonatomic, strong) UIColor * _Nonnull primary;
/// Sheet background. Stripe default: <code>.systemBackground</code>.
@property (nonatomic, strong) UIColor * _Nonnull background;
/// Background of inputs, tabs, and other components.
@property (nonatomic, strong) UIColor * _Nonnull componentBackground;
/// Border color for inputs, tabs, and other components.
@property (nonatomic, strong) UIColor * _Nonnull componentBorder;
/// Border color used for selected buttons and tabs.
/// <code>nil</code> falls back to <code>primary</code>.
@property (nonatomic, strong) UIColor * _Nullable selectedComponentBorder;
/// Divider color used inside inputs and tabs.
@property (nonatomic, strong) UIColor * _Nonnull componentDivider;
/// Default text color appearing over the background.
@property (nonatomic, strong) UIColor * _Nonnull text;
/// Text color for secondary text (e.g. input labels).
@property (nonatomic, strong) UIColor * _Nonnull textSecondary;
/// Text color used over <code>componentBackground</code>.
@property (nonatomic, strong) UIColor * _Nonnull componentText;
/// Input placeholder text color.
@property (nonatomic, strong) UIColor * _Nonnull componentPlaceholderText;
/// Icon color used in the sheet (e.g. close, back).
@property (nonatomic, strong) UIColor * _Nonnull icon;
/// Color for errors and destructive actions.
@property (nonatomic, strong) UIColor * _Nonnull danger;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;
@class StripeAPMAppearancePrimaryButton;
@class StripeAPMAppearanceShadow;
@class StripeAPMAppearanceFont;
/// Appearance customization for the Stripe APM PaymentSheet.
/// Mirrors the publicly stable, non-experimental subset of <code>PaymentSheet.Appearance</code> from
/// the Stripe iOS SDK. Construct an instance, set only the values you want to override,
/// and pass it to one of the <code>SpreedlyStripeAPMCheckout.present(...)</code> overloads.
/// Any property left at its default is forwarded as Stripe’s own default (no override).
/// <h3>Example</h3>
/// \code
/// let appearance = StripeAPMAppearanceConfig()
/// appearance.cornerRadius = 8
/// appearance.colors.primary = .systemPurple
/// appearance.primaryButton.backgroundColor = .systemPurple
/// appearance.primaryButton.height = 52
///
/// SpreedlyStripeAPMCheckout.present(config: config, appearance: appearance)
///
/// \endcode
SWIFT_CLASS("_TtC17SpreedlyStripeAPM25StripeAPMAppearanceConfig")
@interface StripeAPMAppearanceConfig : NSObject
/// Corner radius used for buttons, inputs, and tabs in the PaymentSheet.
/// Stripe default: <code>6.0</code>. Set <code>nil</code> to keep Stripe’s adaptive default.
@property (nonatomic, strong) NSNumber * _Nullable cornerRadius;
/// Border width used for inputs and tabs. Stripe default: <code>1.0</code>.
@property (nonatomic) CGFloat borderWidth;
/// Border width used for selected buttons and tabs.
/// Stripe default: <code>borderWidth * 1.5</code>. Set <code>nil</code> to keep Stripe’s default.
@property (nonatomic, strong) NSNumber * _Nullable selectedBorderWidth;
/// Color palette for the PaymentSheet.
@property (nonatomic, strong) StripeAPMAppearanceColors * _Nonnull colors;
/// Primary button (e.g. “Pay”) appearance.
@property (nonatomic, strong) StripeAPMAppearancePrimaryButton * _Nonnull primaryButton;
/// Shadow applied to inputs and tabs.
@property (nonatomic, strong) StripeAPMAppearanceShadow * _Nonnull shadow;
/// Font configuration. The font’s size and weight are ignored — Stripe derives all
/// sizes from the family and <code>sizeScaleFactor</code>.
@property (nonatomic, strong) StripeAPMAppearanceFont * _Nonnull font;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIFont;
/// Font configuration mirroring the publicly stable surface of <code>PaymentSheet.Appearance.Font</code>.
SWIFT_CLASS("_TtC17SpreedlyStripeAPM23StripeAPMAppearanceFont")
@interface StripeAPMAppearanceFont : NSObject
/// Base font family. The size and weight are ignored by Stripe — only the family is used.
/// Default: <code>UIFont.systemFont(ofSize: UIFont.labelFontSize)</code>.
@property (nonatomic, strong) UIFont * _Nonnull base;
/// Scale factor applied to all font sizes. Must be > 0. Stripe default: <code>1.0</code>.
@property (nonatomic) CGFloat sizeScaleFactor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Primary-button appearance mirroring <code>PaymentSheet.Appearance.PrimaryButton</code>.
SWIFT_CLASS("_TtC17SpreedlyStripeAPM32StripeAPMAppearancePrimaryButton")
@interface StripeAPMAppearancePrimaryButton : NSObject
/// Background color. <code>nil</code> falls back to <code>colors.primary</code>.
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
/// Text color. <code>nil</code> lets Stripe pick black/white based on contrast.
@property (nonatomic, strong) UIColor * _Nullable textColor;
/// Background color in disabled state. <code>nil</code> falls back to <code>backgroundColor</code>.
@property (nonatomic, strong) UIColor * _Nullable disabledBackgroundColor;
/// Text color in disabled state. <code>nil</code> falls back to <code>textColor</code> at 0.6 alpha.
@property (nonatomic, strong) UIColor * _Nullable disabledTextColor;
/// Background color in success state. Stripe default: <code>.systemGreen</code>.
@property (nonatomic, strong) UIColor * _Nonnull successBackgroundColor;
/// Text color in success state. <code>nil</code> falls back to <code>textColor</code>.
@property (nonatomic, strong) UIColor * _Nullable successTextColor;
/// Corner radius override. <code>nil</code> inherits <code>Appearance.cornerRadius</code>.
@property (nonatomic, strong) NSNumber * _Nullable cornerRadius;
/// Border color. Stripe default: <code>.quaternaryLabel</code>.
@property (nonatomic, strong) UIColor * _Nonnull borderColor;
/// Border width. Stripe default: <code>1.0</code>.
@property (nonatomic) CGFloat borderWidth;
/// Font override. <code>nil</code> inherits <code>Appearance.font.base</code>.
@property (nonatomic, strong) UIFont * _Nullable font;
/// Shadow override. <code>nil</code> inherits <code>Appearance.shadow</code>.
@property (nonatomic, strong) StripeAPMAppearanceShadow * _Nullable shadow;
/// Button height. Stripe default: <code>44</code>.
@property (nonatomic) CGFloat height;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Shadow configuration mirroring <code>PaymentSheet.Appearance.Shadow</code>.
SWIFT_CLASS("_TtC17SpreedlyStripeAPM25StripeAPMAppearanceShadow")
@interface StripeAPMAppearanceShadow : NSObject
/// Shadow color. Stripe default: <code>.black</code>.
@property (nonatomic, strong) UIColor * _Nonnull color;
/// Shadow opacity. Stripe default: <code>0.05</code>.
@property (nonatomic) CGFloat opacity;
/// Shadow offset. Stripe default: <code>(0, 2)</code>.
@property (nonatomic) CGSize offset;
/// Shadow blur radius. Stripe default: <code>4</code>.
@property (nonatomic) CGFloat radius;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Convenience: a fully-disabled shadow (Stripe’s <code>Shadow.disabled</code>).
+ (StripeAPMAppearanceShadow * _Nonnull)disabled SWIFT_WARN_UNUSED_RESULT;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
