#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.2 effective-5.10 (swiftlang-6.3.2.1.108 clang-2100.1.1.101)
#ifndef SPREEDLYCLICKTOPAY_SWIFT_H
#define SPREEDLYCLICKTOPAY_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SpreedlyClickToPay",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SpreedlyClickToPay",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// Card list layout for MC <code>src-card-list</code> (iframe <code>displayCards.cardSelectionType</code>).
typedef SWIFT_ENUM(NSInteger, ClickToPayCardSelectionType, open) {
  ClickToPayCardSelectionTypeRadioButton = 0,
  ClickToPayCardSelectionTypeGridView = 1,
};

@class ClickToPayInitConfig;
@class NSString;
@class ClickToPayCustomer;
@class ClickToPayDisplayCardsConfig;
@class ClickToPayOtpConfig;
@class ClickToPayTokenizeBilling;
/// Sole merchant configuration for Click to Pay checkout (Android <code>ClickToPayCheckoutConfig</code> parity).
SWIFT_CLASS("_TtC18SpreedlyClickToPay24ClickToPayCheckoutConfig")
@interface ClickToPayCheckoutConfig : NSObject
@property (nonatomic, strong) ClickToPayInitConfig * _Nonnull initConfig;
- (ClickToPayInitConfig * _Nonnull)initConfig SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) NSString * _Nonnull srcDpaId;
@property (nonatomic, copy) NSString * _Nonnull locale;
@property (nonatomic) BOOL isSandbox;
@property (nonatomic, copy) NSString * _Nonnull dpaPresentationName;
@property (nonatomic, copy) NSString * _Nonnull dpaName;
@property (nonatomic, strong) ClickToPayCustomer * _Nullable customer;
@property (nonatomic) BOOL doLookup;
@property (nonatomic, strong) ClickToPayDisplayCardsConfig * _Nonnull displayCards;
@property (nonatomic, strong) ClickToPayOtpConfig * _Nonnull otp;
@property (nonatomic, strong) ClickToPayTokenizeBilling * _Nullable tokenizeBilling;
/// Optional payment-method metadata on auto-tokenize (iframe <code>c2pCheckout</code> <code>metadata</code> parity).
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable tokenizeMetadata;
/// When <code>true</code>, sets <code>click_to_pay.test</code> on tokenize. When <code>false</code> (default), the test flag follows <code>isSandbox</code>.
@property (nonatomic) BOOL isTest;
/// When <code>true</code>, merchant UI owns saved-card selection; SDK sheet hides MC card list chrome.
@property (nonatomic) BOOL merchantHostedCardList;
/// Objective-C entry point — configure via properties after <code>[[ClickToPayCheckoutConfig alloc] init]</code>.
- (nonnull instancetype)init;
@end

@protocol ClickToPayDelegate;
@class NSCoder;
@class NSBundle;
/// UIKit host for headless Click to Pay — embeds MC WebView via <code>ClickToPayCheckoutController</code>.
SWIFT_CLASS("_TtC18SpreedlyClickToPay32ClickToPayCheckoutViewController")
@interface ClickToPayCheckoutViewController : UIViewController
@property (nonatomic, weak) id <ClickToPayDelegate> _Nullable clickToPayDelegate;
- (nonnull instancetype)initWithConfig:(ClickToPayCheckoutConfig * _Nonnull)config OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
/// Presents full-screen checkout using the singleton presenter (preferred for ObjC).
+ (void)presentWithConfig:(ClickToPayCheckoutConfig * _Nonnull)config from:(UIViewController * _Nonnull)viewController;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, ClickToPayMainLookupMethod)
/// Identity for MC <code>idLookup</code> (email and/or phone).
SWIFT_CLASS("_TtC18SpreedlyClickToPay18ClickToPayCustomer")
@interface ClickToPayCustomer : NSObject
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable phoneNumber;
@property (nonatomic, copy) NSString * _Nullable countryCode;
/// When both email and phone are set, which field drives <code>idLookup</code> (iframe default: email).
@property (nonatomic) enum ClickToPayMainLookupMethod mainLookupMethod;
- (nonnull instancetype)initWithEmail:(NSString * _Nullable)email phoneNumber:(NSString * _Nullable)phoneNumber countryCode:(NSString * _Nullable)countryCode mainLookupMethod:(enum ClickToPayMainLookupMethod)mainLookupMethod OBJC_DESIGNATED_INITIALIZER;
- (BOOL)hasEmail SWIFT_WARN_UNUSED_RESULT;
/// Phone lookup requires both number and country code (Android / iframe parity).
- (BOOL)hasPhoneLookup SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isValidForLookup SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_ENUM_FWD_DECL(NSInteger, ClickToPayEventKind)
/// Receives Click to Pay flow events from UIKit / Objective-C integrations.
SWIFT_PROTOCOL("_TtP18SpreedlyClickToPay18ClickToPayDelegate_")
@protocol ClickToPayDelegate
@optional
/// <code>checkout</code> is non-nil for embedded <code>ClickToPayCheckoutViewController</code>; nil for singleton sheet present.
- (void)clickToPay:(ClickToPayCheckoutViewController * _Nullable)checkout didReceiveEvent:(enum ClickToPayEventKind)event userInfo:(NSDictionary<NSString *, id> * _Nullable)userInfo;
@end

/// <code>src-card-list</code> customization (iframe <code>options.displayCards</code>).
SWIFT_CLASS("_TtC18SpreedlyClickToPay28ClickToPayDisplayCardsConfig")
@interface ClickToPayDisplayCardsConfig : NSObject
@property (nonatomic) BOOL displaySignOut;
@property (nonatomic) BOOL displayAddCard;
@property (nonatomic) BOOL displayPreferredCard;
@property (nonatomic) enum ClickToPayCardSelectionType cardSelectionType;
- (nonnull instancetype)initWithDisplaySignOut:(BOOL)displaySignOut displayAddCard:(BOOL)displayAddCard displayPreferredCard:(BOOL)displayPreferredCard cardSelectionType:(enum ClickToPayCardSelectionType)cardSelectionType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ClickToPayErrorCode, open) {
  ClickToPayErrorCodeC2pInit = 0,
  ClickToPayErrorCodeC2pLookup = 1,
  ClickToPayErrorCodeC2pOtp = 2,
  ClickToPayErrorCodeC2pCheckout = 3,
  ClickToPayErrorCodeC2pTokenize = 4,
  ClickToPayErrorCodeNetworkTimeout = 5,
  ClickToPayErrorCodeUnknown = 6,
};

/// Objective-C event kinds — iframe <code>Spreedly.on(...)</code> parity.
typedef SWIFT_ENUM(NSInteger, ClickToPayEventKind, open) {
  ClickToPayEventKindCheckoutStarted = 0,
  ClickToPayEventKindInitialized = 1,
  ClickToPayEventKindNewUser = 2,
  ClickToPayEventKindExistingUser = 3,
  ClickToPayEventKindVerifiedUser = 4,
  ClickToPayEventKindOtpInitiated = 5,
  ClickToPayEventKindOtpChannelSelectionRequired = 6,
  ClickToPayEventKindOtpResponse = 7,
  ClickToPayEventKindOtpResend = 8,
  ClickToPayEventKindOtpNotYou = 9,
  ClickToPayEventKindDisplayCardsReady = 10,
  ClickToPayEventKindAddNewCard = 11,
  ClickToPayEventKindCheckoutCancelled = 12,
  ClickToPayEventKindCheckoutDifferentPaymentMethod = 13,
  ClickToPayEventKindCheckoutError = 14,
  ClickToPayEventKindCheckoutWindowOpened = 15,
  ClickToPayEventKindCheckoutWindowClosed = 16,
  ClickToPayEventKindSessionDeleted = 17,
  ClickToPayEventKindCheckoutComplete = 18,
  ClickToPayEventKindPaymentMethodTokenized = 19,
  ClickToPayEventKindError = 20,
  ClickToPayEventKindValidationErrors = 21,
};

SWIFT_CLASS("_TtC18SpreedlyClickToPay20ClickToPayFieldError")
@interface ClickToPayFieldError : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull key;
@property (nonatomic, readonly, copy) NSString * _Nonnull attribute;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
/// iframe <code>errors[]</code> parity — <code>attribute</code> matches web iframe <code>c2pError</code> names; <code>key</code> is <code>errors.<attribute></code>.
- (nonnull instancetype)initWithIframeAttribute:(NSString * _Nonnull)iframeAttribute message:(NSString * _Nonnull)message OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC18SpreedlyClickToPay20ClickToPayInitConfig")
@interface ClickToPayInitConfig : NSObject
@property (nonatomic) double transactionAmount;
@property (nonatomic, copy) NSString * _Nonnull transactionCurrencyCode;
@property (nonatomic, copy) NSString * _Nonnull dynamicDataType;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull cardBrands;
- (nonnull instancetype)initWithTransactionAmount:(double)transactionAmount transactionCurrencyCode:(NSString * _Nonnull)transactionCurrencyCode dynamicDataType:(NSString * _Nonnull)dynamicDataType cardBrands:(NSArray<NSString *> * _Nonnull)cardBrands OBJC_DESIGNATED_INITIALIZER;
/// Objective-C: <code>initWithAmountCents:transactionCurrencyCode:</code> (Swift <code>amountCents</code> convenience).
- (nonnull instancetype)initWithAmountCents:(NSInteger)amountCents transactionCurrencyCode:(NSString * _Nonnull)transactionCurrencyCode;
- (nonnull instancetype)initWithAmountCents:(NSInteger)amountCents transactionCurrencyCode:(NSString * _Nonnull)transactionCurrencyCode dynamicDataType:(NSString * _Nonnull)dynamicDataType cardBrands:(NSArray<NSString *> * _Nonnull)cardBrands;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Primary identity channel for MC <code>idLookup</code> (iframe <code>customer.mainLookupMethod</code>).
typedef SWIFT_ENUM(NSInteger, ClickToPayMainLookupMethod, open) {
  ClickToPayMainLookupMethodEmail = 0,
  ClickToPayMainLookupMethodPhoneNumber = 1,
};

/// Masked card from MC <code>getCards</code> / <code>validate</code>.
SWIFT_CLASS("_TtC18SpreedlyClickToPay20ClickToPayMaskedCard")
@interface ClickToPayMaskedCard : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull srcDigitalCardId;
@property (nonatomic, readonly, copy) NSString * _Nullable panLastFour;
@property (nonatomic, readonly, copy) NSString * _Nullable cardBrand;
- (nonnull instancetype)initWithSrcDigitalCardId:(NSString * _Nonnull)srcDigitalCardId panLastFour:(NSString * _Nullable)panLastFour cardBrand:(NSString * _Nullable)cardBrand OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Native SPL card payload for MC <code>encryptCard</code> → <code>checkoutWithNewCard</code> (Android parity).
SWIFT_CLASS("_TtC18SpreedlyClickToPay23ClickToPayNewCardFields")
@interface ClickToPayNewCardFields : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull primaryAccountNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull panExpirationMonth;
@property (nonatomic, readonly, copy) NSString * _Nonnull panExpirationYearTwoDigit;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardSecurityCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardholderFirstName;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardholderLastName;
- (nonnull instancetype)initWithPrimaryAccountNumber:(NSString * _Nonnull)primaryAccountNumber panExpirationMonth:(NSString * _Nonnull)panExpirationMonth panExpirationYearTwoDigit:(NSString * _Nonnull)panExpirationYearTwoDigit cardSecurityCode:(NSString * _Nonnull)cardSecurityCode cardholderFirstName:(NSString * _Nonnull)cardholderFirstName cardholderLastName:(NSString * _Nonnull)cardholderLastName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// iframe <code>otpChannelSelectionEl</code> parity.
typedef SWIFT_ENUM(NSInteger, ClickToPayOtpChannelSelection, open) {
  ClickToPayOtpChannelSelectionInline = 0,
  ClickToPayOtpChannelSelectionExternal = 1,
};

SWIFT_ENUM_FWD_DECL(NSInteger, ClickToPayOtpPresentation)
/// OTP UI customization (iframe <code>options.otp</code>).
SWIFT_CLASS("_TtC18SpreedlyClickToPay19ClickToPayOtpConfig")
@interface ClickToPayOtpConfig : NSObject
@property (nonatomic) BOOL rememberMe;
@property (nonatomic) enum ClickToPayOtpPresentation presentation;
@property (nonatomic) enum ClickToPayOtpChannelSelection channelSelection;
@property (nonatomic, copy) NSString * _Nullable requestedValidationChannelId;
- (nonnull instancetype)initWithRememberMe:(BOOL)rememberMe presentation:(enum ClickToPayOtpPresentation)presentation channelSelection:(enum ClickToPayOtpChannelSelection)channelSelection requestedValidationChannelId:(NSString * _Nullable)requestedValidationChannelId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// OTP presentation mode for MC <code>src-otp-input</code> (iframe <code>options.otp.type</code>).
typedef SWIFT_ENUM(NSInteger, ClickToPayOtpPresentation, open) {
  ClickToPayOtpPresentationOverlay = 0,
  ClickToPayOtpPresentationNone = 1,
};

SWIFT_CLASS("_TtC18SpreedlyClickToPay25ClickToPayTokenizeBilling")
@interface ClickToPayTokenizeBilling : NSObject
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable fullName;
@property (nonatomic, copy) NSString * _Nullable month;
@property (nonatomic, copy) NSString * _Nullable year;
@property (nonatomic, copy) NSString * _Nullable addressLine1;
@property (nonatomic, copy) NSString * _Nullable addressLine2;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable zip;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable phoneNumber;
@property (nonatomic, copy) NSString * _Nullable company;
@property (nonatomic, copy) NSString * _Nullable shippingAddressLine1;
@property (nonatomic, copy) NSString * _Nullable shippingAddressLine2;
@property (nonatomic, copy) NSString * _Nullable shippingCity;
@property (nonatomic, copy) NSString * _Nullable shippingState;
@property (nonatomic, copy) NSString * _Nullable shippingZip;
@property (nonatomic, copy) NSString * _Nullable shippingCountry;
@property (nonatomic, copy) NSString * _Nullable shippingPhoneNumber;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC18SpreedlyClickToPay27ClickToPayValidationChannel")
@interface ClickToPayValidationChannel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull identityType;
@property (nonatomic, readonly, copy) NSString * _Nonnull validationChannelId;
@property (nonatomic, readonly, copy) NSString * _Nullable maskedValidationChannel;
- (nonnull instancetype)initWithIdentityType:(NSString * _Nonnull)identityType validationChannelId:(NSString * _Nonnull)validationChannelId maskedValidationChannel:(NSString * _Nullable)maskedValidationChannel OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Pattern B singleton for Click to Pay checkout (Android <code>SpreedlyClickToPayCheckout</code> parity).
SWIFT_CLASS("_TtC18SpreedlyClickToPay26SpreedlyClickToPayCheckout")
@interface SpreedlyClickToPayCheckout : NSObject
/// Objective-C / blocking interop for <code>setAutoTokenizeAuthRefresher</code>.
+ (void)setAutoTokenizeAuthRefresherBlocking:(BOOL (^ _Nullable)(void))refresher;
/// Global flow-event handler for singleton <code>present</code> / <code>presentWithConfig:from:</code> (iframe <code>Spreedly.on</code> parity).
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, weak) id <ClickToPayDelegate> _Nullable delegate;)
+ (id <ClickToPayDelegate> _Nullable)delegate SWIFT_WARN_UNUSED_RESULT;
+ (void)setDelegate:(id <ClickToPayDelegate> _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isActive;)
+ (BOOL)isActive SWIFT_WARN_UNUSED_RESULT;
+ (void)presentWithConfig:(ClickToPayCheckoutConfig * _Nonnull)config;
+ (void)presentWithConfig:(ClickToPayCheckoutConfig * _Nonnull)config from:(UIViewController * _Nonnull)viewController;
+ (void)cancel;
+ (void)signOutOnComplete:(void (^ _Nullable)(BOOL))onComplete;
+ (void)lookupWithCustomer:(ClickToPayCustomer * _Nonnull)customer;
+ (void)selectOtpChannel:(NSString * _Nonnull)channelId;
+ (void)initiateOtp;
+ (void)validateOtp:(NSString * _Nonnull)value;
+ (void)selectCard:(NSString * _Nonnull)srcDigitalCardId;
+ (void)checkoutSelectedCardWithSrcDigitalCardId:(NSString * _Nullable)srcDigitalCardId verificationValue:(NSString * _Nullable)verificationValue rememberMe:(BOOL)rememberMe;
+ (void)checkoutWithNewCardWithFields:(ClickToPayNewCardFields * _Nonnull)fields rememberMe:(BOOL)rememberMe;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.3.2 effective-5.10 (swiftlang-6.3.2.1.108 clang-2100.1.1.101)
#ifndef SPREEDLYCLICKTOPAY_SWIFT_H
#define SPREEDLYCLICKTOPAY_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SpreedlyClickToPay",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SpreedlyClickToPay",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// Card list layout for MC <code>src-card-list</code> (iframe <code>displayCards.cardSelectionType</code>).
typedef SWIFT_ENUM(NSInteger, ClickToPayCardSelectionType, open) {
  ClickToPayCardSelectionTypeRadioButton = 0,
  ClickToPayCardSelectionTypeGridView = 1,
};

@class ClickToPayInitConfig;
@class NSString;
@class ClickToPayCustomer;
@class ClickToPayDisplayCardsConfig;
@class ClickToPayOtpConfig;
@class ClickToPayTokenizeBilling;
/// Sole merchant configuration for Click to Pay checkout (Android <code>ClickToPayCheckoutConfig</code> parity).
SWIFT_CLASS("_TtC18SpreedlyClickToPay24ClickToPayCheckoutConfig")
@interface ClickToPayCheckoutConfig : NSObject
@property (nonatomic, strong) ClickToPayInitConfig * _Nonnull initConfig;
- (ClickToPayInitConfig * _Nonnull)initConfig SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) NSString * _Nonnull srcDpaId;
@property (nonatomic, copy) NSString * _Nonnull locale;
@property (nonatomic) BOOL isSandbox;
@property (nonatomic, copy) NSString * _Nonnull dpaPresentationName;
@property (nonatomic, copy) NSString * _Nonnull dpaName;
@property (nonatomic, strong) ClickToPayCustomer * _Nullable customer;
@property (nonatomic) BOOL doLookup;
@property (nonatomic, strong) ClickToPayDisplayCardsConfig * _Nonnull displayCards;
@property (nonatomic, strong) ClickToPayOtpConfig * _Nonnull otp;
@property (nonatomic, strong) ClickToPayTokenizeBilling * _Nullable tokenizeBilling;
/// Optional payment-method metadata on auto-tokenize (iframe <code>c2pCheckout</code> <code>metadata</code> parity).
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable tokenizeMetadata;
/// When <code>true</code>, sets <code>click_to_pay.test</code> on tokenize. When <code>false</code> (default), the test flag follows <code>isSandbox</code>.
@property (nonatomic) BOOL isTest;
/// When <code>true</code>, merchant UI owns saved-card selection; SDK sheet hides MC card list chrome.
@property (nonatomic) BOOL merchantHostedCardList;
/// Objective-C entry point — configure via properties after <code>[[ClickToPayCheckoutConfig alloc] init]</code>.
- (nonnull instancetype)init;
@end

@protocol ClickToPayDelegate;
@class NSCoder;
@class NSBundle;
/// UIKit host for headless Click to Pay — embeds MC WebView via <code>ClickToPayCheckoutController</code>.
SWIFT_CLASS("_TtC18SpreedlyClickToPay32ClickToPayCheckoutViewController")
@interface ClickToPayCheckoutViewController : UIViewController
@property (nonatomic, weak) id <ClickToPayDelegate> _Nullable clickToPayDelegate;
- (nonnull instancetype)initWithConfig:(ClickToPayCheckoutConfig * _Nonnull)config OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
/// Presents full-screen checkout using the singleton presenter (preferred for ObjC).
+ (void)presentWithConfig:(ClickToPayCheckoutConfig * _Nonnull)config from:(UIViewController * _Nonnull)viewController;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, ClickToPayMainLookupMethod)
/// Identity for MC <code>idLookup</code> (email and/or phone).
SWIFT_CLASS("_TtC18SpreedlyClickToPay18ClickToPayCustomer")
@interface ClickToPayCustomer : NSObject
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable phoneNumber;
@property (nonatomic, copy) NSString * _Nullable countryCode;
/// When both email and phone are set, which field drives <code>idLookup</code> (iframe default: email).
@property (nonatomic) enum ClickToPayMainLookupMethod mainLookupMethod;
- (nonnull instancetype)initWithEmail:(NSString * _Nullable)email phoneNumber:(NSString * _Nullable)phoneNumber countryCode:(NSString * _Nullable)countryCode mainLookupMethod:(enum ClickToPayMainLookupMethod)mainLookupMethod OBJC_DESIGNATED_INITIALIZER;
- (BOOL)hasEmail SWIFT_WARN_UNUSED_RESULT;
/// Phone lookup requires both number and country code (Android / iframe parity).
- (BOOL)hasPhoneLookup SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isValidForLookup SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_ENUM_FWD_DECL(NSInteger, ClickToPayEventKind)
/// Receives Click to Pay flow events from UIKit / Objective-C integrations.
SWIFT_PROTOCOL("_TtP18SpreedlyClickToPay18ClickToPayDelegate_")
@protocol ClickToPayDelegate
@optional
/// <code>checkout</code> is non-nil for embedded <code>ClickToPayCheckoutViewController</code>; nil for singleton sheet present.
- (void)clickToPay:(ClickToPayCheckoutViewController * _Nullable)checkout didReceiveEvent:(enum ClickToPayEventKind)event userInfo:(NSDictionary<NSString *, id> * _Nullable)userInfo;
@end

/// <code>src-card-list</code> customization (iframe <code>options.displayCards</code>).
SWIFT_CLASS("_TtC18SpreedlyClickToPay28ClickToPayDisplayCardsConfig")
@interface ClickToPayDisplayCardsConfig : NSObject
@property (nonatomic) BOOL displaySignOut;
@property (nonatomic) BOOL displayAddCard;
@property (nonatomic) BOOL displayPreferredCard;
@property (nonatomic) enum ClickToPayCardSelectionType cardSelectionType;
- (nonnull instancetype)initWithDisplaySignOut:(BOOL)displaySignOut displayAddCard:(BOOL)displayAddCard displayPreferredCard:(BOOL)displayPreferredCard cardSelectionType:(enum ClickToPayCardSelectionType)cardSelectionType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ClickToPayErrorCode, open) {
  ClickToPayErrorCodeC2pInit = 0,
  ClickToPayErrorCodeC2pLookup = 1,
  ClickToPayErrorCodeC2pOtp = 2,
  ClickToPayErrorCodeC2pCheckout = 3,
  ClickToPayErrorCodeC2pTokenize = 4,
  ClickToPayErrorCodeNetworkTimeout = 5,
  ClickToPayErrorCodeUnknown = 6,
};

/// Objective-C event kinds — iframe <code>Spreedly.on(...)</code> parity.
typedef SWIFT_ENUM(NSInteger, ClickToPayEventKind, open) {
  ClickToPayEventKindCheckoutStarted = 0,
  ClickToPayEventKindInitialized = 1,
  ClickToPayEventKindNewUser = 2,
  ClickToPayEventKindExistingUser = 3,
  ClickToPayEventKindVerifiedUser = 4,
  ClickToPayEventKindOtpInitiated = 5,
  ClickToPayEventKindOtpChannelSelectionRequired = 6,
  ClickToPayEventKindOtpResponse = 7,
  ClickToPayEventKindOtpResend = 8,
  ClickToPayEventKindOtpNotYou = 9,
  ClickToPayEventKindDisplayCardsReady = 10,
  ClickToPayEventKindAddNewCard = 11,
  ClickToPayEventKindCheckoutCancelled = 12,
  ClickToPayEventKindCheckoutDifferentPaymentMethod = 13,
  ClickToPayEventKindCheckoutError = 14,
  ClickToPayEventKindCheckoutWindowOpened = 15,
  ClickToPayEventKindCheckoutWindowClosed = 16,
  ClickToPayEventKindSessionDeleted = 17,
  ClickToPayEventKindCheckoutComplete = 18,
  ClickToPayEventKindPaymentMethodTokenized = 19,
  ClickToPayEventKindError = 20,
  ClickToPayEventKindValidationErrors = 21,
};

SWIFT_CLASS("_TtC18SpreedlyClickToPay20ClickToPayFieldError")
@interface ClickToPayFieldError : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull key;
@property (nonatomic, readonly, copy) NSString * _Nonnull attribute;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
/// iframe <code>errors[]</code> parity — <code>attribute</code> matches web iframe <code>c2pError</code> names; <code>key</code> is <code>errors.<attribute></code>.
- (nonnull instancetype)initWithIframeAttribute:(NSString * _Nonnull)iframeAttribute message:(NSString * _Nonnull)message OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC18SpreedlyClickToPay20ClickToPayInitConfig")
@interface ClickToPayInitConfig : NSObject
@property (nonatomic) double transactionAmount;
@property (nonatomic, copy) NSString * _Nonnull transactionCurrencyCode;
@property (nonatomic, copy) NSString * _Nonnull dynamicDataType;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull cardBrands;
- (nonnull instancetype)initWithTransactionAmount:(double)transactionAmount transactionCurrencyCode:(NSString * _Nonnull)transactionCurrencyCode dynamicDataType:(NSString * _Nonnull)dynamicDataType cardBrands:(NSArray<NSString *> * _Nonnull)cardBrands OBJC_DESIGNATED_INITIALIZER;
/// Objective-C: <code>initWithAmountCents:transactionCurrencyCode:</code> (Swift <code>amountCents</code> convenience).
- (nonnull instancetype)initWithAmountCents:(NSInteger)amountCents transactionCurrencyCode:(NSString * _Nonnull)transactionCurrencyCode;
- (nonnull instancetype)initWithAmountCents:(NSInteger)amountCents transactionCurrencyCode:(NSString * _Nonnull)transactionCurrencyCode dynamicDataType:(NSString * _Nonnull)dynamicDataType cardBrands:(NSArray<NSString *> * _Nonnull)cardBrands;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Primary identity channel for MC <code>idLookup</code> (iframe <code>customer.mainLookupMethod</code>).
typedef SWIFT_ENUM(NSInteger, ClickToPayMainLookupMethod, open) {
  ClickToPayMainLookupMethodEmail = 0,
  ClickToPayMainLookupMethodPhoneNumber = 1,
};

/// Masked card from MC <code>getCards</code> / <code>validate</code>.
SWIFT_CLASS("_TtC18SpreedlyClickToPay20ClickToPayMaskedCard")
@interface ClickToPayMaskedCard : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull srcDigitalCardId;
@property (nonatomic, readonly, copy) NSString * _Nullable panLastFour;
@property (nonatomic, readonly, copy) NSString * _Nullable cardBrand;
- (nonnull instancetype)initWithSrcDigitalCardId:(NSString * _Nonnull)srcDigitalCardId panLastFour:(NSString * _Nullable)panLastFour cardBrand:(NSString * _Nullable)cardBrand OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Native SPL card payload for MC <code>encryptCard</code> → <code>checkoutWithNewCard</code> (Android parity).
SWIFT_CLASS("_TtC18SpreedlyClickToPay23ClickToPayNewCardFields")
@interface ClickToPayNewCardFields : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull primaryAccountNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull panExpirationMonth;
@property (nonatomic, readonly, copy) NSString * _Nonnull panExpirationYearTwoDigit;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardSecurityCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardholderFirstName;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardholderLastName;
- (nonnull instancetype)initWithPrimaryAccountNumber:(NSString * _Nonnull)primaryAccountNumber panExpirationMonth:(NSString * _Nonnull)panExpirationMonth panExpirationYearTwoDigit:(NSString * _Nonnull)panExpirationYearTwoDigit cardSecurityCode:(NSString * _Nonnull)cardSecurityCode cardholderFirstName:(NSString * _Nonnull)cardholderFirstName cardholderLastName:(NSString * _Nonnull)cardholderLastName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// iframe <code>otpChannelSelectionEl</code> parity.
typedef SWIFT_ENUM(NSInteger, ClickToPayOtpChannelSelection, open) {
  ClickToPayOtpChannelSelectionInline = 0,
  ClickToPayOtpChannelSelectionExternal = 1,
};

SWIFT_ENUM_FWD_DECL(NSInteger, ClickToPayOtpPresentation)
/// OTP UI customization (iframe <code>options.otp</code>).
SWIFT_CLASS("_TtC18SpreedlyClickToPay19ClickToPayOtpConfig")
@interface ClickToPayOtpConfig : NSObject
@property (nonatomic) BOOL rememberMe;
@property (nonatomic) enum ClickToPayOtpPresentation presentation;
@property (nonatomic) enum ClickToPayOtpChannelSelection channelSelection;
@property (nonatomic, copy) NSString * _Nullable requestedValidationChannelId;
- (nonnull instancetype)initWithRememberMe:(BOOL)rememberMe presentation:(enum ClickToPayOtpPresentation)presentation channelSelection:(enum ClickToPayOtpChannelSelection)channelSelection requestedValidationChannelId:(NSString * _Nullable)requestedValidationChannelId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// OTP presentation mode for MC <code>src-otp-input</code> (iframe <code>options.otp.type</code>).
typedef SWIFT_ENUM(NSInteger, ClickToPayOtpPresentation, open) {
  ClickToPayOtpPresentationOverlay = 0,
  ClickToPayOtpPresentationNone = 1,
};

SWIFT_CLASS("_TtC18SpreedlyClickToPay25ClickToPayTokenizeBilling")
@interface ClickToPayTokenizeBilling : NSObject
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable fullName;
@property (nonatomic, copy) NSString * _Nullable month;
@property (nonatomic, copy) NSString * _Nullable year;
@property (nonatomic, copy) NSString * _Nullable addressLine1;
@property (nonatomic, copy) NSString * _Nullable addressLine2;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable zip;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable phoneNumber;
@property (nonatomic, copy) NSString * _Nullable company;
@property (nonatomic, copy) NSString * _Nullable shippingAddressLine1;
@property (nonatomic, copy) NSString * _Nullable shippingAddressLine2;
@property (nonatomic, copy) NSString * _Nullable shippingCity;
@property (nonatomic, copy) NSString * _Nullable shippingState;
@property (nonatomic, copy) NSString * _Nullable shippingZip;
@property (nonatomic, copy) NSString * _Nullable shippingCountry;
@property (nonatomic, copy) NSString * _Nullable shippingPhoneNumber;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC18SpreedlyClickToPay27ClickToPayValidationChannel")
@interface ClickToPayValidationChannel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull identityType;
@property (nonatomic, readonly, copy) NSString * _Nonnull validationChannelId;
@property (nonatomic, readonly, copy) NSString * _Nullable maskedValidationChannel;
- (nonnull instancetype)initWithIdentityType:(NSString * _Nonnull)identityType validationChannelId:(NSString * _Nonnull)validationChannelId maskedValidationChannel:(NSString * _Nullable)maskedValidationChannel OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Pattern B singleton for Click to Pay checkout (Android <code>SpreedlyClickToPayCheckout</code> parity).
SWIFT_CLASS("_TtC18SpreedlyClickToPay26SpreedlyClickToPayCheckout")
@interface SpreedlyClickToPayCheckout : NSObject
/// Objective-C / blocking interop for <code>setAutoTokenizeAuthRefresher</code>.
+ (void)setAutoTokenizeAuthRefresherBlocking:(BOOL (^ _Nullable)(void))refresher;
/// Global flow-event handler for singleton <code>present</code> / <code>presentWithConfig:from:</code> (iframe <code>Spreedly.on</code> parity).
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, weak) id <ClickToPayDelegate> _Nullable delegate;)
+ (id <ClickToPayDelegate> _Nullable)delegate SWIFT_WARN_UNUSED_RESULT;
+ (void)setDelegate:(id <ClickToPayDelegate> _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isActive;)
+ (BOOL)isActive SWIFT_WARN_UNUSED_RESULT;
+ (void)presentWithConfig:(ClickToPayCheckoutConfig * _Nonnull)config;
+ (void)presentWithConfig:(ClickToPayCheckoutConfig * _Nonnull)config from:(UIViewController * _Nonnull)viewController;
+ (void)cancel;
+ (void)signOutOnComplete:(void (^ _Nullable)(BOOL))onComplete;
+ (void)lookupWithCustomer:(ClickToPayCustomer * _Nonnull)customer;
+ (void)selectOtpChannel:(NSString * _Nonnull)channelId;
+ (void)initiateOtp;
+ (void)validateOtp:(NSString * _Nonnull)value;
+ (void)selectCard:(NSString * _Nonnull)srcDigitalCardId;
+ (void)checkoutSelectedCardWithSrcDigitalCardId:(NSString * _Nullable)srcDigitalCardId verificationValue:(NSString * _Nullable)verificationValue rememberMe:(BOOL)rememberMe;
+ (void)checkoutWithNewCardWithFields:(ClickToPayNewCardFields * _Nonnull)fields rememberMe:(BOOL)rememberMe;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
