#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.2 effective-5.10 (swiftlang-6.3.2.1.108 clang-2100.1.1.101)
#ifndef SPREEDLYPAZE_SWIFT_H
#define SPREEDLYPAZE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SpreedlyPaze",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SpreedlyPaze",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
SWIFT_ENUM_FWD_DECL(NSInteger, PazeCheckoutIntent)
@class NSDate;
SWIFT_CLASS("_TtC12SpreedlyPaze20PazeAbandonedSession")
@interface PazeAbandonedSession : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull sessionId;
@property (nonatomic, readonly) enum PazeCheckoutIntent intent;
@property (nonatomic, readonly, copy) NSDate * _Nonnull timestamp;
- (nonnull instancetype)initWithSessionId:(NSString * _Nonnull)sessionId intent:(enum PazeCheckoutIntent)intent timestamp:(NSDate * _Nonnull)timestamp OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PazeAbandonedSession (SWIFT_EXTENSION(SpreedlyPaze))
/// Value equality, preserved from when this was a struct.
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSUInteger hash;
@end

/// Objective-C bridge – Swift’s <code>async throws</code> is not visible to ObjC.
SWIFT_PROTOCOL("_TtP12SpreedlyPaze29PazeAuthorizationProviderObjC_")
@protocol PazeAuthorizationProviderObjC
- (void)accessTokenWithSessionId:(NSString * _Nonnull)sessionId completion:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
@end

typedef SWIFT_ENUM(NSInteger, PazeButtonColor, open) {
  PazeButtonColorAuto = 0,
  PazeButtonColorPazeBlue = 1,
  PazeButtonColorMidnightBlack = 2,
  PazeButtonColorWhite = 3,
  PazeButtonColorWhiteWithOutline = 4,
};

typedef SWIFT_ENUM(NSInteger, PazeButtonLabel, open) {
  PazeButtonLabelCheckoutWith = 0,
  PazeButtonLabelCheckout = 1,
  PazeButtonLabelPazeCheckout = 2,
  PazeButtonLabelDonateWith = 3,
};

typedef SWIFT_ENUM(NSInteger, PazeButtonShape, open) {
  PazeButtonShapeDefault = 0,
  PazeButtonShapePill = 1,
  PazeButtonShapeRectangle = 2,
};

/// How the wallet returns to the app, expressed for Objective-C.
/// Two factory methods rather than an enum, because an enum with associated values has no ObjC
/// representation.
SWIFT_CLASS("_TtC12SpreedlyPaze16PazeCallbackObjC")
@interface PazeCallbackObjC : NSObject
/// A custom URL scheme registered in <code>CFBundleURLTypes</code>.
+ (PazeCallbackObjC * _Nonnull)scheme:(NSString * _Nonnull)scheme SWIFT_WARN_UNUSED_RESULT;
/// A Universal Link. Requires the host to be listed in the app’s associated domains.
+ (PazeCallbackObjC * _Nonnull)universalLinkWithHost:(NSString * _Nonnull)host path:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, PazeCheckoutIntent, open) {
  PazeCheckoutIntentExpressCheckout = 0,
  PazeCheckoutIntentReviewAndPay = 1,
  PazeCheckoutIntentAddCard = 2,
};

@class PazeTransactionValueObjC;
/// Objective-C companion for <code>PazeCheckoutRequest</code>.
/// <code>transactionValue</code> is nullable because <code>ADD_CARD</code> must not carry an amount – passing one is a
/// validation failure, not a default.
SWIFT_CLASS("_TtC12SpreedlyPaze23PazeCheckoutRequestObjC")
@interface PazeCheckoutRequestObjC : NSObject
@property (nonatomic, readonly) enum PazeCheckoutIntent intent;
@property (nonatomic, readonly, copy) NSString * _Nullable emailAddress;
@property (nonatomic, readonly, strong) PazeTransactionValueObjC * _Nullable transactionValue;
@property (nonatomic, readonly, copy) NSString * _Nonnull billingPreference;
- (nonnull instancetype)initWithIntent:(enum PazeCheckoutIntent)intent emailAddress:(NSString * _Nullable)emailAddress transactionValue:(PazeTransactionValueObjC * _Nullable)transactionValue billingPreference:(NSString * _Nonnull)billingPreference OBJC_DESIGNATED_INITIALIZER;
/// Convenience for the common case, which is every checkout that does not override the billing
/// preference. Swift default arguments are invisible to Objective-C, so without this an ObjC
/// caller has to pass the default wire value itself – a detail they should not have to know.
/// Delegates to the designated initializer so the default lives in exactly one place.
- (nonnull instancetype)initWithIntent:(enum PazeCheckoutIntent)intent emailAddress:(NSString * _Nullable)emailAddress transactionValue:(PazeTransactionValueObjC * _Nullable)transactionValue;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Objective-C bridge – <code>PazeClientConfig</code> is a plain Swift struct.
SWIFT_CLASS("_TtC12SpreedlyPaze20PazeClientConfigObjC")
@interface PazeClientConfigObjC : NSObject
@property (nonatomic, copy) NSString * _Nonnull clientId;
@property (nonatomic, copy) NSString * _Nonnull clientName;
@property (nonatomic, copy) NSString * _Nonnull profileId;
- (nonnull instancetype)initWithClientId:(NSString * _Nonnull)clientId clientName:(NSString * _Nonnull)clientName profileId:(NSString * _Nonnull)profileId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PazeMaskedCard;
SWIFT_CLASS("_TtC12SpreedlyPaze18PazeCompleteResult")
@interface PazeCompleteResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull sessionId;
@property (nonatomic, readonly, copy) NSString * _Nonnull securedPayload;
@property (nonatomic, readonly, copy) NSString * _Nullable payloadId;
@property (nonatomic, readonly, strong) PazeMaskedCard * _Nonnull maskedCard;
- (nonnull instancetype)initWithSessionId:(NSString * _Nonnull)sessionId securedPayload:(NSString * _Nonnull)securedPayload payloadId:(NSString * _Nullable)payloadId maskedCard:(PazeMaskedCard * _Nonnull)maskedCard OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PazeCompleteResult (SWIFT_EXTENSION(SpreedlyPaze))
/// Value equality, preserved from when this was a struct.
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSUInteger hash;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, PazeEnvironment)
/// Objective-C companion for <code>PazeConfig</code>.
SWIFT_CLASS("_TtC12SpreedlyPaze14PazeConfigObjC")
@interface PazeConfigObjC : NSObject
@property (nonatomic, readonly, strong) PazeClientConfigObjC * _Nonnull client;
@property (nonatomic, readonly) enum PazeEnvironment environment;
@property (nonatomic, readonly, strong) PazeCallbackObjC * _Nonnull callback;
@property (nonatomic, readonly, strong) id <PazeAuthorizationProviderObjC> _Nonnull authorizationProvider;
- (nonnull instancetype)initWithClient:(PazeClientConfigObjC * _Nonnull)client environment:(enum PazeEnvironment)environment callback:(PazeCallbackObjC * _Nonnull)callback authorizationProvider:(id <PazeAuthorizationProviderObjC> _Nonnull)authorizationProvider OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_ENUM_FWD_DECL(NSInteger, PazeEventKind)
SWIFT_PROTOCOL("_TtP12SpreedlyPaze12PazeDelegate_")
@protocol PazeDelegate
@optional
- (void)pazeWithDidReceiveEvent:(enum PazeEventKind)kind userInfo:(NSDictionary<NSString *, id> * _Nonnull)userInfo;
@end

typedef SWIFT_ENUM(NSInteger, PazeEnvironment, open) {
  PazeEnvironmentSandbox = 0,
  PazeEnvironmentUat = 1,
  PazeEnvironmentProduction = 2,
};

/// Failure reasons surfaced by the Paze checkout flow.
/// Backed by <code>Int</code> so Objective-C callers can switch on it; <code>identifier</code> carries the stable string
/// used in telemetry and logs. Paze’s own <code>message</code> strings are for humans and must never become
/// the programmatic contract – match on these cases instead.
typedef SWIFT_ENUM(NSInteger, PazeErrorCode, open) {
/// <code>configure(_:)</code> was not called before <code>present(request:)</code>.
  PazeErrorCodeNotConfigured = 0,
/// The callback scheme or universal link is not registered in the app’s Info.plist/entitlements.
  PazeErrorCodeCallbackNotRegistered = 1,
/// <code>present(request:)</code> was called while a checkout was already running.
  PazeErrorCodeCheckoutAlreadyActive = 3,
/// <code>PazeCheckoutRequest</code> shape is invalid for its intent (e.g. an amount on <code>.addCard</code>, a
/// missing amount on <code>.expressCheckout</code>/<code>.reviewAndPay</code>, or a malformed amount string).
  PazeErrorCodeInvalidRequest = 4,
/// The merchant’s authorization hook threw or returned an unusable value.
  PazeErrorCodeAuthorizationFailed = 10,
/// The merchant’s authorization hook did not respond in time.
  PazeErrorCodeAuthorizationTimeout = 11,
/// The merchant’s authorization hook returned a response the SDK could not read.
  PazeErrorCodeAuthorizationMalformed = 12,
/// Paze rejected the access token. Distinct from <code>authorizationFailed</code>, which means the
/// merchant’s own backend failed – conflating the two makes every integration bug look like
/// a Paze outage.
  PazeErrorCodePazeUnauthorized = 20,
  PazeErrorCodeSessionCreateFailed = 21,
/// Paze reported the wallet is unavailable for this shopper.
  PazeErrorCodeCheckoutUnavailable = 22,
  PazeErrorCodeSessionReviewFailed = 23,
  PazeErrorCodeSessionCompleteFailed = 24,
/// The shopper dismissed the wallet.
  PazeErrorCodeWalletCancelled = 30,
/// The wallet reported a failure.
  PazeErrorCodeWalletFailed = 31,
/// The callback URL could not be parsed.
  PazeErrorCodeCallbackMalformed = 32,
/// The callback reported success but carried no response payload.
  PazeErrorCodeCallbackMissingResponse = 33,
/// The callback belongs to a session that is not the one in flight.
  PazeErrorCodeCallbackStale = 34,
/// The single-use callback code passed its validity window before the merchant confirmed.
  PazeErrorCodeCodeExpired = 35,
/// The app closed while the wallet was open, so the checkout never reached a result.
/// Surfaced on the next checkout attempt rather than at launch.
  PazeErrorCodeCheckoutIncomplete = 36,
  PazeErrorCodeNetwork = 41,
  PazeErrorCodeUnknown = 42,
};

typedef SWIFT_ENUM(NSInteger, PazeEventKind, open) {
  PazeEventKindReviewReady = 0,
  PazeEventKindWalletCancelled = 1,
  PazeEventKindBackendPayload = 2,
  PazeEventKindError = 3,
  PazeEventKindStateChanged = 4,
};

typedef SWIFT_ENUM(NSInteger, PazeFlowState, open) {
  PazeFlowStateIdle = 0,
  PazeFlowStateAuthorizing = 1,
  PazeFlowStateCreatingSession = 2,
  PazeFlowStateAwaitingWallet = 3,
  PazeFlowStateReviewing = 4,
  PazeFlowStateAwaitingMerchantConfirmation = 5,
  PazeFlowStateCompleting = 6,
  PazeFlowStateFinished = 7,
  PazeFlowStateFailed = 8,
  PazeFlowStateCancelled = 9,
  PazeFlowStateExpired = 10,
};

SWIFT_CLASS("_TtC12SpreedlyPaze14PazeMaskedCard")
@interface PazeMaskedCard : NSObject
/// Exactly 4 ASCII digits, validated by <code>PazeAPIResponseParser</code>. Never a longer or malformed
/// value – see <code>PazeAPIResponseParser.validatedLastFour</code>.
@property (nonatomic, readonly, copy) NSString * _Nullable lastFour;
@property (nonatomic, readonly, copy) NSString * _Nullable network;
- (nonnull instancetype)initWithLastFour:(NSString * _Nullable)lastFour network:(NSString * _Nullable)network OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PazeMaskedCard (SWIFT_EXTENSION(SpreedlyPaze))
/// Value equality, preserved from when this was a struct so tests and merchant code can still
/// compare two cards. NSObject would otherwise compare by identity.
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSUInteger hash;
@end

typedef SWIFT_ENUM(NSInteger, PazeMessageStyle, open) {
/// No container. Text and links adapt to the system theme. The default presentation.
  PazeMessageStyleStandard = 0,
/// Solid fill container with theme-adaptive colours.
  PazeMessageStyleFilled = 1,
/// Outlined container with a border stroke.
  PazeMessageStyleOutlined = 2,
};

typedef SWIFT_ENUM(NSInteger, PazeReviewDataSource, open) {
/// Fields parsed from the authenticated review-session response.
  PazeReviewDataSourceCompleteJSON = 0,
/// Display claims taken from the wallet callback only (not used on the review path today).
  PazeReviewDataSourceCallbackUnauthenticated = 1,
};

SWIFT_CLASS("_TtC12SpreedlyPaze17PazeReviewDetails")
@interface PazeReviewDetails : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull sessionId;
@property (nonatomic, readonly, strong) PazeMaskedCard * _Nonnull maskedCard;
@property (nonatomic, readonly, copy) NSString * _Nullable contactName;
@property (nonatomic, readonly, copy) NSString * _Nullable contactEmail;
@property (nonatomic, readonly, copy) NSString * _Nullable shippingName;
@property (nonatomic, readonly, copy) NSString * _Nullable shippingLine1;
@property (nonatomic, readonly, copy) NSString * _Nullable shippingLine2;
@property (nonatomic, readonly, copy) NSString * _Nullable paymentDescriptor;
@property (nonatomic, readonly) enum PazeReviewDataSource source;
/// Shopper-facing payment line. Prefers <code>paymentDescriptor</code>, then network + last four.
@property (nonatomic, readonly, copy) NSString * _Nullable paymentLabel;
- (nonnull instancetype)initWithSessionId:(NSString * _Nonnull)sessionId maskedCard:(PazeMaskedCard * _Nonnull)maskedCard contactName:(NSString * _Nullable)contactName contactEmail:(NSString * _Nullable)contactEmail shippingName:(NSString * _Nullable)shippingName shippingLine1:(NSString * _Nullable)shippingLine1 shippingLine2:(NSString * _Nullable)shippingLine2 paymentDescriptor:(NSString * _Nullable)paymentDescriptor source:(enum PazeReviewDataSource)source OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PazeReviewDetails (SWIFT_EXTENSION(SpreedlyPaze))
/// Value equality, preserved from when this was a struct.
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSUInteger hash;
@end

typedef SWIFT_ENUM(NSInteger, PazeTransactionType, open) {
  PazeTransactionTypePurchase = 0,
  PazeTransactionTypeCardOnFile = 1,
};

/// Objective-C companion for <code>PazeTransactionValue</code>.
SWIFT_CLASS("_TtC12SpreedlyPaze24PazeTransactionValueObjC")
@interface PazeTransactionValueObjC : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull amount;
@property (nonatomic, readonly, copy) NSString * _Nonnull currencyCode;
- (nonnull instancetype)initWithAmount:(NSString * _Nonnull)amount currencyCode:(NSString * _Nonnull)currencyCode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSCoder;
@class UITraitCollection;
@class NSBundle;
SWIFT_CLASS("_TtC12SpreedlyPaze32SpreedlyPazeButtonViewController")
@interface SpreedlyPazeButtonViewController : UIViewController
@property (nonatomic) enum PazeButtonLabel label;
@property (nonatomic) enum PazeButtonColor color;
@property (nonatomic) enum PazeButtonShape shape;
- (nonnull instancetype)initWithLabel:(enum PazeButtonLabel)label color:(enum PazeButtonColor)color shape:(enum PazeButtonShape)shape onTap:(void (^ _Nonnull)(void))onTap OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC12SpreedlyPaze20SpreedlyPazeCheckout")
@interface SpreedlyPazeCheckout : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, weak) id <PazeDelegate> _Nullable delegate;)
+ (id <PazeDelegate> _Nullable)delegate SWIFT_WARN_UNUSED_RESULT;
+ (void)setDelegate:(id <PazeDelegate> _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isActive;)
+ (BOOL)isActive SWIFT_WARN_UNUSED_RESULT;
/// Objective-C configuration entry point.
/// Swift’s <code>throws</code> surfaces to Objective-C as an <code>NSError</code> out-parameter, so the selector is
/// <code>configureWithConfig:error:</code>.
+ (BOOL)configureWithConfig:(PazeConfigObjC * _Nonnull)config error:(NSError * _Nullable * _Nullable)error;
/// Objective-C checkout entry point, presenting from the topmost view controller.
+ (void)presentWithRequest:(PazeCheckoutRequestObjC * _Nonnull)request;
/// Objective-C checkout entry point with an explicit presenting view controller.
+ (void)presentWithRequest:(PazeCheckoutRequestObjC * _Nonnull)request fromViewController:(UIViewController * _Nullable)viewController;
+ (void)confirm;
+ (void)cancel;
/// Non-<code>nil</code> only when a wallet flow was killed with the process mid-checkout – never set for
/// an in-app cancel, failure, or completion. Peek without clearing.
+ (PazeAbandonedSession * _Nullable)abandonedSession SWIFT_WARN_UNUSED_RESULT;
/// Same as <code>abandonedSession()</code>, but clears the marker so it is only ever surfaced once.
+ (PazeAbandonedSession * _Nullable)consumeAbandonedSession;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;
@class NSURL;
SWIFT_CLASS("_TtC12SpreedlyPaze19SpreedlyPazeMessage")
@interface SpreedlyPazeMessage : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
/// Objective-C entry point for <code>setMessage(html:style:darkMode:onLinkTap:)</code>.
/// The Swift method cannot be exposed directly: its <code>darkMode</code> is a <code>Bool?</code>, and an optional
/// value type has no Objective-C representation, which excludes the whole selector from the
/// generated header. <code>NSNumber?</code> carries the same three states – pass <code>nil</code> to follow the
/// system appearance, or a boolean number to force one.
- (void)setMessageWithHTML:(NSString * _Nullable)html style:(enum PazeMessageStyle)style darkMode:(NSNumber * _Nullable)darkMode onLinkTap:(void (^ _Nullable)(NSURL * _Nonnull))onLinkTap;
/// Manual height computation for callers not using Auto Layout end-to-end.
- (CGFloat)measuredHeightFor:(CGFloat)width SWIFT_WARN_UNUSED_RESULT;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
@end

@class UITextView;
@interface SpreedlyPazeMessage (SWIFT_EXTENSION(SpreedlyPaze)) <UITextViewDelegate>
- (BOOL)textView:(UITextView * _Nonnull)textView shouldInteractWithURL:(NSURL * _Nonnull)url inRange:(NSRange)characterRange interaction:(UITextItemInteraction)interaction SWIFT_WARN_UNUSED_RESULT;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
