#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.2 effective-5.10 (swiftlang-6.3.2.1.108 clang-2100.1.1.101)
#ifndef SPREEDLYPAZE_SWIFT_H
#define SPREEDLYPAZE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SpreedlyPaze",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SpreedlyPaze",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
SWIFT_ENUM_FWD_DECL(NSInteger, PazeCheckoutIntent)
@class NSDate;
SWIFT_CLASS("_TtC12SpreedlyPaze20PazeAbandonedSession")
@interface PazeAbandonedSession : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull sessionId;
@property (nonatomic, readonly) enum PazeCheckoutIntent intent;
@property (nonatomic, readonly, copy) NSDate * _Nonnull timestamp;
- (nonnull instancetype)initWithSessionId:(NSString * _Nonnull)sessionId intent:(enum PazeCheckoutIntent)intent timestamp:(NSDate * _Nonnull)timestamp OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PazeAbandonedSession (SWIFT_EXTENSION(SpreedlyPaze))
/// Value equality, preserved from when this was a struct.
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSUInteger hash;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, PazeActionLinkKind)
/// An action the wallet offers, paired with the URL that performs it.
/// Exposed but not acted on: opening one of these means launching a second authentication session
/// and handling a second callback, which is a new flow rather than a new field.
SWIFT_CLASS("_TtC12SpreedlyPaze14PazeActionLink")
@interface PazeActionLink : NSObject
@property (nonatomic, readonly) enum PazeActionLinkKind kind;
/// Raw wire value, kept so an action this version does not recognize is still identifiable.
@property (nonatomic, readonly, copy) NSString * _Nullable rawKind;
/// HTTPS only – non-HTTPS links are dropped before they reach here.
@property (nonatomic, readonly, copy) NSString * _Nonnull link;
- (nonnull instancetype)initWithKind:(enum PazeActionLinkKind)kind rawKind:(NSString * _Nullable)rawKind link:(NSString * _Nonnull)link OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PazeActionLink (SWIFT_EXTENSION(SpreedlyPaze))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSUInteger hash;
@end

/// An action the wallet offers for this checkout, such as changing the card or the address.
typedef SWIFT_ENUM(NSInteger, PazeActionLinkKind, open) {
  PazeActionLinkKindChangeCard = 0,
  PazeActionLinkKindChangeShippingAddress = 1,
/// The wallet offered an action this version does not know. The <code>link</code> is still usable.
  PazeActionLinkKindUnknown = 2,
};

@class PazeDeliveryContactDetails;
SWIFT_CLASS("_TtC12SpreedlyPaze11PazeAddress")
@interface PazeAddress : NSObject
/// Addressee, when the wallet supplied one. Not always the cardholder.
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly, copy) NSString * _Nullable line1;
@property (nonatomic, readonly, copy) NSString * _Nullable line2;
@property (nonatomic, readonly, copy) NSString * _Nullable line3;
@property (nonatomic, readonly, copy) NSString * _Nullable city;
/// State, province, or region, as the wallet spelled it.
@property (nonatomic, readonly, copy) NSString * _Nullable state;
@property (nonatomic, readonly, copy) NSString * _Nullable zip;
/// ISO country code.
@property (nonatomic, readonly, copy) NSString * _Nullable countryCode;
/// Who to contact about the delivery. Paze attaches this to the shipping address – it is not
/// returned on a billing address – and accepts it on the addresses sent with <code>complete</code>.
@property (nonatomic, readonly, strong) PazeDeliveryContactDetails * _Nullable deliveryContactDetails;
- (nonnull instancetype)initWithName:(NSString * _Nullable)name line1:(NSString * _Nullable)line1 line2:(NSString * _Nullable)line2 line3:(NSString * _Nullable)line3 city:(NSString * _Nullable)city state:(NSString * _Nullable)state zip:(NSString * _Nullable)zip countryCode:(NSString * _Nullable)countryCode deliveryContactDetails:(PazeDeliveryContactDetails * _Nullable)deliveryContactDetails OBJC_DESIGNATED_INITIALIZER;
/// True when the wallet sent the object but every field inside it was empty. Lets a caller
/// tell “no address” from “an address with nothing in it” without checking eight properties.
@property (nonatomic, readonly) BOOL isEmpty;
/// Address as display lines, empty components dropped. Ordered street-to-country so it reads
/// correctly when joined with newlines.
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull displayLines;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PazeAddress (SWIFT_EXTENSION(SpreedlyPaze))
/// Value equality. <code>NSObject</code> would otherwise compare by identity, which would make two
/// identical addresses from the same response compare unequal.
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSUInteger hash;
@end

/// Objective-C bridge – Swift’s <code>async throws</code> is not visible to ObjC.
SWIFT_PROTOCOL("_TtP12SpreedlyPaze29PazeAuthorizationProviderObjC_")
@protocol PazeAuthorizationProviderObjC
- (void)accessTokenWithSessionId:(NSString * _Nonnull)sessionId completion:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
@end

/// Which billing addresses the wallet offers, and how much of each it returns.
/// Official create and complete only accept <code>ALL</code> and <code>NONE</code>.
typedef SWIFT_ENUM(NSInteger, PazeBillingPreference, open) {
  PazeBillingPreferenceAll = 0,
  PazeBillingPreferenceNone = 1,
};

typedef SWIFT_ENUM(NSInteger, PazeButtonColor, open) {
/// Adapts to the current interface style: Paze Blue in light, white in dark.
  PazeButtonColorAuto = -1,
  PazeButtonColorPazeBlue = 0,
  PazeButtonColorWhite = 1,
  PazeButtonColorWhiteWithOutline = 2,
  PazeButtonColorMidnightBlack = 3,
};

typedef SWIFT_ENUM(NSInteger, PazeButtonLabel, open) {
  PazeButtonLabelCheckoutWith = 0,
  PazeButtonLabelCheckout = 1,
  PazeButtonLabelPazeCheckout = 2,
  PazeButtonLabelDonateWith = 3,
};

typedef SWIFT_ENUM(NSInteger, PazeButtonShape, open) {
  PazeButtonShapeDefault = 0,
  PazeButtonShapeRectangle = 1,
  PazeButtonShapePill = 2,
};

/// How the wallet returns to the app, expressed for Objective-C.
/// Two factory methods rather than an enum, because an enum with associated values has no ObjC
/// representation.
SWIFT_CLASS("_TtC12SpreedlyPaze16PazeCallbackObjC")
@interface PazeCallbackObjC : NSObject
/// A custom URL scheme registered in <code>CFBundleURLTypes</code>.
+ (PazeCallbackObjC * _Nonnull)scheme:(NSString * _Nonnull)scheme SWIFT_WARN_UNUSED_RESULT;
/// A Universal Link. Requires the host to be listed in the app’s associated domains.
+ (PazeCallbackObjC * _Nonnull)universalLinkWithHost:(NSString * _Nonnull)host path:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Funding type behind the card.
typedef SWIFT_ENUM(NSInteger, PazeCardType, open) {
  PazeCardTypeCredit = 0,
  PazeCardTypeDebit = 1,
/// The wallet reported a type this version of the SDK does not know.
  PazeCardTypeUnknown = 2,
};

typedef SWIFT_ENUM(NSInteger, PazeCheckoutIntent, open) {
  PazeCheckoutIntentExpressCheckout = 0,
  PazeCheckoutIntentReviewAndPay = 1,
  PazeCheckoutIntentAddCard = 2,
};

@class PazeTransactionValueObjC;
SWIFT_ENUM_FWD_DECL(NSInteger, PazeTransactionType)
SWIFT_ENUM_FWD_DECL(NSInteger, PazeShippingPreference)
SWIFT_ENUM_FWD_DECL(NSInteger, PazePayloadType)
@class PazeEnhancedTransactionDataObjC;
@class PazeCobrandEntryObjC;
SWIFT_ENUM_FWD_DECL(NSInteger, PazeUseCase)
@class NSNumber;
SWIFT_ENUM_FWD_DECL(NSInteger, PazeProcessingNetwork)
/// Objective-C companion for <code>PazeCheckoutRequest</code>.
/// <code>transactionValue</code> is nullable because <code>ADD_CARD</code> must not carry an amount – passing one is a
/// validation failure, not a default.
SWIFT_CLASS("_TtC12SpreedlyPaze23PazeCheckoutRequestObjC")
@interface PazeCheckoutRequestObjC : NSObject
@property (nonatomic, readonly) enum PazeCheckoutIntent intent;
@property (nonatomic, readonly, copy) NSString * _Nullable emailAddress;
/// Digits only, <code>1</code> followed by 10 digits. Supply this or <code>emailAddress</code>.
@property (nonatomic, readonly, copy) NSString * _Nullable phoneNumber;
@property (nonatomic, readonly, strong) PazeTransactionValueObjC * _Nullable transactionValue;
@property (nonatomic, readonly) enum PazeBillingPreference billingPreference;
/// Mirrors the Swift <code>transactionType: PazeTransactionType?</code>. Objective-C cannot express an
/// optional enum, so <code>usesDerivedTransactionType</code> carries the “not set” state instead.
@property (nonatomic, readonly) enum PazeTransactionType transactionType;
/// <code>true</code> when the type should be derived from the intent, as it is by default.
@property (nonatomic, readonly) BOOL usesDerivedTransactionType;
@property (nonatomic, readonly) enum PazeShippingPreference shippingPreference;
@property (nonatomic, readonly, copy) NSString * _Nullable merchantCategoryCode;
@property (nonatomic, readonly) enum PazePayloadType payloadType;
@property (nonatomic, readonly) BOOL pazeOnFile;
@property (nonatomic, readonly, strong) PazeEnhancedTransactionDataObjC * _Nullable enhancedTransactionData;
/// When true, create still returns a checkout URL for an unrecognized contact.
@property (nonatomic, readonly) BOOL alwaysEnableCheckout;
/// Cobranded cards to highlight in the wallet, highest priority first. Omitted when empty.
@property (nonatomic, readonly, copy) NSArray<PazeCobrandEntryObjC *> * _Nullable cobrand;
/// Mirrors Swift <code>useCase: PazeUseCase?</code>. Objective-C cannot express an optional enum.
@property (nonatomic, readonly) enum PazeUseCase useCase;
/// <code>true</code> when <code>useCase</code> should be sent, as it is by default when set via the designated
/// initializer’s <code>useCase</code>/<code>hasUseCase</code> pair.
@property (nonatomic, readonly) BOOL hasUseCase;
/// ISO 3166-1 alpha-2 countries the merchant ships to. Omitted when empty.
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable acceptedShippingCountries;
/// Networks the merchant accepts, as <code>PazePaymentCardNetwork</code> raw values. Omitted when empty;
/// empty or absent means all networks.
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nullable acceptedPaymentCardNetworks;
/// Mirrors Swift <code>processingNetwork: PazeProcessingNetwork?</code>. Network used to process the
/// completed payload. Sent on complete only.
@property (nonatomic, readonly) enum PazeProcessingNetwork processingNetwork;
/// <code>true</code> when <code>processingNetwork</code> should be sent, mirroring the <code>useCase</code>/<code>hasUseCase</code> pair.
@property (nonatomic, readonly) BOOL hasProcessingNetwork;
- (nonnull instancetype)initWithIntent:(enum PazeCheckoutIntent)intent emailAddress:(NSString * _Nullable)emailAddress phoneNumber:(NSString * _Nullable)phoneNumber transactionValue:(PazeTransactionValueObjC * _Nullable)transactionValue billingPreference:(enum PazeBillingPreference)billingPreference transactionType:(enum PazeTransactionType)transactionType usesDerivedTransactionType:(BOOL)usesDerivedTransactionType shippingPreference:(enum PazeShippingPreference)shippingPreference merchantCategoryCode:(NSString * _Nullable)merchantCategoryCode payloadType:(enum PazePayloadType)payloadType pazeOnFile:(BOOL)pazeOnFile enhancedTransactionData:(PazeEnhancedTransactionDataObjC * _Nullable)enhancedTransactionData alwaysEnableCheckout:(BOOL)alwaysEnableCheckout cobrand:(NSArray<PazeCobrandEntryObjC *> * _Nullable)cobrand useCase:(enum PazeUseCase)useCase hasUseCase:(BOOL)hasUseCase acceptedShippingCountries:(NSArray<NSString *> * _Nullable)acceptedShippingCountries acceptedPaymentCardNetworks:(NSArray<NSNumber *> * _Nullable)acceptedPaymentCardNetworks processingNetwork:(enum PazeProcessingNetwork)processingNetwork hasProcessingNetwork:(BOOL)hasProcessingNetwork OBJC_DESIGNATED_INITIALIZER;
/// Sets an explicit transaction type, which is the only way an ObjC caller can reach <code>BOTH</code>
/// (charge and store in one call).
- (nonnull instancetype)initWithIntent:(enum PazeCheckoutIntent)intent emailAddress:(NSString * _Nullable)emailAddress transactionValue:(PazeTransactionValueObjC * _Nullable)transactionValue transactionType:(enum PazeTransactionType)transactionType;
/// Convenience for the common case, which is every checkout that does not override the billing
/// preference. Swift default arguments are invisible to Objective-C, so without this an ObjC
/// caller has to pass the default wire value itself – a detail they should not have to know.
/// Delegates to the designated initializer so the default lives in exactly one place.
- (nonnull instancetype)initWithIntent:(enum PazeCheckoutIntent)intent emailAddress:(NSString * _Nullable)emailAddress transactionValue:(PazeTransactionValueObjC * _Nullable)transactionValue;
/// Phone-identified consumers. Paze accepts email <em>or</em> phone, so this is the entry point for
/// a merchant who holds only the latter.
- (nonnull instancetype)initWithIntent:(enum PazeCheckoutIntent)intent phoneNumber:(NSString * _Nullable)phoneNumber transactionValue:(PazeTransactionValueObjC * _Nullable)transactionValue;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Objective-C bridge – <code>PazeClientConfig</code> is a plain Swift struct.
SWIFT_CLASS("_TtC12SpreedlyPaze20PazeClientConfigObjC")
@interface PazeClientConfigObjC : NSObject
@property (nonatomic, copy) NSString * _Nonnull clientId;
@property (nonatomic, copy) NSString * _Nonnull clientName;
@property (nonatomic, copy) NSString * _Nonnull profileId;
@property (nonatomic, copy) NSString * _Nullable merchantCategoryCode;
- (nonnull instancetype)initWithClientId:(NSString * _Nonnull)clientId clientName:(NSString * _Nonnull)clientName profileId:(NSString * _Nonnull)profileId merchantCategoryCode:(NSString * _Nullable)merchantCategoryCode OBJC_DESIGNATED_INITIALIZER;
/// Objective-C cannot see Swift default arguments, so the three-identifier case – which is
/// every merchant who configures nothing extra – needs its own selector.
- (nonnull instancetype)initWithClientId:(NSString * _Nonnull)clientId clientName:(NSString * _Nonnull)clientName profileId:(NSString * _Nonnull)profileId;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Objective-C companion for <code>PazeCobrandEntry</code>.
SWIFT_CLASS("_TtC12SpreedlyPaze20PazeCobrandEntryObjC")
@interface PazeCobrandEntryObjC : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly) BOOL benefitsOffered;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name benefitsOffered:(BOOL)benefitsOffered OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PazeMaskedCard;
SWIFT_ENUM_FWD_DECL(NSInteger, PazeOnFileStatus)
SWIFT_CLASS("_TtC12SpreedlyPaze18PazeCompleteResult")
@interface PazeCompleteResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull sessionId;
@property (nonatomic, readonly, copy) NSString * _Nonnull securedPayload;
@property (nonatomic, readonly, copy) NSString * _Nullable payloadId;
@property (nonatomic, readonly, strong) PazeMaskedCard * _Nonnull maskedCard;
/// The signed envelope wrapping the secured payload, passed through byte for byte.
/// Deliberately not opened on device: verifying it needs the merchant’s own keys, and the SDK
/// makes no payment decision from it. Forward it to the backend that already handles
/// <code>securedPayload</code> and verify it there.
@property (nonatomic, readonly, copy) NSString * _Nullable completeResponse;
/// Identifier for the stored card, present when the wallet created one.
@property (nonatomic, readonly, copy) NSString * _Nullable pazeOnFileId;
@property (nonatomic, readonly) enum PazeOnFileStatus pazeOnFileStatus;
/// Where the consumer asked the order to be sent. Present when the checkout collected one.
@property (nonatomic, readonly, strong) PazeAddress * _Nullable shippingAddress;
/// Paze’s support correlation id. Worth putting in merchant logs – it is what Paze support
/// asks for when investigating a specific checkout.
@property (nonatomic, readonly, copy) NSString * _Nullable ewSID;
- (nonnull instancetype)initWithSessionId:(NSString * _Nonnull)sessionId securedPayload:(NSString * _Nonnull)securedPayload payloadId:(NSString * _Nullable)payloadId maskedCard:(PazeMaskedCard * _Nonnull)maskedCard completeResponse:(NSString * _Nullable)completeResponse pazeOnFileId:(NSString * _Nullable)pazeOnFileId pazeOnFileStatus:(enum PazeOnFileStatus)pazeOnFileStatus shippingAddress:(PazeAddress * _Nullable)shippingAddress ewSID:(NSString * _Nullable)ewSID OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PazeCompleteResult (SWIFT_EXTENSION(SpreedlyPaze))
/// Value equality, preserved from when this was a struct.
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSUInteger hash;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, PazeEnvironment)
/// Objective-C companion for <code>PazeConfig</code>.
SWIFT_CLASS("_TtC12SpreedlyPaze14PazeConfigObjC")
@interface PazeConfigObjC : NSObject
@property (nonatomic, readonly, strong) PazeClientConfigObjC * _Nonnull client;
@property (nonatomic, readonly) enum PazeEnvironment environment;
@property (nonatomic, readonly, strong) PazeCallbackObjC * _Nonnull callback;
@property (nonatomic, readonly, strong) id <PazeAuthorizationProviderObjC> _Nonnull authorizationProvider;
- (nonnull instancetype)initWithClient:(PazeClientConfigObjC * _Nonnull)client environment:(enum PazeEnvironment)environment callback:(PazeCallbackObjC * _Nonnull)callback authorizationProvider:(id <PazeAuthorizationProviderObjC> _Nonnull)authorizationProvider OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// A phone number split the way Paze’s <code>contactPhoneNumber</code> and <code>mobileNumber</code> objects carry it.
SWIFT_CLASS("_TtC12SpreedlyPaze22PazeContactPhoneNumber")
@interface PazeContactPhoneNumber : NSObject
/// ITU/ISD dialing code without a <code>+</code>, e.g. <code>"1"</code>. 1…4 characters.
@property (nonatomic, readonly, copy) NSString * _Nonnull countryCode;
/// Subscriber digits only, no country code, e.g. <code>"7735882300"</code>. Up to 10 digits.
@property (nonatomic, readonly, copy) NSString * _Nonnull phoneNumber;
- (nonnull instancetype)initWithCountryCode:(NSString * _Nonnull)countryCode phoneNumber:(NSString * _Nonnull)phoneNumber OBJC_DESIGNATED_INITIALIZER;
/// <code>+</code> followed by country code and subscriber digits. Display only – the wire form stays
/// split, and this is lossy in the direction that matters.
@property (nonatomic, readonly, copy) NSString * _Nonnull e164;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PazeContactPhoneNumber (SWIFT_EXTENSION(SpreedlyPaze))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSUInteger hash;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, PazeEventKind)
SWIFT_PROTOCOL("_TtP12SpreedlyPaze12PazeDelegate_")
@protocol PazeDelegate
@optional
- (void)pazeWithDidReceiveEvent:(enum PazeEventKind)kind userInfo:(NSDictionary<NSString *, id> * _Nonnull)userInfo;
@end

/// Delivery contact for a shipping address. Both fields are optional: the wallet returns whichever
/// the consumer supplied, and a merchant sending an address may know neither.
SWIFT_CLASS("_TtC12SpreedlyPaze26PazeDeliveryContactDetails")
@interface PazeDeliveryContactDetails : NSObject
/// Contact’s full name. Up to 100 characters.
@property (nonatomic, readonly, copy) NSString * _Nullable contactFullName;
@property (nonatomic, readonly, strong) PazeContactPhoneNumber * _Nullable contactPhoneNumber;
- (nonnull instancetype)initWithContactFullName:(NSString * _Nullable)contactFullName contactPhoneNumber:(PazeContactPhoneNumber * _Nullable)contactPhoneNumber OBJC_DESIGNATED_INITIALIZER;
/// True when the object carries nothing, so it can be omitted rather than sent empty.
@property (nonatomic, readonly) BOOL isEmpty;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PazeDeliveryContactDetails (SWIFT_EXTENSION(SpreedlyPaze))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSUInteger hash;
@end

SWIFT_CLASS("_TtC12SpreedlyPaze19PazeDigitalCardData")
@interface PazeDigitalCardData : NSObject
/// HTTPS art URL. Non-HTTPS values are rejected before they reach here, so a merchant can load
/// this without re-checking the scheme.
@property (nonatomic, readonly, copy) NSString * _Nullable artUri;
/// Intrinsic art size, when the wallet reported it. Zero means “not stated”.
@property (nonatomic, readonly) NSInteger artWidth;
@property (nonatomic, readonly) NSInteger artHeight;
- (nonnull instancetype)initWithArtUri:(NSString * _Nullable)artUri artWidth:(NSInteger)artWidth artHeight:(NSInteger)artHeight OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) BOOL isEmpty;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PazeDigitalCardData (SWIFT_EXTENSION(SpreedlyPaze))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSUInteger hash;
@end

/// Objective-C companion for <code>PazeEcomData</code>.
/// The booleans are <code>NSNumber</code> rather than <code>BOOL</code> because each is genuinely optional: Objective-C
/// cannot express <code>Bool?</code>, and a plain <code>BOOL</code> would force every caller to send <code>false</code> for fields
/// they mean to omit.
SWIFT_CLASS("_TtC12SpreedlyPaze16PazeEcomDataObjC")
@interface PazeEcomDataObjC : NSObject
@property (nonatomic, readonly, strong) NSNumber * _Nullable cartContainsGiftCard;
@property (nonatomic, readonly, strong) NSNumber * _Nullable orderForPickup;
@property (nonatomic, readonly, copy) NSString * _Nullable orderQuantity;
@property (nonatomic, readonly, copy) NSString * _Nullable orderHighestCost;
@property (nonatomic, readonly, strong) PazeAddress * _Nullable finalShippingAddress;
- (nonnull instancetype)initWithCartContainsGiftCard:(NSNumber * _Nullable)cartContainsGiftCard orderForPickup:(NSNumber * _Nullable)orderForPickup orderQuantity:(NSString * _Nullable)orderQuantity orderHighestCost:(NSString * _Nullable)orderHighestCost finalShippingAddress:(PazeAddress * _Nullable)finalShippingAddress OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PazeTravelDataObjC;
/// Objective-C companion for <code>PazeEnhancedTransactionData</code>.
SWIFT_CLASS("_TtC12SpreedlyPaze31PazeEnhancedTransactionDataObjC")
@interface PazeEnhancedTransactionDataObjC : NSObject
@property (nonatomic, readonly, strong) PazeEcomDataObjC * _Nullable ecomData;
@property (nonatomic, readonly, strong) PazeTravelDataObjC * _Nullable travelData;
- (nonnull instancetype)initWithEcomData:(PazeEcomDataObjC * _Nullable)ecomData travelData:(PazeTravelDataObjC * _Nullable)travelData OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, PazeEnvironment, open) {
  PazeEnvironmentSandbox = 0,
  PazeEnvironmentUat = 1,
  PazeEnvironmentProduction = 2,
};

/// Failure reasons surfaced by the Paze checkout flow.
/// Backed by <code>Int</code> so Objective-C callers can switch on it; <code>identifier</code> carries the stable string
/// used in telemetry and logs. Paze’s own <code>message</code> strings are for humans and must never become
/// the programmatic contract – match on these cases instead.
typedef SWIFT_ENUM(NSInteger, PazeErrorCode, open) {
/// <code>configure(_:)</code> was not called before <code>present(request:)</code>.
  PazeErrorCodeNotConfigured = 0,
/// The callback scheme or universal link is not registered in the app’s Info.plist/entitlements.
  PazeErrorCodeCallbackNotRegistered = 1,
/// <code>present(request:)</code> was called while a checkout was already running.
  PazeErrorCodeCheckoutAlreadyActive = 3,
/// <code>PazeCheckoutRequest</code> shape is invalid for its intent (e.g. an amount on <code>.addCard</code>, a
/// missing amount on <code>.expressCheckout</code>/<code>.reviewAndPay</code>, or a malformed amount string).
  PazeErrorCodeInvalidRequest = 4,
/// The merchant’s authorization hook threw or returned an unusable value.
  PazeErrorCodeAuthorizationFailed = 10,
/// The merchant’s authorization hook did not respond in time.
  PazeErrorCodeAuthorizationTimeout = 11,
/// The merchant’s authorization hook returned a response the SDK could not read.
  PazeErrorCodeAuthorizationMalformed = 12,
/// Paze rejected the access token. Distinct from <code>authorizationFailed</code>, which means the
/// merchant’s own backend failed – conflating the two makes every integration bug look like
/// a Paze outage.
  PazeErrorCodePazeUnauthorized = 20,
  PazeErrorCodeSessionCreateFailed = 21,
/// Paze reported the wallet is unavailable for this shopper.
  PazeErrorCodeCheckoutUnavailable = 22,
  PazeErrorCodeSessionReviewFailed = 23,
  PazeErrorCodeSessionCompleteFailed = 24,
/// Paze is shedding load. The SDK already backed off and retried; this means the limit
/// outlasted the retry budget, so the caller should try again later rather than immediately.
  PazeErrorCodePazeRateLimited = 25,
/// Complete returned 2xx but carried no sealed payload, so there is nothing to charge with.
/// Distinct from <code>sessionCompleteFailed</code>, which means the call itself failed – Android
/// separates the two as <code>NO_SECURED_PAYLOAD</code>, and a merchant retries them differently.
  PazeErrorCodeNoSecuredPayload = 26,
/// The shopper dismissed the wallet.
  PazeErrorCodeWalletCancelled = 30,
/// The wallet reported a failure.
  PazeErrorCodeWalletFailed = 31,
/// The callback URL could not be parsed.
  PazeErrorCodeCallbackMalformed = 32,
/// The callback reported success but carried no response payload.
  PazeErrorCodeCallbackMissingResponse = 33,
/// The callback belongs to a session that is not the one in flight.
  PazeErrorCodeCallbackStale = 34,
/// The single-use callback code passed its validity window before the merchant confirmed.
  PazeErrorCodeCodeExpired = 35,
/// The app closed while the wallet was open, so the checkout never reached a result.
/// Surfaced on the next checkout attempt rather than at launch.
  PazeErrorCodeCheckoutIncomplete = 36,
  PazeErrorCodeNetwork = 41,
  PazeErrorCodeUnknown = 42,
};

typedef SWIFT_ENUM(NSInteger, PazeEventKind, open) {
  PazeEventKindCanCheckout = 0,
  PazeEventKindReviewReady = 1,
  PazeEventKindWalletCancelled = 2,
  PazeEventKindBackendPayload = 3,
  PazeEventKindError = 4,
  PazeEventKindStateChanged = 5,
};

typedef SWIFT_ENUM(NSInteger, PazeFlowState, open) {
  PazeFlowStateIdle = 0,
  PazeFlowStateAuthorizing = 1,
  PazeFlowStateCreatingSession = 2,
  PazeFlowStateAwaitingWallet = 3,
  PazeFlowStateReviewing = 4,
  PazeFlowStateAwaitingMerchantConfirmation = 5,
  PazeFlowStateCompleting = 6,
  PazeFlowStateFinished = 7,
  PazeFlowStateFailed = 8,
  PazeFlowStateCancelled = 9,
  PazeFlowStateExpired = 10,
};

SWIFT_ENUM_FWD_DECL(NSInteger, PazePayoutSupport)
SWIFT_CLASS("_TtC12SpreedlyPaze14PazeMaskedCard")
@interface PazeMaskedCard : NSObject
/// Exactly 4 ASCII digits, validated by <code>PazeAPIResponseParser</code>. Never a longer or malformed
/// value – see <code>PazeAPIResponseParser.validatedLastFour</code>.
@property (nonatomic, readonly, copy) NSString * _Nullable lastFour;
@property (nonatomic, readonly, copy) NSString * _Nullable network;
/// Wallet identifier for this specific digital card.
@property (nonatomic, readonly, copy) NSString * _Nullable digitalCardId;
/// Consumer-facing card description, e.g. <code>"Acme Rewards Visa"</code>.
@property (nonatomic, readonly, copy) NSString * _Nullable descriptor;
/// Issuer brand, which is not always the same string as <code>network</code>.
@property (nonatomic, readonly, copy) NSString * _Nullable brand;
@property (nonatomic, readonly) enum PazeCardType cardType;
/// Payment Account Reference: a stable identifier for the underlying account across tokens.
/// Useful for recognising a returning consumer without storing anything card-like.
@property (nonatomic, readonly, copy) NSString * _Nullable paymentAccountReference;
/// Expiry as the wallet reported it. Not validated into a date – the merchant displays it and
/// the processor enforces it.
@property (nonatomic, readonly, copy) NSString * _Nullable expirationMonth;
@property (nonatomic, readonly, copy) NSString * _Nullable expirationYear;
@property (nonatomic, readonly, strong) PazeDigitalCardData * _Nullable digitalCardData;
/// Billing address, required by the review schema. Needed for AVS.
@property (nonatomic, readonly, strong) PazeAddress * _Nullable billingAddress;
@property (nonatomic, readonly) enum PazePayoutSupport payoutSupported;
- (nonnull instancetype)initWithLastFour:(NSString * _Nullable)lastFour network:(NSString * _Nullable)network digitalCardId:(NSString * _Nullable)digitalCardId descriptor:(NSString * _Nullable)descriptor brand:(NSString * _Nullable)brand cardType:(enum PazeCardType)cardType paymentAccountReference:(NSString * _Nullable)paymentAccountReference expirationMonth:(NSString * _Nullable)expirationMonth expirationYear:(NSString * _Nullable)expirationYear digitalCardData:(PazeDigitalCardData * _Nullable)digitalCardData billingAddress:(PazeAddress * _Nullable)billingAddress payoutSupported:(enum PazePayoutSupport)payoutSupported OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PazeMaskedCard (SWIFT_EXTENSION(SpreedlyPaze))
/// Value equality, preserved from when this was a struct so tests and merchant code can still
/// compare two cards. NSObject would otherwise compare by identity.
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSUInteger hash;
@end

typedef SWIFT_ENUM(NSInteger, PazeMessageStyle, open) {
/// No container. Text and links adapt to the system theme. The default presentation.
  PazeMessageStyleStandard = 0,
/// Solid fill container with theme-adaptive colours.
  PazeMessageStyleFilled = 1,
/// Outlined container with a border stroke.
  PazeMessageStyleOutlined = 2,
};

/// Whether the wallet stored the card for future use, and why not when it did not.
/// Carries an <code>unknown</code> case because Paze reserves the right to add values at any time and expects
/// integrators to ignore ones they do not recognize. An unrecognized status must never fail the
/// decode – the payment itself already succeeded by the time this is read.
typedef SWIFT_ENUM(NSInteger, PazeOnFileStatus, open) {
/// The checkout did not ask for the card to be stored.
  PazeOnFileStatusNotRequested = 0,
/// The card was stored; <code>pazeOnFileId</code> identifies it.
  PazeOnFileStatusCreated = 1,
/// Storing was requested but the consumer or profile does not permit it.
  PazeOnFileStatusNotEnabled = 2,
/// Storing was requested and attempted, but did not succeed.
  PazeOnFileStatusFailed = 3,
/// The wallet reported a status this version of the SDK does not know.
  PazeOnFileStatusUnknown = 4,
};

/// What the wallet seals into the payload returned by <code>complete</code>.
typedef SWIFT_ENUM(NSInteger, PazePayloadType, open) {
/// Payment credentials. The SDK sends this explicitly because the wallet’s own default is
/// <code>ID</code>, which carries no credentials to charge.
  PazePayloadTypePayment = 0,
/// Consumer identity only, with no payment credentials.
  PazePayloadTypeId = 1,
};

/// Card networks the merchant accepts on this checkout. Omit or empty means all networks.
typedef SWIFT_ENUM(NSInteger, PazePaymentCardNetwork, open) {
  PazePaymentCardNetworkVisa = 0,
  PazePaymentCardNetworkMastercard = 1,
  PazePaymentCardNetworkDiscover = 2,
};

/// Whether the card can receive a payout (disbursement), as opposed to only being charged.
/// Three states rather than a <code>Bool</code>: the wallet omitting the field is not the same answer as the
/// wallet saying no, and collapsing them would make an unknown look like a refusal.
typedef SWIFT_ENUM(NSInteger, PazePayoutSupport, open) {
  PazePayoutSupportSupported = 0,
  PazePayoutSupportNotSupported = 1,
/// The wallet did not say, or said something this version does not recognize.
  PazePayoutSupportUnknown = 2,
};

/// Network used to process the completed payload. Overrides the card’s front network.
typedef SWIFT_ENUM(NSInteger, PazeProcessingNetwork, open) {
  PazeProcessingNetworkVisa = 0,
  PazeProcessingNetworkMastercard = 1,
};

SWIFT_CLASS("_TtC12SpreedlyPaze17PazeReviewDetails")
@interface PazeReviewDetails : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull sessionId;
@property (nonatomic, readonly, strong) PazeMaskedCard * _Nonnull maskedCard;
@property (nonatomic, readonly, copy) NSString * _Nullable contactName;
@property (nonatomic, readonly, copy) NSString * _Nullable contactEmail;
@property (nonatomic, readonly, copy) NSString * _Nullable shippingName;
@property (nonatomic, readonly, copy) NSString * _Nullable shippingLine1;
@property (nonatomic, readonly, copy) NSString * _Nullable shippingLine2;
@property (nonatomic, readonly, copy) NSString * _Nullable paymentDescriptor;
/// Full structured shipping address. The flattened strings above are a display convenience
/// over the same data, but they drop line2, line3, and the country.
@property (nonatomic, readonly, strong) PazeAddress * _Nullable shippingAddress;
/// Who to contact about the delivery, when the wallet collected someone different.
@property (nonatomic, readonly, copy) NSString * _Nullable deliveryContactName;
@property (nonatomic, readonly, copy) NSString * _Nullable deliveryPhoneNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable consumerPhoneNumber;
/// Consumer country and language, for merchants localising their own review screen.
@property (nonatomic, readonly, copy) NSString * _Nullable consumerCountryCode;
@property (nonatomic, readonly, copy) NSString * _Nullable consumerLanguageCode;
/// Actions the wallet offers, such as changing the card or the shipping address. Exposed for
/// merchants to surface; acting on one is a separate flow the SDK does not drive.
@property (nonatomic, readonly, copy) NSArray<PazeActionLink *> * _Nonnull links;
/// Paze’s support correlation id for this review call.
@property (nonatomic, readonly, copy) NSString * _Nullable ewSID;
/// Shopper-facing payment line. Prefers <code>paymentDescriptor</code>, then network + last four.
@property (nonatomic, readonly, copy) NSString * _Nullable paymentLabel;
- (nonnull instancetype)initWithSessionId:(NSString * _Nonnull)sessionId maskedCard:(PazeMaskedCard * _Nonnull)maskedCard contactName:(NSString * _Nullable)contactName contactEmail:(NSString * _Nullable)contactEmail shippingName:(NSString * _Nullable)shippingName shippingLine1:(NSString * _Nullable)shippingLine1 shippingLine2:(NSString * _Nullable)shippingLine2 paymentDescriptor:(NSString * _Nullable)paymentDescriptor shippingAddress:(PazeAddress * _Nullable)shippingAddress deliveryContactName:(NSString * _Nullable)deliveryContactName deliveryPhoneNumber:(NSString * _Nullable)deliveryPhoneNumber consumerPhoneNumber:(NSString * _Nullable)consumerPhoneNumber consumerCountryCode:(NSString * _Nullable)consumerCountryCode consumerLanguageCode:(NSString * _Nullable)consumerLanguageCode links:(NSArray<PazeActionLink *> * _Nonnull)links ewSID:(NSString * _Nullable)ewSID OBJC_DESIGNATED_INITIALIZER;
/// The URL for a given wallet action, when it offered one.
- (NSString * _Nullable)linkFor:(enum PazeActionLinkKind)kind SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PazeReviewDetails (SWIFT_EXTENSION(SpreedlyPaze))
/// Value equality, preserved from when this was a struct.
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSUInteger hash;
@end

/// Which shipping addresses the wallet offers the consumer.
typedef SWIFT_ENUM(NSInteger, PazeShippingPreference, open) {
/// Offer the consumer’s stored shipping addresses.
  PazeShippingPreferenceAll = 0,
/// Suppress address selection. Forced for <code>.addCard</code>, which collects no address.
  PazeShippingPreferenceNone = 1,
};

typedef SWIFT_ENUM(NSInteger, PazeTransactionType, open) {
  PazeTransactionTypePurchase = 0,
  PazeTransactionTypeCardOnFile = 1,
/// Charge now <em>and</em> store the card, in one complete call.
  PazeTransactionTypeBoth = 2,
};

/// Objective-C companion for <code>PazeTransactionValue</code>.
SWIFT_CLASS("_TtC12SpreedlyPaze24PazeTransactionValueObjC")
@interface PazeTransactionValueObjC : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull amount;
@property (nonatomic, readonly, copy) NSString * _Nonnull currencyCode;
@property (nonatomic, readonly, copy) NSString * _Nullable subtotal;
@property (nonatomic, readonly, copy) NSString * _Nullable taxAmount;
@property (nonatomic, readonly, copy) NSString * _Nullable shippingAmount;
@property (nonatomic, readonly, copy) NSString * _Nullable discountAmount;
- (nonnull instancetype)initWithAmount:(NSString * _Nonnull)amount currencyCode:(NSString * _Nonnull)currencyCode subtotal:(NSString * _Nullable)subtotal taxAmount:(NSString * _Nullable)taxAmount shippingAmount:(NSString * _Nullable)shippingAmount discountAmount:(NSString * _Nullable)discountAmount OBJC_DESIGNATED_INITIALIZER;
/// The amount-only case, which is every checkout that does not show a cart breakdown.
- (nonnull instancetype)initWithAmount:(NSString * _Nonnull)amount currencyCode:(NSString * _Nonnull)currencyCode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Objective-C companion for <code>PazeTravelData</code>.
SWIFT_CLASS("_TtC12SpreedlyPaze18PazeTravelDataObjC")
@interface PazeTravelDataObjC : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable passengerName;
@property (nonatomic, readonly, strong) NSNumber * _Nullable roundTrip;
@property (nonatomic, readonly, copy) NSString * _Nullable departureDate;
@property (nonatomic, readonly, copy) NSString * _Nullable returnDate;
@property (nonatomic, readonly, strong) PazeAddress * _Nullable departureLocation;
@property (nonatomic, readonly, strong) PazeAddress * _Nullable returnLocation;
- (nonnull instancetype)initWithPassengerName:(NSString * _Nullable)passengerName roundTrip:(NSNumber * _Nullable)roundTrip departureDate:(NSString * _Nullable)departureDate returnDate:(NSString * _Nullable)returnDate departureLocation:(PazeAddress * _Nullable)departureLocation returnLocation:(PazeAddress * _Nullable)returnLocation OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Paze checkout use case. Official create currently documents <code>RMG</code> only.
typedef SWIFT_ENUM(NSInteger, PazeUseCase, open) {
  PazeUseCaseRmg = 0,
};

@class NSCoder;
@class UITraitCollection;
IB_DESIGNABLE
SWIFT_CLASS("_TtC12SpreedlyPaze22SpreedlyPazeButtonView")
@interface SpreedlyPazeButtonView : UIButton
/// Which label artwork the button renders.
@property (nonatomic) enum PazeButtonLabel label;
/// Convenience accessor for <code>style.color</code>.
@property (nonatomic) enum PazeButtonColor color;
/// Convenience accessor for <code>style.shape</code>.
@property (nonatomic) enum PazeButtonShape shape;
/// Invoked on tap. The button only reports the tap – it never starts a checkout itself, so a
/// merchant stays in control of when the wallet opens.
@property (nonatomic, copy) void (^ _Nullable onTap)(void);
/// Storyboard-only label name. Use <code>label</code> in code.
/// Accepts <code>checkoutWith</code>, <code>checkout</code>, <code>pazeCheckout</code>, <code>donateWith</code>.
@property (nonatomic, copy) IBInspectable NSString * _Nonnull previewLabel;
/// Storyboard-only colour name. Use <code>color</code> in code.
/// Accepts <code>auto</code>, <code>pazeBlue</code>, <code>white</code>, <code>whiteWithOutline</code>, <code>midnightBlack</code>.
@property (nonatomic, copy) IBInspectable NSString * _Nonnull previewColor;
/// Storyboard-only shape name. Use <code>shape</code> in code.
/// Accepts <code>default</code>, <code>rectangle</code>, <code>pill</code>.
@property (nonatomic, copy) IBInspectable NSString * _Nonnull previewShape;
- (nonnull instancetype)initWithLabel:(enum PazeButtonLabel)label color:(enum PazeButtonColor)color shape:(enum PazeButtonShape)shape onTap:(void (^ _Nullable)(void))onTap OBJC_DESIGNATED_INITIALIZER;
/// Storyboard and XIB entry point. Previously unavailable, which blocked storyboard use
/// outright.
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previous SWIFT_AVAILABILITY(ios,introduced=16.0,deprecated=17.0);
/// A blocked device must not show a payment affordance at all, and an impression is only worth
/// reporting once the button is actually on screen.
/// One impression per appearance, not per instance. Leaving the window clears the flag, so a
/// button the merchant shows again – a second visit to the cart, a screen popped and pushed –
/// reports a second impression. SwiftUI and UIKit both reuse the view object across updates, so
/// latching on the instance would report only the first time a shopper ever saw it.
/// “Shown” means attached to a window. A button scrolled out of the viewport stays attached and
/// is not re-reported when it scrolls back.
- (void)didMoveToWindow;
/// Minimum width and fixed height, matching Paze’s shipped sample.
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UIViewController;
SWIFT_CLASS("_TtC12SpreedlyPaze20SpreedlyPazeCheckout")
@interface SpreedlyPazeCheckout : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, weak) id <PazeDelegate> _Nullable delegate;)
+ (id <PazeDelegate> _Nullable)delegate SWIFT_WARN_UNUSED_RESULT;
+ (void)setDelegate:(id <PazeDelegate> _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isActive;)
+ (BOOL)isActive SWIFT_WARN_UNUSED_RESULT;
/// Objective-C configuration entry point.
/// Swift’s <code>throws</code> surfaces to Objective-C as an <code>NSError</code> out-parameter, so the selector is
/// <code>configureWithConfig:error:</code>.
+ (BOOL)configureWithConfig:(PazeConfigObjC * _Nonnull)config error:(NSError * _Nullable * _Nullable)error;
/// Objective-C checkout entry point, presenting from the topmost view controller.
+ (void)presentWithRequest:(PazeCheckoutRequestObjC * _Nonnull)request;
/// Objective-C checkout entry point with an explicit presenting view controller.
+ (void)presentWithRequest:(PazeCheckoutRequestObjC * _Nonnull)request fromViewController:(UIViewController * _Nullable)viewController;
+ (void)confirm;
+ (void)cancel;
/// Non-<code>nil</code> only when a wallet flow was killed with the process mid-checkout – never set for
/// an in-app cancel, failure, or completion.
/// Reading it clears the marker, so an interrupted checkout is reported once and not on every
/// subsequent launch. Call it at startup and tell the shopper their last checkout did not
/// finish; nothing was charged.
+ (PazeAbandonedSession * _Nullable)consumeAbandonedSession;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURL;
IB_DESIGNABLE
SWIFT_CLASS("_TtC12SpreedlyPaze19SpreedlyPazeMessage")
@interface SpreedlyPazeMessage : UIView
/// Storyboard-only message HTML. Use <code>setMessage(html:style:darkMode:onLinkTap:)</code> in code.
@property (nonatomic, copy) IBInspectable NSString * _Nullable previewHtml;
/// Storyboard-only style name: <code>standard</code>, <code>filled</code>, or <code>outlined</code>.
@property (nonatomic, copy) IBInspectable NSString * _Nonnull previewStyle;
/// Storyboard-only dark-mode override.
@property (nonatomic) IBInspectable BOOL previewDark;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
/// Objective-C entry point for <code>setMessage(html:style:darkMode:onLinkTap:)</code>.
/// The Swift method cannot be exposed directly: its <code>darkMode</code> is a <code>Bool?</code>, and an optional
/// value type has no Objective-C representation, which excludes the whole selector from the
/// generated header. <code>NSNumber?</code> carries the same three states – pass <code>nil</code> to follow the
/// system appearance, or a boolean number to force one.
- (void)setMessageWithHTML:(NSString * _Nullable)html style:(enum PazeMessageStyle)style darkMode:(NSNumber * _Nullable)darkMode onLinkTap:(void (^ _Nullable)(NSURL * _Nonnull))onLinkTap;
/// The HTML most recently passed to <code>setMessage(html:style:darkMode:onLinkTap:)</code>, or <code>nil</code>
/// when the message is cleared. Lets a caller re-render or inspect without keeping their own
/// copy alongside the view’s.
- (NSString * _Nullable)getMessage SWIFT_WARN_UNUSED_RESULT;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
/// Manual height computation for callers not using Auto Layout end-to-end.
/// Reported so Auto Layout and SwiftUI can size the view from its content. Without this the
/// only height signal was an internal constraint measured against a fallback width, which
/// clipped the last line whenever the real width differed.
@property (nonatomic, readonly) CGSize intrinsicContentSize;
/// Re-measure once the real width is known. <code>setMessage</code> often runs before layout, when the
/// view still has zero width.
- (void)layoutSubviews;
- (CGFloat)measuredHeightFor:(CGFloat)width SWIFT_WARN_UNUSED_RESULT;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
@end

@class UITextView;
@interface SpreedlyPazeMessage (SWIFT_EXTENSION(SpreedlyPaze)) <UITextViewDelegate>
- (BOOL)textView:(UITextView * _Nonnull)textView shouldInteractWithURL:(NSURL * _Nonnull)url inRange:(NSRange)characterRange interaction:(UITextItemInteraction)interaction SWIFT_WARN_UNUSED_RESULT;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
