#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef SPREEDLYUI_SWIFT_H
#define SPREEDLYUI_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import SafariServices;
@import SpreedlyCore;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SpreedlyUI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

enum DropInNameDisplayMode : NSInteger;
@class NSString;
/// Configuration for which optional fields appear in the bank account form.
/// The Spreedly API requires <code>bank_routing_number</code>, <code>bank_account_number</code>, and a name
/// (either <code>full_name</code> or <code>first_name</code>/<code>last_name</code>). Everything else is optional and
/// gateway-dependent. This config controls which optional fields the form renders.
SWIFT_CLASS("_TtC10SpreedlyUI22BankAccountFieldConfig")
@interface BankAccountFieldConfig : NSObject
/// Whether to show a single “Full Name” field or separate “First Name” / “Last Name” fields.
/// Defaults to <code>.singleField</code>.
@property (nonatomic, readonly) enum DropInNameDisplayMode nameDisplayMode;
/// Whether to show the bank name text field. Off by default — most gateways do
/// not require this attribute, so we ship the smaller form by default.
@property (nonatomic, readonly) BOOL showBankName;
/// Custom label for the bank name field. <code>nil</code> uses the default localized title.
@property (nonatomic, readonly, copy) NSString * _Nullable bankNameLabel;
/// Whether bank name is required for validation. Defaults to optional.
@property (nonatomic, readonly) BOOL bankNameRequired;
/// Whether to show the account type segmented control (checking/savings).
@property (nonatomic, readonly) BOOL showAccountType;
/// Custom label for the account type section. <code>nil</code> uses the default localized title.
@property (nonatomic, readonly, copy) NSString * _Nullable accountTypeLabel;
/// Whether to show the account holder type segmented control (personal/business).
@property (nonatomic, readonly) BOOL showAccountHolderType;
/// Custom label for the account holder type section. <code>nil</code> uses the default localized title.
@property (nonatomic, readonly, copy) NSString * _Nullable accountHolderTypeLabel;
- (nonnull instancetype)initWithNameDisplayMode:(enum DropInNameDisplayMode)nameDisplayMode showBankName:(BOOL)showBankName bankNameLabel:(NSString * _Nullable)bankNameLabel bankNameRequired:(BOOL)bankNameRequired showAccountType:(BOOL)showAccountType accountTypeLabel:(NSString * _Nullable)accountTypeLabel showAccountHolderType:(BOOL)showAccountHolderType accountHolderTypeLabel:(NSString * _Nullable)accountHolderTypeLabel OBJC_DESIGNATED_INITIALIZER;
/// Default: full name, account type + holder type shown, no bank name.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) BankAccountFieldConfig * _Nonnull default_;)
+ (BankAccountFieldConfig * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
/// Minimal: just the required text fields + secure fields (no segmented controls, no bank name).
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) BankAccountFieldConfig * _Nonnull minimal;)
+ (BankAccountFieldConfig * _Nonnull)minimal SWIFT_WARN_UNUSED_RESULT;
/// Full: all fields including bank name and both segmented controls.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) BankAccountFieldConfig * _Nonnull full;)
+ (BankAccountFieldConfig * _Nonnull)full SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PaymentProcessingResult;
@class NSBundle;
@class SPLThemeConfig;
@class NSCoder;
/// UIKit wrapper around <code>BankAccountFormDropIn</code>. Embed in a navigation controller
/// or present modally; mirrors <code>CardFormDropInViewController</code>.
SWIFT_CLASS("_TtC10SpreedlyUI35BankAccountFormDropInViewController")
@interface BankAccountFormDropInViewController : UIViewController
@property (nonatomic, strong) BankAccountFieldConfig * _Nonnull fieldConfig;
@property (nonatomic, copy) void (^ _Nullable onProcessingResult)(PaymentProcessingResult * _Nonnull);
/// Designated initializer; forwards to <code>UIViewController</code> so storyboard and nib paths still work.
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
/// Convenience initializer using the <code>.default</code> field config and no result callback.
- (nonnull instancetype)init;
/// Initializes with a custom field config and result callback.
- (nonnull instancetype)initWithFieldConfig:(BankAccountFieldConfig * _Nonnull)fieldConfig onProcessingResult:(void (^ _Nullable)(PaymentProcessingResult * _Nonnull))onProcessingResult;
/// Initializes with a custom field config, single theme applied to both color schemes, and result callback.
- (nonnull instancetype)initWithFieldConfig:(BankAccountFieldConfig * _Nonnull)fieldConfig themeConfig:(SPLThemeConfig * _Nullable)themeConfig onProcessingResult:(void (^ _Nullable)(PaymentProcessingResult * _Nonnull))onProcessingResult;
/// Initializes with a custom field config, separate light/dark themes, and result callback.
- (nonnull instancetype)initWithFieldConfig:(BankAccountFieldConfig * _Nonnull)fieldConfig lightThemeConfig:(SPLThemeConfig * _Nullable)lightThemeConfig darkThemeConfig:(SPLThemeConfig * _Nullable)darkThemeConfig onProcessingResult:(void (^ _Nullable)(PaymentProcessingResult * _Nonnull))onProcessingResult;
/// Storyboard-required initializer; not the recommended path.
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
/// Embeds the SwiftUI drop-in inside this view controller; dismisses early when the device fails security checks.
- (void)viewDidLoad;
@end

@protocol FieldTextChangeListener;
/// UIKit wrapper for CVVRecachingView to enable Objective-C integration.
/// Objective-C API for CVV recaching.
SWIFT_CLASS("_TtC10SpreedlyUI26CVVRecachingViewController")
@interface CVVRecachingViewController : UIViewController
@property (nonatomic, copy) NSString * _Nonnull labelText;
@property (nonatomic, copy) NSString * _Nonnull placeholderText;
@property (nonatomic, copy) NSString * _Nonnull buttonText;
@property (nonatomic, copy) NSString * _Nonnull cancelButtonText;
@property (nonatomic, copy) NSString * _Nonnull paymentMethodToken;
@property (nonatomic) BOOL allowBlankName;
@property (nonatomic) BOOL allowExpiredDate;
@property (nonatomic) BOOL allowBlankDate;
@property (nonatomic, copy) void (^ _Nullable onProcessingResult)(PaymentProcessingResult * _Nonnull);
@property (nonatomic, weak) id <FieldTextChangeListener> _Nullable cvvTextChangeListener;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLastFourDigits:(NSString * _Nonnull)lastFourDigits cardType:(NSString * _Nonnull)cardType cardBrand:(NSString * _Nullable)cardBrand paymentMethodToken:(NSString * _Nonnull)paymentMethodToken presentationMode:(NSInteger)presentationMode labelText:(NSString * _Nullable)labelText placeholderText:(NSString * _Nullable)placeholderText buttonText:(NSString * _Nullable)buttonText cancelButtonText:(NSString * _Nullable)cancelButtonText onProcessingResult:(void (^ _Nullable)(PaymentProcessingResult * _Nonnull))onProcessingResult;
- (nonnull instancetype)initWithLastFourDigits:(NSString * _Nonnull)lastFourDigits cardType:(NSString * _Nonnull)cardType cardBrand:(NSString * _Nullable)cardBrand paymentMethodToken:(NSString * _Nonnull)paymentMethodToken presentationMode:(NSInteger)presentationMode labelText:(NSString * _Nullable)labelText placeholderText:(NSString * _Nullable)placeholderText buttonText:(NSString * _Nullable)buttonText cancelButtonText:(NSString * _Nullable)cancelButtonText lightThemeConfig:(SPLThemeConfig * _Nullable)lightThemeConfig darkThemeConfig:(SPLThemeConfig * _Nullable)darkThemeConfig onProcessingResult:(void (^ _Nullable)(PaymentProcessingResult * _Nonnull))onProcessingResult;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
@end

@class DropInCoreFieldLabels;
enum YearFormat : NSInteger;
@class FormField;
@protocol UIViewControllerTransitionCoordinator;
SWIFT_CLASS("_TtC10SpreedlyUI28CardFormDropInViewController")
@interface CardFormDropInViewController : UIViewController
@property (nonatomic, strong) DropInCoreFieldLabels * _Nullable coreFieldLabels;
@property (nonatomic) enum YearFormat yearFormat;
@property (nonatomic) enum DropInNameDisplayMode nameDisplayMode;
@property (nonatomic, copy) void (^ _Nullable onProcessingResult)(PaymentProcessingResult * _Nonnull);
/// PAN display format for the card number field.
/// Setting this also updates <code>cardNumberFormatRawValue</code> — use one or the other, not both.
@property (nonatomic) enum CardNumberFormat cardNumberFormat;
/// Raw value of <code>cardNumberFormat</code>. Kept for backward compatibility — prefer <code>cardNumberFormat</code>.
@property (nonatomic) NSInteger cardNumberFormatRawValue;
@property (nonatomic) BOOL enableAutofill;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithOtherFields:(NSArray<FormField *> * _Nonnull)otherFields yearFormat:(enum YearFormat)yearFormat nameDisplayMode:(enum DropInNameDisplayMode)nameDisplayMode onProcessingResult:(void (^ _Nullable)(PaymentProcessingResult * _Nonnull))onProcessingResult;
- (nonnull instancetype)initWithOtherFields:(NSArray<FormField *> * _Nonnull)otherFields yearFormat:(enum YearFormat)yearFormat nameDisplayMode:(enum DropInNameDisplayMode)nameDisplayMode themeConfig:(SPLThemeConfig * _Nullable)themeConfig onProcessingResult:(void (^ _Nullable)(PaymentProcessingResult * _Nonnull))onProcessingResult;
- (nonnull instancetype)initWithOtherFields:(NSArray<FormField *> * _Nonnull)otherFields yearFormat:(enum YearFormat)yearFormat nameDisplayMode:(enum DropInNameDisplayMode)nameDisplayMode lightThemeConfig:(SPLThemeConfig * _Nullable)lightThemeConfig darkThemeConfig:(SPLThemeConfig * _Nullable)darkThemeConfig onProcessingResult:(void (^ _Nullable)(PaymentProcessingResult * _Nonnull))onProcessingResult;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
/// UIKit / Objective-C path: preserve typed fields before rotation re-presents the embedded SwiftUI drop-in.
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
@end

@class UIPresentationController;
/// UIKit wrapper for DoChallengeIfNeeded to enable Objective-C integration
/// This class is always available regardless of whether Forter3DS is configured.
/// When Forter3DS is not available, the view will display an appropriate message.
SWIFT_CLASS("_TtC10SpreedlyUI33DoChallengeIfNeededViewController")
@interface DoChallengeIfNeededViewController : UIViewController <UIAdaptivePresentationControllerDelegate>
/// Initializes the 3DS Challenge View Controller
/// \param transactionToken Transaction token for status.json API (managed_order_token is fetched internally)
///
/// \param onDismiss Callback when view should be dismissed (e.g., Cancel button or merchant action)
///
- (nonnull instancetype)initWithTransactionToken:(NSString * _Nonnull)transactionToken onDismiss:(void (^ _Nullable)(void))onDismiss OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
/// Convenience initializer for Objective-C compatibility
/// Omits the onDismiss closure parameter for simpler Objective-C usage
/// \param transactionToken Transaction token for status.json API (managed_order_token is fetched internally)
///
- (nonnull instancetype)initWithTransactionToken:(NSString * _Nonnull)transactionToken;
- (void)viewDidLoad;
- (void)presentationControllerDidDismiss:(UIPresentationController * _Nonnull)presentationController;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

/// Optional title and placeholder overrides for core card fields in [CardFormDropIn].
SWIFT_CLASS("_TtC10SpreedlyUI21DropInCoreFieldLabels")
@interface DropInCoreFieldLabels : NSObject
@property (nonatomic, copy) NSString * _Nullable cardNumberTitle;
@property (nonatomic, copy) NSString * _Nullable cardNumberPlaceholder;
@property (nonatomic, copy) NSString * _Nullable cvcTitle;
@property (nonatomic, copy) NSString * _Nullable cvcPlaceholder;
@property (nonatomic, copy) NSString * _Nullable expirationMonthTitle;
@property (nonatomic, copy) NSString * _Nullable expirationMonthPlaceholder;
@property (nonatomic, copy) NSString * _Nullable expirationYearTitle;
@property (nonatomic, copy) NSString * _Nullable expirationYearPlaceholder;
@property (nonatomic, copy) NSString * _Nullable expirationDateTitle;
@property (nonatomic, copy) NSString * _Nullable expirationDatePlaceholder;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Controls whether the card form shows a single “Full Name” field or separate first/last name fields.
typedef SWIFT_ENUM(NSInteger, DropInNameDisplayMode, open) {
  DropInNameDisplayModeSingleField = 0,
  DropInNameDisplayModeSeparateFields = 1,
};

/// Objective-C–friendly listener for per-keystroke <code>SPLTextField/onChange</code>–style updates from drop-ins and <code>SPLTextFieldViewController</code>.
SWIFT_PROTOCOL("_TtP10SpreedlyUI23FieldTextChangeListener_")
@protocol FieldTextChangeListener
/// \param fieldType Which drop-in field emitted the change.
///
/// \param text Plaintext for low-sensitivity fields; AES-GCM ciphertext for <code>FormFieldType/merchantOnChangeUsesCiphertext</code> fields (same rules as <code>SPLTextField/onChange</code>).
///
- (void)onFieldTextChanged:(enum FormFieldType)fieldType text:(NSString * _Nonnull)text;
@end

SWIFT_CLASS("_TtC10SpreedlyUI9FormField")
@interface FormField : NSObject
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id title:(NSString * _Nonnull)title type:(enum FormFieldType)type placeholder:(NSString * _Nullable)placeholder isRequired:(BOOL)isRequired OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Lifecycle of a merchant-safe field-state emission (maps to legacy iframe <code>fieldEvent</code> types where applicable).
typedef SWIFT_ENUM(NSInteger, HostedFieldEventType, open) {
/// User input was accepted (processed value updated).
  HostedFieldEventTypeInput = 0,
/// Field gained focus.
  HostedFieldEventTypeFocus = 1,
/// Field lost focus.
  HostedFieldEventTypeBlur = 2,
/// Validation outcome changed (including combined expiry refresh).
  HostedFieldEventTypeValidation = 3,
/// Card number mask visibility changed (<code>setNumberFormat</code> / <code>toggleMask</code> / controlled <code>panMasked</code>); use [HostedFieldState.isPanMasked].
  HostedFieldEventTypePanMaskChanged = 4,
};

@class NSNumber;
/// Merchant-safe field snapshot (legacy iframe <code>fieldEvent</code> / <code>inputProperties</code> subset; no raw PAN or CVV).
SWIFT_CLASS("_TtC10SpreedlyUI16HostedFieldState")
@interface HostedFieldState : NSObject
/// Which field produced this snapshot.
@property (nonatomic, readonly) enum FormFieldType fieldType;
/// What triggered this snapshot.
@property (nonatomic, readonly) enum HostedFieldEventType eventType;
/// Whether the field has focus at emission time.
@property (nonatomic, readonly) BOOL isFocused;
/// Current validation outcome for this field (includes combined month/year rules where applicable).
@property (nonatomic, readonly) BOOL isValid;
/// Whether the visible (decrypted) value is empty.
@property (nonatomic, readonly) BOOL isEmpty;
/// Detected card brand raw value for card-number fields; otherwise nil. Omits unknown scheme.
@property (nonatomic, readonly, copy) NSString * _Nullable cardSchemeRawValue;
/// Digit count for card number fields (not raw PAN); nil for other types.
@property (nonatomic, readonly, strong) NSNumber * _Nullable numberLength;
/// Digit count for CVV fields; nil for other types.
@property (nonatomic, readonly, strong) NSNumber * _Nullable cvvLength;
/// For card-number fields: <code>true</code> when some or all PAN digits are hidden in the field UI at emit time (<code>.masked</code>); <code>false</code> when all digits are visible (<code>.pretty</code> and <code>.plain</code>). Always <code>true</code> on non-PAN fields — ignore on CVC.
@property (nonatomic, readonly) BOOL isPanMasked;
/// Card number only: PAN layout at emit time (<code>CardNumberFormat</code> raw value); <code>nil</code> for CVC and other fields.
@property (nonatomic, readonly, strong) NSNumber * _Nullable panDisplayFormatRawValue;
/// Card number only: policy mask from hosted display state at emit time (<code>hostedCardDisplayState.panMasked</code>); <code>nil</code> for CVC and other fields.
@property (nonatomic, readonly, strong) NSNumber * _Nullable panDisplayPolicyMasked;
/// Card number only: IIN prefix (6 or 8 digits per scheme); <code>nil</code> when fewer than six digits or on non-PAN fields.
@property (nonatomic, readonly, copy) NSString * _Nullable iin;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Java-friendly listener for [HostedFieldState] updates from [SPLTextFieldViewController] (headless / custom form). [CardFormDropIn] does not expose field-state callbacks.
SWIFT_PROTOCOL("_TtP10SpreedlyUI24HostedFieldStateListener_")
@protocol HostedFieldStateListener
- (void)onFieldStateChanged:(HostedFieldState * _Nonnull)state;
@end

typedef SWIFT_ENUM(NSInteger, OffsiteGateway, open) {
  OffsiteGatewayPaypal = 0,
  OffsiteGatewayStripePaymentIntent = 1,
  OffsiteGatewayPix = 2,
  OffsiteGatewayBoletoBancario = 3,
  OffsiteGatewayNupay = 4,
  OffsiteGatewayOxxo = 5,
  OffsiteGatewaySprel = 6,
};

@class UIView;
enum SpreedlySubmitLabel : NSInteger;
SWIFT_CLASS("_TtC10SpreedlyUI26SPLTextFieldViewController")
@interface SPLTextFieldViewController : UIViewController
@property (nonatomic) enum FormFieldType field;
@property (nonatomic, copy) NSString * _Nullable fieldTitle;
@property (nonatomic) BOOL isRequired;
@property (nonatomic) enum YearFormat yearFormat;
@property (nonatomic, copy) NSString * _Nullable placeholder;
@property (nonatomic) UIKeyboardType keyboardType;
@property (nonatomic) UITextContentType _Nullable textContentType;
@property (nonatomic, copy) void (^ _Nullable onValidationChange)(BOOL);
@property (nonatomic, copy) void (^ _Nullable onSubmit)(void);
/// When <code>true</code>, focuses this field (same as SwiftUI <code>SPLTextField/shouldFocus</code>).
@property (nonatomic) BOOL shouldFocus;
@property (nonatomic, copy) void (^ _Nullable onFocus)(void);
@property (nonatomic, copy) void (^ _Nullable onFocusChanged)(BOOL);
@property (nonatomic, copy) void (^ _Nullable onFieldStateChange)(HostedFieldState * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onInputLength)(NSInteger);
@property (nonatomic, weak) id <HostedFieldStateListener> _Nullable hostedFieldStateListener;
@property (nonatomic, weak) id <FieldTextChangeListener> _Nullable fieldTextChangeListener;
/// When <code>field</code> is the card number type, produces the trailing brand view for the given scheme string (<code>CardType</code>’s <code>rawValue</code>, e.g. <code>"visa"</code>). Use app-bundled artwork.
@property (nonatomic, copy) UIView * _Nonnull (^ _Nullable trailingIconViewFactory)(NSString * _Nonnull);
@property (nonatomic) BOOL forceMaskOnLifecycleStop;
/// When <code>false</code>, suppresses credit-card autofill hints (legacy iframe <code>toggleAutoComplete</code> off).
/// Safe to change after the view loads; the hosted presentation is rebuilt while field values stay in secure storage.
@property (nonatomic) BOOL enableAutofill;
@property (nonatomic, readonly) BOOL isValid;
@property (nonatomic, readonly, copy) NSString * _Nullable errorMessage;
@property (nonatomic, readonly) BOOL hasValue;
@property (nonatomic, readonly) NSInteger inputLength;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithField:(enum FormFieldType)field;
- (nonnull instancetype)initWithField:(enum FormFieldType)field title:(NSString * _Nullable)title isRequired:(BOOL)isRequired;
- (nonnull instancetype)initWithField:(enum FormFieldType)field title:(NSString * _Nullable)title isRequired:(BOOL)isRequired placeholder:(NSString * _Nullable)placeholder keyboardType:(UIKeyboardType)keyboardType textContentType:(UITextContentType _Nullable)textContentType onValidationChange:(void (^ _Nullable)(BOOL))onValidationChange onFocus:(void (^ _Nullable)(void))onFocus;
- (nonnull instancetype)initWithField:(enum FormFieldType)field title:(NSString * _Nullable)title isRequired:(BOOL)isRequired placeholder:(NSString * _Nullable)placeholder keyboardType:(UIKeyboardType)keyboardType textContentType:(UITextContentType _Nullable)textContentType onValidationChange:(void (^ _Nullable)(BOOL))onValidationChange onSubmit:(void (^ _Nullable)(void))onSubmit submitLabel:(enum SpreedlySubmitLabel)submitLabel onFocus:(void (^ _Nullable)(void))onFocus;
- (nonnull instancetype)initWithField:(enum FormFieldType)field title:(NSString * _Nullable)title isRequired:(BOOL)isRequired placeholder:(NSString * _Nullable)placeholder keyboardType:(UIKeyboardType)keyboardType textContentType:(UITextContentType _Nullable)textContentType themeConfig:(SPLThemeConfig * _Nullable)themeConfig onValidationChange:(void (^ _Nullable)(BOOL))onValidationChange onFocus:(void (^ _Nullable)(void))onFocus;
- (nonnull instancetype)initWithField:(enum FormFieldType)field title:(NSString * _Nullable)title isRequired:(BOOL)isRequired placeholder:(NSString * _Nullable)placeholder keyboardType:(UIKeyboardType)keyboardType textContentType:(UITextContentType _Nullable)textContentType lightThemeConfig:(SPLThemeConfig * _Nullable)lightThemeConfig darkThemeConfig:(SPLThemeConfig * _Nullable)darkThemeConfig onValidationChange:(void (^ _Nullable)(BOOL))onValidationChange onFocus:(void (^ _Nullable)(void))onFocus;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)clear;
- (void)reset;
/// Make this text field the first responder (focused)
- (BOOL)becomeFirstResponder SWIFT_WARN_UNUSED_RESULT;
/// Resign first responder (unfocus)
- (BOOL)resignFirstResponder SWIFT_WARN_UNUSED_RESULT;
@end

@class UIColor;
/// Objective-C compatible theme configuration class
/// Bridges UIKit colors to SwiftUI themes for Objective-C callers
SWIFT_CLASS("_TtC10SpreedlyUI14SPLThemeConfig")
@interface SPLThemeConfig : NSObject
@property (nonatomic, strong) UIColor * _Nullable primaryColor;
@property (nonatomic, strong) UIColor * _Nullable secondaryColor;
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
@property (nonatomic, strong) UIColor * _Nullable surfaceColor;
@property (nonatomic, strong) UIColor * _Nullable borderColor;
@property (nonatomic, strong) UIColor * _Nullable borderFocusedColor;
@property (nonatomic, strong) UIColor * _Nullable textColor;
@property (nonatomic, strong) UIColor * _Nullable textSecondaryColor;
@property (nonatomic, strong) UIColor * _Nullable errorColor;
@property (nonatomic, strong) UIColor * _Nullable placeholderColor;
@property (nonatomic) CGFloat borderRadius;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPrimaryColor:(UIColor * _Nullable)primaryColor secondaryColor:(UIColor * _Nullable)secondaryColor backgroundColor:(UIColor * _Nullable)backgroundColor surfaceColor:(UIColor * _Nullable)surfaceColor borderColor:(UIColor * _Nullable)borderColor borderFocusedColor:(UIColor * _Nullable)borderFocusedColor textColor:(UIColor * _Nullable)textColor textSecondaryColor:(UIColor * _Nullable)textSecondaryColor errorColor:(UIColor * _Nullable)errorColor placeholderColor:(UIColor * _Nullable)placeholderColor borderRadius:(CGFloat)borderRadius;
/// Convenience initializer using Android-style configuration
/// \param primaryColorHex Primary brand color used for buttons and highlights (e.g., “#0077C8”)
///
/// \param secondaryColorHex Secondary brand color used for accents and borders (e.g., “#AFB4B5”)
///
/// \param formBorderColorHex Color for form field borders (e.g., “#D9D9D9”)
///
/// \param formBackgroundColorHex Background color for the form container (e.g., “#FFFFFF”)
///
/// \param fieldBackgroundColorHex Background color for individual input fields (e.g., “#F8F9FA”)
///
/// \param fieldLabelColorHex Color for field labels and placeholder text (e.g., “#6C757D”)
///
/// \param borderRadius Corner radius for form elements (default: 8.0)
///
- (nonnull instancetype)initWithPrimaryColorHex:(NSString * _Nonnull)primaryColorHex secondaryColorHex:(NSString * _Nullable)secondaryColorHex formBorderColorHex:(NSString * _Nullable)formBorderColorHex formBackgroundColorHex:(NSString * _Nullable)formBackgroundColorHex fieldBackgroundColorHex:(NSString * _Nullable)fieldBackgroundColorHex fieldLabelColorHex:(NSString * _Nullable)fieldLabelColorHex borderRadius:(CGFloat)borderRadius;
@end

/// This is a public implementation that follows the same pattern as SecureView
/// from the ScreenSecurity folder without directly depending on it
SWIFT_CLASS("_TtC10SpreedlyUI26ScreenPreventionSecureView")
@interface ScreenPreventionSecureView : UIView
/// Toggle to enable or disable secure behavior
@property (nonatomic) BOOL isSecure;
/// Placeholder text to display in screenshots/recordings
@property (nonatomic, copy) NSString * _Nonnull placeholderText;
/// Content view where your views should be added
@property (nonatomic, readonly, strong) UIView * _Null_unspecified contentView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class SFSafariViewController;
/// Presents SFSafariViewController directly on the topmost VC.
/// SDK fetches checkout_url via status API, presents Safari, and
/// publishes PaymentResult when the user finishes or returns via redirect.
SWIFT_CLASS("_TtC10SpreedlyUI23SpreedlyOffsiteCheckout")
@interface SpreedlyOffsiteCheckout : NSObject <SFSafariViewControllerDelegate>
+ (void)presentWithTransactionToken:(NSString * _Nonnull)transactionToken;
- (void)safariViewControllerDidFinish:(SFSafariViewController * _Nonnull)controller;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Custom submit label enum that maps to SubmitLabel on iOS 15+
typedef SWIFT_ENUM(NSInteger, SpreedlySubmitLabel, open) {
  SpreedlySubmitLabelReturn = 0,
  SpreedlySubmitLabelDone = 1,
  SpreedlySubmitLabelGo = 2,
  SpreedlySubmitLabelSearch = 3,
  SpreedlySubmitLabelSend = 4,
  SpreedlySubmitLabelNext = 5,
  SpreedlySubmitLabelJoin = 6,
  SpreedlySubmitLabelRoute = 7,
  SpreedlySubmitLabelContinue = 8,
};

/// Objective-C compatible theme manager
/// Objective-C API for theme management
SWIFT_CLASS("_TtC10SpreedlyUI24SpreedlyThemeManagerObjC")
@interface SpreedlyThemeManagerObjC : NSObject
/// Set global theme with separate light and dark themes using SPLThemeConfig
/// \param lightThemeConfig The theme configuration for light mode
///
/// \param darkThemeConfig The theme configuration for dark mode
///
+ (void)setGlobalThemeWithLightConfig:(SPLThemeConfig * _Nonnull)lightThemeConfig darkConfig:(SPLThemeConfig * _Nonnull)darkConfig;
/// Set global theme using SPLThemeConfig (backward compatibility - uses same theme for both modes)
/// \param themeConfig The theme configuration to set as global (used for both light and dark modes)
///
+ (void)setGlobalThemeWithConfig:(SPLThemeConfig * _Nonnull)themeConfig;
/// Set global theme with separate light and dark themes using Android-style hex color configuration
/// \param lightPrimaryColorHex Primary brand color for light mode (e.g., “#0077C8”)
///
/// \param lightSecondaryColorHex Secondary brand color for light mode (e.g., “#AFB4B5”)
///
/// \param lightFormBorderColorHex Form field border color for light mode (e.g., “#D9D9D9”)
///
/// \param lightFormBackgroundColorHex Form background color for light mode (e.g., “#FFFFFF”)
///
/// \param lightFieldBackgroundColorHex Field background color for light mode (e.g., “#F8F9FA”)
///
/// \param lightFieldLabelColorHex Field label color for light mode (e.g., “#6C757D”)
///
/// \param darkPrimaryColorHex Primary brand color for dark mode (e.g., “#00A0FF”)
///
/// \param darkSecondaryColorHex Secondary brand color for dark mode (e.g., “#6C757D”)
///
/// \param darkFormBorderColorHex Form field border color for dark mode (e.g., “#4A4A4A”)
///
/// \param darkFormBackgroundColorHex Form background color for dark mode (e.g., “#1C1C1E”)
///
/// \param darkFieldBackgroundColorHex Field background color for dark mode (e.g., “#2C2C2E”)
///
/// \param darkFieldLabelColorHex Field label color for dark mode (e.g., “#AEAEB2”)
///
/// \param borderRadius Corner radius for form elements (default: 8.0)
///
+ (void)setGlobalThemeWithLightHexColorsWithLightPrimaryColorHex:(NSString * _Nonnull)lightPrimaryColorHex lightSecondaryColorHex:(NSString * _Nullable)lightSecondaryColorHex lightFormBorderColorHex:(NSString * _Nullable)lightFormBorderColorHex lightFormBackgroundColorHex:(NSString * _Nullable)lightFormBackgroundColorHex lightFieldBackgroundColorHex:(NSString * _Nullable)lightFieldBackgroundColorHex lightFieldLabelColorHex:(NSString * _Nullable)lightFieldLabelColorHex darkPrimaryColorHex:(NSString * _Nonnull)darkPrimaryColorHex darkSecondaryColorHex:(NSString * _Nullable)darkSecondaryColorHex darkFormBorderColorHex:(NSString * _Nullable)darkFormBorderColorHex darkFormBackgroundColorHex:(NSString * _Nullable)darkFormBackgroundColorHex darkFieldBackgroundColorHex:(NSString * _Nullable)darkFieldBackgroundColorHex darkFieldLabelColorHex:(NSString * _Nullable)darkFieldLabelColorHex borderRadius:(CGFloat)borderRadius;
/// Set global theme using Android-style hex color configuration (backward compatibility - uses same theme for both modes)
/// \param primaryColorHex Primary brand color (e.g., “#0077C8”)
///
/// \param secondaryColorHex Secondary brand color (e.g., “#AFB4B5”)
///
/// \param formBorderColorHex Form field border color (e.g., “#D9D9D9”)
///
/// \param formBackgroundColorHex Form background color (e.g., “#FFFFFF”)
///
/// \param fieldBackgroundColorHex Field background color (e.g., “#F8F9FA”)
///
/// \param fieldLabelColorHex Field label color (e.g., “#6C757D”)
///
/// \param borderRadius Corner radius for form elements (default: 8.0)
///
+ (void)setGlobalThemeWithHexColorsWithPrimaryColorHex:(NSString * _Nonnull)primaryColorHex secondaryColorHex:(NSString * _Nullable)secondaryColorHex formBorderColorHex:(NSString * _Nullable)formBorderColorHex formBackgroundColorHex:(NSString * _Nullable)formBackgroundColorHex fieldBackgroundColorHex:(NSString * _Nullable)fieldBackgroundColorHex fieldLabelColorHex:(NSString * _Nullable)fieldLabelColorHex borderRadius:(CGFloat)borderRadius;
/// Set global theme with separate light and dark themes using UIColor properties
/// \param lightPrimaryColor Primary brand color for light mode
///
/// \param lightSecondaryColor Secondary brand color for light mode (optional)
///
/// \param lightBackgroundColor Background color for light mode (optional)
///
/// \param lightBorderColor Border color for light mode (optional)
///
/// \param lightTextColor Text color for light mode (optional)
///
/// \param darkPrimaryColor Primary brand color for dark mode
///
/// \param darkSecondaryColor Secondary brand color for dark mode (optional)
///
/// \param darkBackgroundColor Background color for dark mode (optional)
///
/// \param darkBorderColor Border color for dark mode (optional)
///
/// \param darkTextColor Text color for dark mode (optional)
///
/// \param borderRadius Corner radius (default: 8.0)
///
+ (void)setGlobalThemeWithLightColorsWithLightPrimaryColor:(UIColor * _Nonnull)lightPrimaryColor lightSecondaryColor:(UIColor * _Nullable)lightSecondaryColor lightBackgroundColor:(UIColor * _Nullable)lightBackgroundColor lightBorderColor:(UIColor * _Nullable)lightBorderColor lightTextColor:(UIColor * _Nullable)lightTextColor darkPrimaryColor:(UIColor * _Nonnull)darkPrimaryColor darkSecondaryColor:(UIColor * _Nullable)darkSecondaryColor darkBackgroundColor:(UIColor * _Nullable)darkBackgroundColor darkBorderColor:(UIColor * _Nullable)darkBorderColor darkTextColor:(UIColor * _Nullable)darkTextColor borderRadius:(CGFloat)borderRadius;
/// Set global theme using UIColor properties (backward compatibility - uses same theme for both modes)
/// \param primaryColor Primary brand color
///
/// \param secondaryColor Secondary brand color (optional)
///
/// \param backgroundColor Background color (optional)
///
/// \param borderColor Border color (optional)
///
/// \param textColor Text color (optional)
///
/// \param borderRadius Corner radius (default: 8.0)
///
+ (void)setGlobalThemeWithColorsWithPrimaryColor:(UIColor * _Nonnull)primaryColor secondaryColor:(UIColor * _Nullable)secondaryColor backgroundColor:(UIColor * _Nullable)backgroundColor borderColor:(UIColor * _Nullable)borderColor textColor:(UIColor * _Nullable)textColor borderRadius:(CGFloat)borderRadius;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface SpreedlyUIManager (SWIFT_EXTENSION(SpreedlyUI))
/// <code>YearFormat</code> from the registered <code>FormFieldType/expirationYear</code> field (used when splitting <code>MM/YY</code> autofill on the month field).
@property (nonatomic, readonly) enum YearFormat separatedExpirationYearFormat;
/// Called when an <code>FormFieldType/expirationYear</code> <code>SPLTextField</code> appears or its format changes.
- (void)updateSeparatedExpirationYearFormat:(enum YearFormat)format;
@end

@interface UIViewController (SWIFT_EXTENSION(SpreedlyUI))
/// Wrap this view controller in a secure container (similar to SwiftUI’s .screenPrevention())
/// Automatically starts manager protection for app switcher overlay
/// \param placeholderText Optional text to display in screenshots/recordings (default: “”)
///
///
/// returns:
/// A container view controller with secure protection applied
- (UIViewController * _Nonnull)wrapInSecureViewControllerWithPlaceholderText:(NSString * _Nonnull)placeholderText SWIFT_WARN_UNUSED_RESULT;
@end

/// Whether the expiration year field shows 2-digit (YY) or 4-digit (YYYY) format.
typedef SWIFT_ENUM(NSInteger, YearFormat, open) {
  YearFormatTwoDigit = 2,
  YearFormatFourDigit = 4,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
