#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef SPREEDLYUI_SWIFT_H
#define SPREEDLYUI_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import SafariServices;
@import SpreedlyCore;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SpreedlyUI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSURL;
/// Objective-C compatible wrapper for Braintree URL handling.
/// Call handleOpenWithUrl: from your URL handler (e.g. scene:openURLContexts: or application:open:options:).
SWIFT_CLASS("_TtC10SpreedlyUI23BraintreeURLHandlerObjC")
@interface BraintreeURLHandlerObjC : NSObject
/// Forwards a URL to the Braintree SDK for app-switch handling.
/// Call from your app’s URL handler (e.g. scene:openURLContexts: or application:open:options:).
///
/// returns:
/// YES if the URL was handled by Braintree, NO otherwise.
+ (BOOL)handleOpenWithUrl:(NSURL * _Nonnull)url SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;
@class PaymentProcessingResult;
@class NSBundle;
@class SPLThemeConfig;
@class NSCoder;
/// UIKit wrapper for CVVRecachingView to enable Objective-C integration.
/// Provides Objective-C compatible API for CVV recaching functionality.
SWIFT_CLASS("_TtC10SpreedlyUI26CVVRecachingViewController")
@interface CVVRecachingViewController : UIViewController
@property (nonatomic, copy) NSString * _Nonnull labelText;
@property (nonatomic, copy) NSString * _Nonnull placeholderText;
@property (nonatomic, copy) NSString * _Nonnull buttonText;
@property (nonatomic, copy) NSString * _Nonnull cancelButtonText;
@property (nonatomic, copy) NSString * _Nonnull paymentMethodToken;
@property (nonatomic) BOOL allowBlankName;
@property (nonatomic) BOOL allowExpiredDate;
@property (nonatomic) BOOL allowBlankDate;
@property (nonatomic, copy) void (^ _Nullable onProcessingResult)(PaymentProcessingResult * _Nonnull);
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLastFourDigits:(NSString * _Nonnull)lastFourDigits cardType:(NSString * _Nonnull)cardType cardBrand:(NSString * _Nullable)cardBrand paymentMethodToken:(NSString * _Nonnull)paymentMethodToken presentationMode:(NSInteger)presentationMode labelText:(NSString * _Nullable)labelText placeholderText:(NSString * _Nullable)placeholderText buttonText:(NSString * _Nullable)buttonText cancelButtonText:(NSString * _Nullable)cancelButtonText onProcessingResult:(void (^ _Nullable)(PaymentProcessingResult * _Nonnull))onProcessingResult;
- (nonnull instancetype)initWithLastFourDigits:(NSString * _Nonnull)lastFourDigits cardType:(NSString * _Nonnull)cardType cardBrand:(NSString * _Nullable)cardBrand paymentMethodToken:(NSString * _Nonnull)paymentMethodToken presentationMode:(NSInteger)presentationMode labelText:(NSString * _Nullable)labelText placeholderText:(NSString * _Nullable)placeholderText buttonText:(NSString * _Nullable)buttonText cancelButtonText:(NSString * _Nullable)cancelButtonText lightThemeConfig:(SPLThemeConfig * _Nullable)lightThemeConfig darkThemeConfig:(SPLThemeConfig * _Nullable)darkThemeConfig onProcessingResult:(void (^ _Nullable)(PaymentProcessingResult * _Nonnull))onProcessingResult;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
@end

enum YearFormat : NSInteger;
enum DropInNameDisplayMode : NSInteger;
@class FormField;
SWIFT_CLASS("_TtC10SpreedlyUI28CardFormDropInViewController")
@interface CardFormDropInViewController : UIViewController
@property (nonatomic) enum YearFormat yearFormat;
@property (nonatomic) enum DropInNameDisplayMode nameDisplayMode;
@property (nonatomic, copy) void (^ _Nullable onProcessingResult)(PaymentProcessingResult * _Nonnull);
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithOtherFields:(NSArray<FormField *> * _Nonnull)otherFields yearFormat:(enum YearFormat)yearFormat nameDisplayMode:(enum DropInNameDisplayMode)nameDisplayMode onProcessingResult:(void (^ _Nullable)(PaymentProcessingResult * _Nonnull))onProcessingResult;
- (nonnull instancetype)initWithOtherFields:(NSArray<FormField *> * _Nonnull)otherFields yearFormat:(enum YearFormat)yearFormat nameDisplayMode:(enum DropInNameDisplayMode)nameDisplayMode themeConfig:(SPLThemeConfig * _Nullable)themeConfig onProcessingResult:(void (^ _Nullable)(PaymentProcessingResult * _Nonnull))onProcessingResult;
- (nonnull instancetype)initWithOtherFields:(NSArray<FormField *> * _Nonnull)otherFields yearFormat:(enum YearFormat)yearFormat nameDisplayMode:(enum DropInNameDisplayMode)nameDisplayMode lightThemeConfig:(SPLThemeConfig * _Nullable)lightThemeConfig darkThemeConfig:(SPLThemeConfig * _Nullable)darkThemeConfig onProcessingResult:(void (^ _Nullable)(PaymentProcessingResult * _Nonnull))onProcessingResult;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
@end

@class UIPresentationController;
/// UIKit wrapper for DoChallengeIfNeeded to enable Objective-C integration
/// This class is always available regardless of whether Forter3DS is configured.
/// When Forter3DS is not available, the view will display an appropriate message.
SWIFT_CLASS("_TtC10SpreedlyUI33DoChallengeIfNeededViewController")
@interface DoChallengeIfNeededViewController : UIViewController <UIAdaptivePresentationControllerDelegate>
/// Initializes the 3DS Challenge View Controller
/// \param transactionToken Transaction token for status.json API (managed_order_token is fetched internally)
///
/// \param onDismiss Callback when view should be dismissed (e.g., Cancel button or merchant action)
///
- (nonnull instancetype)initWithTransactionToken:(NSString * _Nonnull)transactionToken onDismiss:(void (^ _Nullable)(void))onDismiss OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
/// Convenience initializer for Objective-C compatibility
/// Omits the onDismiss closure parameter for simpler Objective-C usage
/// \param transactionToken Transaction token for status.json API (managed_order_token is fetched internally)
///
- (nonnull instancetype)initWithTransactionToken:(NSString * _Nonnull)transactionToken;
- (void)viewDidLoad;
- (void)presentationControllerDidDismiss:(UIPresentationController * _Nonnull)presentationController;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, DropInNameDisplayMode, open) {
  DropInNameDisplayModeSingleField = 0,
  DropInNameDisplayModeSeparateFields = 1,
};

SWIFT_CLASS("_TtC10SpreedlyUI9FormField")
@interface FormField : NSObject
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id title:(NSString * _Nonnull)title type:(enum FormFieldType)type placeholder:(NSString * _Nullable)placeholder isRequired:(BOOL)isRequired OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, OffsiteGateway, open) {
  OffsiteGatewayPaypal = 0,
  OffsiteGatewayStripePaymentIntent = 1,
  OffsiteGatewayPix = 2,
  OffsiteGatewayBoletoBancario = 3,
  OffsiteGatewayNupay = 4,
  OffsiteGatewayNupayRecurrent = 5,
  OffsiteGatewayOxxo = 6,
  OffsiteGatewayRapipago = 7,
  OffsiteGatewaySprel = 8,
};

enum SpreedlySubmitLabel : NSInteger;
SWIFT_CLASS("_TtC10SpreedlyUI26SPLTextFieldViewController")
@interface SPLTextFieldViewController : UIViewController
@property (nonatomic) enum FormFieldType field;
@property (nonatomic, copy) NSString * _Nullable fieldTitle;
@property (nonatomic) BOOL isRequired;
@property (nonatomic) enum YearFormat yearFormat;
@property (nonatomic, copy) NSString * _Nullable placeholder;
@property (nonatomic) UIKeyboardType keyboardType;
@property (nonatomic) UITextContentType _Nullable textContentType;
@property (nonatomic, copy) void (^ _Nullable onValidationChange)(BOOL);
@property (nonatomic, copy) void (^ _Nullable onSubmit)(void);
@property (nonatomic) BOOL shouldFocus;
@property (nonatomic, copy) void (^ _Nullable onFocus)(void);
@property (nonatomic, readonly) BOOL isValid;
@property (nonatomic, readonly, copy) NSString * _Nullable errorMessage;
@property (nonatomic, readonly) BOOL hasValue;
@property (nonatomic, readonly) NSInteger inputLength;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithField:(enum FormFieldType)field;
- (nonnull instancetype)initWithField:(enum FormFieldType)field title:(NSString * _Nullable)title isRequired:(BOOL)isRequired;
- (nonnull instancetype)initWithField:(enum FormFieldType)field title:(NSString * _Nullable)title isRequired:(BOOL)isRequired placeholder:(NSString * _Nullable)placeholder keyboardType:(UIKeyboardType)keyboardType textContentType:(UITextContentType _Nullable)textContentType onValidationChange:(void (^ _Nullable)(BOOL))onValidationChange onFocus:(void (^ _Nullable)(void))onFocus;
- (nonnull instancetype)initWithField:(enum FormFieldType)field title:(NSString * _Nullable)title isRequired:(BOOL)isRequired placeholder:(NSString * _Nullable)placeholder keyboardType:(UIKeyboardType)keyboardType textContentType:(UITextContentType _Nullable)textContentType onValidationChange:(void (^ _Nullable)(BOOL))onValidationChange onSubmit:(void (^ _Nullable)(void))onSubmit submitLabel:(enum SpreedlySubmitLabel)submitLabel onFocus:(void (^ _Nullable)(void))onFocus;
- (nonnull instancetype)initWithField:(enum FormFieldType)field title:(NSString * _Nullable)title isRequired:(BOOL)isRequired placeholder:(NSString * _Nullable)placeholder keyboardType:(UIKeyboardType)keyboardType textContentType:(UITextContentType _Nullable)textContentType themeConfig:(SPLThemeConfig * _Nullable)themeConfig onValidationChange:(void (^ _Nullable)(BOOL))onValidationChange onFocus:(void (^ _Nullable)(void))onFocus;
- (nonnull instancetype)initWithField:(enum FormFieldType)field title:(NSString * _Nullable)title isRequired:(BOOL)isRequired placeholder:(NSString * _Nullable)placeholder keyboardType:(UIKeyboardType)keyboardType textContentType:(UITextContentType _Nullable)textContentType lightThemeConfig:(SPLThemeConfig * _Nullable)lightThemeConfig darkThemeConfig:(SPLThemeConfig * _Nullable)darkThemeConfig onValidationChange:(void (^ _Nullable)(BOOL))onValidationChange onFocus:(void (^ _Nullable)(void))onFocus;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)clear;
- (void)reset;
/// Make this text field the first responder (focused)
- (BOOL)becomeFirstResponder SWIFT_WARN_UNUSED_RESULT;
/// Resign first responder (unfocus)
- (BOOL)resignFirstResponder SWIFT_WARN_UNUSED_RESULT;
@end

@class UIColor;
/// Objective-C compatible theme configuration class
/// Provides a bridge between UIKit colors and SwiftUI themes
SWIFT_CLASS("_TtC10SpreedlyUI14SPLThemeConfig")
@interface SPLThemeConfig : NSObject
@property (nonatomic, strong) UIColor * _Nullable primaryColor;
@property (nonatomic, strong) UIColor * _Nullable secondaryColor;
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
@property (nonatomic, strong) UIColor * _Nullable surfaceColor;
@property (nonatomic, strong) UIColor * _Nullable borderColor;
@property (nonatomic, strong) UIColor * _Nullable borderFocusedColor;
@property (nonatomic, strong) UIColor * _Nullable textColor;
@property (nonatomic, strong) UIColor * _Nullable textSecondaryColor;
@property (nonatomic, strong) UIColor * _Nullable errorColor;
@property (nonatomic, strong) UIColor * _Nullable placeholderColor;
@property (nonatomic) CGFloat borderRadius;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPrimaryColor:(UIColor * _Nullable)primaryColor secondaryColor:(UIColor * _Nullable)secondaryColor backgroundColor:(UIColor * _Nullable)backgroundColor surfaceColor:(UIColor * _Nullable)surfaceColor borderColor:(UIColor * _Nullable)borderColor borderFocusedColor:(UIColor * _Nullable)borderFocusedColor textColor:(UIColor * _Nullable)textColor textSecondaryColor:(UIColor * _Nullable)textSecondaryColor errorColor:(UIColor * _Nullable)errorColor placeholderColor:(UIColor * _Nullable)placeholderColor borderRadius:(CGFloat)borderRadius;
/// Convenience initializer using Android-style configuration
/// \param primaryColorHex Primary brand color used for buttons and highlights (e.g., “#0077C8”)
///
/// \param secondaryColorHex Secondary brand color used for accents and borders (e.g., “#AFB4B5”)
///
/// \param formBorderColorHex Color for form field borders (e.g., “#D9D9D9”)
///
/// \param formBackgroundColorHex Background color for the form container (e.g., “#FFFFFF”)
///
/// \param fieldBackgroundColorHex Background color for individual input fields (e.g., “#F8F9FA”)
///
/// \param fieldLabelColorHex Color for field labels and placeholder text (e.g., “#6C757D”)
///
/// \param borderRadius Corner radius for form elements (default: 8.0)
///
- (nonnull instancetype)initWithPrimaryColorHex:(NSString * _Nonnull)primaryColorHex secondaryColorHex:(NSString * _Nullable)secondaryColorHex formBorderColorHex:(NSString * _Nullable)formBorderColorHex formBackgroundColorHex:(NSString * _Nullable)formBackgroundColorHex fieldBackgroundColorHex:(NSString * _Nullable)fieldBackgroundColorHex fieldLabelColorHex:(NSString * _Nullable)fieldLabelColorHex borderRadius:(CGFloat)borderRadius;
@end

/// This is a public implementation that follows the same pattern as SecureView
/// from the ScreenSecurity folder without directly depending on it
SWIFT_CLASS("_TtC10SpreedlyUI26ScreenPreventionSecureView")
@interface ScreenPreventionSecureView : UIView
/// Toggle to enable or disable secure behavior
@property (nonatomic) BOOL isSecure;
/// Placeholder text to display in screenshots/recordings
@property (nonatomic, copy) NSString * _Nonnull placeholderText;
/// Content view where your views should be added
@property (nonatomic, readonly, strong) UIView * _Null_unspecified contentView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class BraintreeCheckoutConfig;
SWIFT_CLASS("_TtC10SpreedlyUI25SpreedlyBraintreeCheckout")
@interface SpreedlyBraintreeCheckout : NSObject
/// <code>true</code> when Braintree SDK is linked and Braintree checkout can be used.
/// Optional: use this to show/hide Braintree UI. You can instead call <code>present(config:)</code>
/// directly; when Braintree is not linked, a failure will be published to the payment result.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isAvailable;)
+ (BOOL)isAvailable SWIFT_WARN_UNUSED_RESULT;
/// Whether a Braintree checkout is currently in progress.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isActive;)
+ (BOOL)isActive SWIFT_WARN_UNUSED_RESULT;
/// The transaction token of the active checkout, if any.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable currentTransactionToken;)
+ (NSString * _Nullable)currentTransactionToken SWIFT_WARN_UNUSED_RESULT;
/// Presents the Braintree PayPal or Venmo flow from the topmost view controller.
/// Result is delivered via <code>Spreedly.shared().paymentResultPublisher</code>.
/// When Braintree is not linked, publishes a failure (no-op presentation).
+ (void)presentWithConfig:(BraintreeCheckoutConfig * _Nonnull)config;
/// Presents the Braintree PayPal or Venmo flow from the given view controller.
+ (void)presentWithConfig:(BraintreeCheckoutConfig * _Nonnull)config from:(UIViewController * _Nonnull)viewController;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class SFSafariViewController;
/// Presents SFSafariViewController directly on the topmost VC.
/// SDK fetches checkout_url via status API, presents Safari, and
/// publishes PaymentResult when the user finishes or returns via redirect.
SWIFT_CLASS("_TtC10SpreedlyUI23SpreedlyOffsiteCheckout")
@interface SpreedlyOffsiteCheckout : NSObject <SFSafariViewControllerDelegate>
/// Fetches the checkout URL for the given transaction and presents
/// SFSafariViewController directly on the topmost view controller.
/// Result is delivered via <code>Spreedly.shared().paymentResultPublisher</code>
/// (or the <code>SpreedlyPaymentDelegate</code> for Obj-C).
+ (void)presentWithTransactionToken:(NSString * _Nonnull)transactionToken;
- (void)safariViewControllerDidFinish:(SFSafariViewController * _Nonnull)controller;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class StripeAPMConfig;
SWIFT_CLASS("_TtC10SpreedlyUI25SpreedlyStripeAPMCheckout")
@interface SpreedlyStripeAPMCheckout : NSObject
/// Called from the URL pre-handler when the app is opened via the Stripe return URL.
/// Notifies Spreedly (GET redirect URL) so Spreedly can update the transaction, then forwards to Stripe.
+ (BOOL)handleStripeReturnURL:(NSURL * _Nonnull)url SWIFT_WARN_UNUSED_RESULT;
/// Presents the Stripe PaymentSheet for APM checkout from the topmost view controller
/// (same approach as <code>SpreedlyOffsiteCheckout.present(transactionToken:)</code>).
/// Use this from SwiftUI or when you do not have a specific presenter.
/// Result is delivered via <code>Spreedly.shared().paymentResultPublisher</code>
/// (or the <code>SpreedlyPaymentDelegate</code> for Obj-C).
/// \param config StripeAPMConfig with publishableKey, clientSecret, transactionToken, etc.
///
+ (void)presentWithConfig:(StripeAPMConfig * _Nonnull)config;
/// Configures and presents the Stripe PaymentSheet for APM checkout from the given view controller.
/// Prefer <code>present(config:)</code> so the SDK finds the topmost VC (works with sheets/alerts).
/// \param config StripeAPMConfig with publishableKey, clientSecret, transactionToken, etc.
///
/// \param viewController The UIViewController to present the PaymentSheet from.
///
+ (void)presentWithConfig:(StripeAPMConfig * _Nonnull)config from:(UIViewController * _Nonnull)viewController;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Custom submit label enum that maps to SubmitLabel on iOS 15+
typedef SWIFT_ENUM(NSInteger, SpreedlySubmitLabel, open) {
  SpreedlySubmitLabelReturn = 0,
  SpreedlySubmitLabelDone = 1,
  SpreedlySubmitLabelGo = 2,
  SpreedlySubmitLabelSearch = 3,
  SpreedlySubmitLabelSend = 4,
  SpreedlySubmitLabelNext = 5,
  SpreedlySubmitLabelJoin = 6,
  SpreedlySubmitLabelRoute = 7,
  SpreedlySubmitLabelContinue = 8,
};

/// Objective-C compatible theme manager
/// This class provides Objective-C accessible methods for theme management
SWIFT_CLASS("_TtC10SpreedlyUI24SpreedlyThemeManagerObjC")
@interface SpreedlyThemeManagerObjC : NSObject
/// Set global theme with separate light and dark themes using SPLThemeConfig
/// \param lightThemeConfig The theme configuration for light mode
///
/// \param darkThemeConfig The theme configuration for dark mode
///
+ (void)setGlobalThemeWithLightConfig:(SPLThemeConfig * _Nonnull)lightThemeConfig darkConfig:(SPLThemeConfig * _Nonnull)darkConfig;
/// Set global theme using SPLThemeConfig (backward compatibility - uses same theme for both modes)
/// \param themeConfig The theme configuration to set as global (used for both light and dark modes)
///
+ (void)setGlobalThemeWithConfig:(SPLThemeConfig * _Nonnull)themeConfig;
/// Set global theme with separate light and dark themes using Android-style hex color configuration
/// \param lightPrimaryColorHex Primary brand color for light mode (e.g., “#0077C8”)
///
/// \param lightSecondaryColorHex Secondary brand color for light mode (e.g., “#AFB4B5”)
///
/// \param lightFormBorderColorHex Form field border color for light mode (e.g., “#D9D9D9”)
///
/// \param lightFormBackgroundColorHex Form background color for light mode (e.g., “#FFFFFF”)
///
/// \param lightFieldBackgroundColorHex Field background color for light mode (e.g., “#F8F9FA”)
///
/// \param lightFieldLabelColorHex Field label color for light mode (e.g., “#6C757D”)
///
/// \param darkPrimaryColorHex Primary brand color for dark mode (e.g., “#00A0FF”)
///
/// \param darkSecondaryColorHex Secondary brand color for dark mode (e.g., “#6C757D”)
///
/// \param darkFormBorderColorHex Form field border color for dark mode (e.g., “#4A4A4A”)
///
/// \param darkFormBackgroundColorHex Form background color for dark mode (e.g., “#1C1C1E”)
///
/// \param darkFieldBackgroundColorHex Field background color for dark mode (e.g., “#2C2C2E”)
///
/// \param darkFieldLabelColorHex Field label color for dark mode (e.g., “#AEAEB2”)
///
/// \param borderRadius Corner radius for form elements (default: 8.0)
///
+ (void)setGlobalThemeWithLightHexColorsWithLightPrimaryColorHex:(NSString * _Nonnull)lightPrimaryColorHex lightSecondaryColorHex:(NSString * _Nullable)lightSecondaryColorHex lightFormBorderColorHex:(NSString * _Nullable)lightFormBorderColorHex lightFormBackgroundColorHex:(NSString * _Nullable)lightFormBackgroundColorHex lightFieldBackgroundColorHex:(NSString * _Nullable)lightFieldBackgroundColorHex lightFieldLabelColorHex:(NSString * _Nullable)lightFieldLabelColorHex darkPrimaryColorHex:(NSString * _Nonnull)darkPrimaryColorHex darkSecondaryColorHex:(NSString * _Nullable)darkSecondaryColorHex darkFormBorderColorHex:(NSString * _Nullable)darkFormBorderColorHex darkFormBackgroundColorHex:(NSString * _Nullable)darkFormBackgroundColorHex darkFieldBackgroundColorHex:(NSString * _Nullable)darkFieldBackgroundColorHex darkFieldLabelColorHex:(NSString * _Nullable)darkFieldLabelColorHex borderRadius:(CGFloat)borderRadius;
/// Set global theme using Android-style hex color configuration (backward compatibility - uses same theme for both modes)
/// \param primaryColorHex Primary brand color (e.g., “#0077C8”)
///
/// \param secondaryColorHex Secondary brand color (e.g., “#AFB4B5”)
///
/// \param formBorderColorHex Form field border color (e.g., “#D9D9D9”)
///
/// \param formBackgroundColorHex Form background color (e.g., “#FFFFFF”)
///
/// \param fieldBackgroundColorHex Field background color (e.g., “#F8F9FA”)
///
/// \param fieldLabelColorHex Field label color (e.g., “#6C757D”)
///
/// \param borderRadius Corner radius for form elements (default: 8.0)
///
+ (void)setGlobalThemeWithHexColorsWithPrimaryColorHex:(NSString * _Nonnull)primaryColorHex secondaryColorHex:(NSString * _Nullable)secondaryColorHex formBorderColorHex:(NSString * _Nullable)formBorderColorHex formBackgroundColorHex:(NSString * _Nullable)formBackgroundColorHex fieldBackgroundColorHex:(NSString * _Nullable)fieldBackgroundColorHex fieldLabelColorHex:(NSString * _Nullable)fieldLabelColorHex borderRadius:(CGFloat)borderRadius;
/// Set global theme with separate light and dark themes using UIColor properties
/// \param lightPrimaryColor Primary brand color for light mode
///
/// \param lightSecondaryColor Secondary brand color for light mode (optional)
///
/// \param lightBackgroundColor Background color for light mode (optional)
///
/// \param lightBorderColor Border color for light mode (optional)
///
/// \param lightTextColor Text color for light mode (optional)
///
/// \param darkPrimaryColor Primary brand color for dark mode
///
/// \param darkSecondaryColor Secondary brand color for dark mode (optional)
///
/// \param darkBackgroundColor Background color for dark mode (optional)
///
/// \param darkBorderColor Border color for dark mode (optional)
///
/// \param darkTextColor Text color for dark mode (optional)
///
/// \param borderRadius Corner radius (default: 8.0)
///
+ (void)setGlobalThemeWithLightColorsWithLightPrimaryColor:(UIColor * _Nonnull)lightPrimaryColor lightSecondaryColor:(UIColor * _Nullable)lightSecondaryColor lightBackgroundColor:(UIColor * _Nullable)lightBackgroundColor lightBorderColor:(UIColor * _Nullable)lightBorderColor lightTextColor:(UIColor * _Nullable)lightTextColor darkPrimaryColor:(UIColor * _Nonnull)darkPrimaryColor darkSecondaryColor:(UIColor * _Nullable)darkSecondaryColor darkBackgroundColor:(UIColor * _Nullable)darkBackgroundColor darkBorderColor:(UIColor * _Nullable)darkBorderColor darkTextColor:(UIColor * _Nullable)darkTextColor borderRadius:(CGFloat)borderRadius;
/// Set global theme using UIColor properties (backward compatibility - uses same theme for both modes)
/// \param primaryColor Primary brand color
///
/// \param secondaryColor Secondary brand color (optional)
///
/// \param backgroundColor Background color (optional)
///
/// \param borderColor Border color (optional)
///
/// \param textColor Text color (optional)
///
/// \param borderRadius Corner radius (default: 8.0)
///
+ (void)setGlobalThemeWithColorsWithPrimaryColor:(UIColor * _Nonnull)primaryColor secondaryColor:(UIColor * _Nullable)secondaryColor backgroundColor:(UIColor * _Nullable)backgroundColor borderColor:(UIColor * _Nullable)borderColor textColor:(UIColor * _Nullable)textColor borderRadius:(CGFloat)borderRadius;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface UIViewController (SWIFT_EXTENSION(SpreedlyUI))
/// Wrap this view controller in a secure container (similar to SwiftUI’s .screenPrevention())
/// Automatically starts manager protection for app switcher overlay
/// \param placeholderText Optional text to display in screenshots/recordings (default: “”)
///
///
/// returns:
/// A container view controller with secure protection applied
- (UIViewController * _Nonnull)wrapInSecureViewControllerWithPlaceholderText:(NSString * _Nonnull)placeholderText SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, YearFormat, open) {
  YearFormatTwoDigit = 2,
  YearFormatFourDigit = 4,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
